### ISSUE TITLE
Ramda.js

### ISSUE THREAD

**Issue by gtrak** [charmCityJs/talks#1]
Your name: Gary Trakhman

Your idea: Ramda.js tutorial, a curried FP and collection library for JS.  I'll show off some basic convenience functions and build up to use of the curried style on promise chains, and maybe even transducers. 

Approx length: 10-15 min (remember, talks should be 10-20 min long, just estimate for us here)

Month(s) available: All the months!!!!

**Comment by latazzajones** [comment]
Great! I'll add this to our meetup page now :)
