### ISSUE TITLE
Passion Talk: :sparkles: :bread: :sparkles:

### ISSUE THREAD

**Issue by colestrode** [charmCityJs/talks#100]
**Your name:** 
Cole Furfaro-Strode

**Your talk idea, described briefly:**

Baking bread has finally hit the javascript mainstream, so let's not get left behind: https://twitter.com/mikemaccana/status/805876764845240320

I've been baking bread at home for about a year. It's geeky: you get to measure and weigh things, track time and temperature. But it also has room for creativity and self-expression. Baking also requires you to trust your instincts and your senses. In a lot of ways, it is like being an engineer.

I love baking bread and want to share with you all!

**Approx length: (must be less than 20 minutes to be considered*):**

5-7 minutes of delicious, nerdy excitement. I might even bring some samples!

**Comment by clickclickonsal** [comment]
Hey, @colestrode that's pretty cool! I would loaf if you can give this talk on June 7th! No pressure dough! 🙃

**Comment by colestrode** [comment]
Hey @clickclickonsal! Let me see check in what our family is up to that night, I'll get back to ya soon :)

**Comment by colestrode** [comment]
We're on! I'll start working on something :)

**Comment by clickclickonsal** [comment]
Awesome! Hope you can bake in at least one pun in your talk for me. ;-)

**Comment by colestrode** [comment]
Thanks for having me ❤️
