### ISSUE TITLE
Building Slack Bots for Fun and Profit (or At Least Fun) 

### ISSUE THREAD

**Issue by colestrode** [charmCityJs/talks#101]
**Your name:** 
Cole Furfaro-Strode

**Your talk idea, described briefly:**

I’ve built a lot of Slack bots, some of which we use every day at SparkPost to [keep us productive][1], some of which are for my own [entertainment][2]. My favorite thing about Slack bots is they are easy to build and entertaining, which makes them a great playground to learn more advanced engineering concepts. In this talk I’ll teach you how to build a Slack bot, how the [Skellington][3] library that I developed with @jasonrhodes can make this process even easier and how you can use bots to learn yourself some new tricks.

**Approx length: (must be less than 20 minutes to be considered*):** 18-20 glorious minutes

[1]:https://github.com/SparkPost/community-bot
[2]:https://github.com/colestrode/marky-markov
[3]:https://github.com/colestrode/skellington

**Comment by esauter5** [comment]
Are you available to give this talk on January 4, @colestrode ?

**Comment by colestrode** [comment]
Hey @esauter5 :) I think so, I need to double check my wife's schedule. Can I get back to you in a day or two?

**Comment by esauter5** [comment]
Works for me!

**Comment by colestrode** [comment]
We're good to go 🙂 The 4th works for me!

**Comment by esauter5** [comment]
Awesome. See you then!

**Comment by colestrode** [comment]
Slides! https://speakerdeck.com/colestrode/slack-bots-for-fun-and-profit-charm-city-js

**Comment by esauter5** [comment]
Thanks for giving this talk @colestrode!

**Comment by colestrode** [comment]
Thanks for having me 🙂
