### ISSUE TITLE
Introduction to D3

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#102]
**Your name:** Chris Uehlinger

**Your talk idea, described briefly:** D3 is a HUGE library, but you don't need to master all of it to be good at it. This talk will begin with an explanation of what D3 is, and a "map" of the many "regions" of D3. We'll take a look at how to make a basic bar chart with some simple animations, and end with some ways to learn more about the other parts of D3.

**Approx length:** 15-20 minutes

(I know I just gave a talk, but I want to give this one eventually. I thought I'd add it to the list in case you're short on speakers in the next couple months.)

**Comment by jasonrhodes** [comment]
Hey @chrisuehlinger we _are_ short this month, do you think you'd have this ready by next Wed?

**Comment by chrisuehlinger** [comment]
(*slurps coffee, tears page from typewriter, carriage returns*) I'd be glad
to help out. I've had this talk on the backburner for a while now, so I
don't think it'll be too tough to write.

**Comment by jasonrhodes** [comment]
Lol perfect

**Comment by jasonrhodes** [comment]
Thanks for speaking and on short notice too!
