### ISSUE TITLE
AppLab - Helping kids build simple apps with JavaScript

### ISSUE THREAD

**Issue by nikzb** [charmCityJs/talks#103]
**Your name:** Nik Baltatzis

**Your talk idea, described briefly:** AppLab is a learning tool designed by Code.org as part of their AP Computer Science Principles curriculum. The tool allows new programmers to quickly create simple web apps with JavaScript. I use the tool with my students and thought it would be cool to share it as something that people could then share with their kids, friends, etc, who are interested in learning a bit of JavaScript without having to necessarily learn a ton of other stuff first (You build your GUI with a GUI so HTML or CSS required. Code.org hosts the site and gives you a link to share. You can drag and drop or switch to typing code) To see a sample game I created, go [here](https://studio.code.org/projects/applab/eCkPhvM6fCEIQhjYVlJsLQ).

**Approx length:** (must be less than 20 minutes to be considered*):** 10-15 minutes

**Comment by jasonrhodes** [comment]
@nikzb this sounds great, are you able to give this for February?

**Comment by nikzb** [comment]
@jasonrhodes I could probably do it but I'm recovering from pneumonia, so it might be better to put it off for a later date

**Comment by jasonrhodes** [comment]
Hey @nikzb that's fine -- if you end up feeling better and want to give it a go, let me know this weekend.

**Comment by nikzb** [comment]
Hey @jasonrhodes, I am doing much better and should be definitely be good to go by Wednesday. If you have the slot open, I can go ahead and give the talk. Let me know.

**Comment by jasonrhodes** [comment]
Oh sorry @nikzb for not getting back to you sooner but yes, the slot is still open and we'd love to have you!

**Comment by nikzb** [comment]
@jasonrhodes Sounds good. See you on Wednesday.

**Comment by jasonrhodes** [comment]
Thanks again, @nikzb !
