### ISSUE TITLE
Visualize Open Baltimore Data

### ISSUE THREAD

**Issue by EmpiricalAnalysis** [charmCityJs/talks#104]
**Your name:** 
Johann Liang

**Your talk idea, described briefly:**
Baltimore City has provided the public access to many of its data sets in an effort to increase transparency. However, given the challenges in deciphering hundreds and sometimes millions of rows of number/text, we don't often hear how the availability of those data have helped improve citizens' life. To get started, I believe visualizing the data can generate good ideas of what to do about them. In this talk, I will show and explain the visualizations that I've built for data sets from the Open Baltimore portal.  

**Approx length: (must be less than 20 minutes to be considered*):**
10-15 minutes

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by jasonrhodes** [comment]
Hey @EmpiricalAnalysis are you still ok with giving this talk in February? We'd love to have you!

**Comment by EmpiricalAnalysis** [comment]
@jasonrhodes Thanks for having me! I love to give the talk, but I just started working on another data set which I think would be interesting to include in the talk. Time is a bit tight to get ready for this month's meeting. Would there be a spot in March's meeting so I can give the talk then instead? Thanks again!

**Comment by jasonrhodes** [comment]
@EmpiricalAnalysis will you have something ready for March? No more excuses! ;)

**Comment by EmpiricalAnalysis** [comment]
Arrgh! Time flies! Would love to do the talk at the upcoming March meeting. Thanks, @jasonrhodes !

**Comment by jasonrhodes** [comment]
Yes! We're at Impact Hub remember! @clickclickonsal will be MC-ing and we'll be in touch soon.

**Comment by EmpiricalAnalysis** [comment]
Sounds great, @jasonrhodes and @clickclickonsal ! See you next Wednesday!

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @EmpiricalAnalysis !
