### ISSUE TITLE
Extend the Intro to WebGL and Three.js talk from December + Demo how I'm using it

### ISSUE THREAD

**Issue by rpchurchill** [charmCityJs/talks#105]
**Your name:** 
R.P. (Bob) Churchill
(rpchurchill.com)

**Your talk idea, described briefly:**
Chris Uehlinger gave such a nice intro to WebGL and Three.js in Dec '16 that I marched right home and started experimenting with it.  Within three days (of starting to work on it) I had extended an ongoing project of mine to use this technology, complete with the option to render it in stereoscopic VR.  There are lots of web pages out there that walk you through the basics but they don't tell you much more than what's in the initial tutorials.   My idea is to pick up where Chris left off and describe what the next few steps in building and viewing a scene would involve (coordinate systems, camera location and direction, scaling, adding elements to a scene, modifying existing elements, tricks to make things more efficient).  I would also briefly describe and demo the project I'm working on, a flexible, user-definable discrete-event simulation framework.

**Approx length: (must be less than 20 minutes to be considered*):**
I can keep it down to 10 minutes if need be, or I can go longer, whatever gets me to the podium quickest.  I would definitely be ready for the February session.  :-)

![des-20170104](https://cloud.githubusercontent.com/assets/19749611/21648667/c155ab20-d26c-11e6-85a9-e891b042a22c.png)

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by rpchurchill** [comment]
testing...

**Comment by jasonrhodes** [comment]
Hey @rpchurchill are you still available to give this next week? I somehow missed this talk sitting here until just now!

**Comment by rpchurchill** [comment]
Sure.  What did you have in mind for duration?

**Comment by jasonrhodes** [comment]
10-15 is perfect

**Comment by rpchurchill** [comment]
Excellent.  Will do.

**Comment by jasonrhodes** [comment]
Thanks for talking!
