### ISSUE TITLE
Javascript has Blue Teeth

### ISSUE THREAD

**Issue by skratchdot** [charmCityJs/talks#106]
**Your name:** 
Jeff S.

**Your talk idea, described briefly:**
"Javascript has Blue Teeth"

I'll talk a little about Bluetooth and give a very brief history touching on:
- Bluetooth EDR vs Bluetooth LE
- Centrals vs Peripherals
- GATT Services

I'll touch on node libs like:
- [noble](https://github.com/sandeepmistry/noble/)
- [bleno](https://github.com/sandeepmistry/bleno/)

I'll talk a bit about Web Bluetooth:
- https://webbluetoothcg.github.io/web-bluetooth/

Then I'll finish up by talking about a library I've been working on (perhaps a small demo).

**Approx length:**
I dunno. 10-20 minutes?

**Comment by jasonrhodes** [comment]
You good to give this in March?

**Comment by skratchdot** [comment]
@jasonrhodes - Yes. I should be able to work on something by then.  I still haven't finished the library I was referencing (haven't worked on it for over a month), but I'm guessing a week is enough time...

**Comment by jasonrhodes** [comment]
You're FILLING me with confidence, @skratchdot! We've got you booked for March.

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @skratchdot !  🔷📶
