### ISSUE TITLE
Let's Talk About ASTs

### ISSUE THREAD

**Issue by skratchdot** [charmCityJs/talks#107]
**Your name:** 
Jeff S.

**Your talk idea, described briefly:**
"Let's Talk About ASTs"

I'll talk about ASTs and why you should care about them (as a javascript developer).

I'll touch on libs that use ASTs and transforms:
- eslint
- babel
- jscodeshift

I'll demo [astexplorer](https://github.com/fkling/astexplorer).

**Approx length:**
~10 minutes

**Comment by oliikit** [comment]
Hey @skratchdot! We're going through old talks - would you be up for talking in September or October?

**Comment by skratchdot** [comment]
@oliikit - I have a broken ankle at the moment (so have missed the last 2 meetups).  I go back to the doctor in 4 weeks, so *maybe* I can do October, but I don't think I can commit to September.

**Comment by oliikit** [comment]
Ouch! Have a speedy recovery!

![](https://media.giphy.com/media/f6y4qvdxwEDx6/giphy.gif)

We may shoot for November then!

**Comment by skratchdot** [comment]
Haha. Thanks for the gif!  November sounds more doable.

**Comment by jasonrhodes** [comment]
@skratchdot you still prefer to wait for November? We've got room in Oct if you wanna do it then lmk asap

**Comment by skratchdot** [comment]
@jasonrhodes - I still prefer November b/c I will be in a boot and on crutches for a few more weeks, but should be off crutches by November.  If no one else steps forward, then I can probably make October work, but hopefully you can find someone else!
