### ISSUE TITLE
Using AWS Lambda, Node.js to build alexa skill

### ISSUE THREAD

**Issue by bizob2828** [charmCityJs/talks#108]
**Your name:** 
Bob Evans
**Your talk idea, described briefly:**
Show how easy it is to build an alexa skill to use for your echo dot.  I built integration with a list management service called wunderlist.  I'll show how to use AWS Lambda, creating the alexa skill and using it on your echo/echo dot.
**Approx length: (must be less than 20 minutes to be considered*):**
15mins
*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by clickclickonsal** [comment]
Alexa! Is @bizob2828 able to give this talk April 5th, 2017?

**Comment by bizob2828** [comment]
I think I can commit to that @clickclickonsal

**Comment by clickclickonsal** [comment]
Awesome, I'll book you for April. 👍

**Comment by clickclickonsal** [comment]
Alexa! Tell @bizob2828 'Thank you for giving this talk'. 🤖
