### ISSUE TITLE
Playing around with Puck.js

### ISSUE THREAD

**Issue by ChrisGuzman** [charmCityJs/talks#109]
**Your name:** Chris Guzman

**Your talk idea, described briefly:** I just got a [Puck.js](https://www.puck-js.com/) and I want to show you how easy it is to work with it! You'll learn how to use it as a beacon, measure light, temperature, magnetic fields & capacitance, control Infrared devices, or produce any colour light as well as using it as a programmable button!

**Do you consent to having your talk recorded\*, if we choose to do so?:** Yes

**Short talk title (optional):** Playing around with Puck.js

**Twitter username (optional):** https://twitter.com/speaktochris

**Length: (1-15 min please):** Anywhere between 5 and 15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by ChrisGuzman** [comment]
Wait can I name the talk "Pucking around with Puck.js"? Or is that a bit too NSFW?

kudos to @clickclickonsal for the idea

**Comment by clickclickonsal** [comment]
Can I book you for April 5th? 

and I'm ok with the name 😅 but I'll let @jasonrhodes decide that.

**Comment by ChrisGuzman** [comment]
May would be better. But I could do a 5 min presentation in April if you really needed me.

**Comment by clickclickonsal** [comment]
We can check back with you next month then. 🙃

**Comment by clickclickonsal** [comment]
@ChrisGuzman, May I ask how's May sound for giving this talk?

**Comment by clickclickonsal** [comment]
Closing this talk because you're leaving us 😞. Have a great pucking time in New Orleans 😄
