### ISSUE TITLE
Request: Babel, etc. / ES6 transpiling

### ISSUE THREAD

**Issue by jasonrhodes** [charmCityJs/talks#11]
Your name: Jason Rhodes

Your topic request: Writing ES6 is going to be more and more important so it'd be nice to understand how Babel works, what other transpiling options there are, how they compare.

**Comment by jasonrhodes** [comment]
testing

**Comment by paultyng** [comment]
I could do a talk about ES and transpiling, etc.  

Your name: Paul Tyng

Your idea: ES2015, TC39, Babel, etc.

Approx length: 15mins? 

Not sure the process for answering a request, should those details be in a new issue?

**Comment by jasonrhodes** [comment]
Hey @paultyng thanks for commenting, yeah I'd just go ahead and copy this to a new Issue and reference this one (use `#11`) and we'll go ahead and close this request. Seems like the easiest way to keep track. Thanks again!
