### ISSUE TITLE
Literature: A Path to Software Development

### ISSUE THREAD

**Issue by bolducp** [charmCityJs/talks#110]
**Your name:** Paige Bolduc

**Your talk idea, described briefly:**  As a developer who came from an entirely non-technical academic background and childhood upbringing, I'd like to give a talk about why I think "non-traditional" paths to tech can be valuable and productive. I'll explain some of the surprising ways in which studying literature prepared me to write software. In my talk I'll also briefly make a case for what I believe the tech community can learn from the humanities and why it's crucial to have collaboration between people in both. 

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Literature: A Path to Software Development

**Twitter username (optional):**  @paige_bolduc

**Length: (1-15 min please):** approx. 10 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
This sounds like a great talk! I can relate to the "non-traditional" path. Are you available to give this  talk for our next meetup, April 5th?

**Comment by bolducp** [comment]
Hi, Sal! Thanks! Yes, I'd love to give the talk at the April 5th meetup.

**Comment by clickclickonsal** [comment]
Awesome! You're booked for April!

**Comment by clickclickonsal** [comment]
Thanks for giving this awesome talk @bolducp! 👍 We hope to see/have you do more talks! 😄
