### ISSUE TITLE
Regular Expressions: /love/ 

### ISSUE THREAD

**Issue by rayners** [charmCityJs/talks#112]
**Your name:** David Raynes

**Your talk idea, described briefly:** A love story, as told with regular expressions.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Regular Expressions: /love/ (read as: Looking for love)

**CCJS Slack username:** rayners

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** rayners

**Length: (1-15 min please):** Probably 10-15m

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by rayners** [comment]
I don't get to most CCJS meetings, but I should be able to make it to May. And then again in September.

**Comment by clickclickonsal** [comment]
Hey @rayners, I'm going to book you for May. Does that still currently work for you?

**Comment by rayners** [comment]
Earliest I think is September. I'll have to double-check with the class schedules.

**Comment by jasonrhodes** [comment]
Closing this for now, @rayners would love to have you give this or another talk, just file a new issue and list available dates. Thanks!
