### ISSUE TITLE
Getting your secret squirrel on 

### ISSUE THREAD

**Issue by oliikit** [charmCityJs/talks#113]
**Your name:** Olivia

**Your talk idea, described briefly:** Going over the basics of securing your privacy of the web and being a true :shipit: 

**Do you consent to having your talk recorded, if we choose to do so?:**  Yep

**Short talk title (optional):**  Getting Your Secret :shipit: On

**CCJS Slack username:** olivia

**Twitter username (optional):** dothecodeolivia

**Length: (1-15 min please):** Probably 10 minutes. I'll try to make it around 10 minutes.

I may be able to present in May? I'll try (if you need me) 😬

**Comment by clickclickonsal** [comment]
Can I book you for May? :-D

**Comment by oliikit** [comment]
Sure let's do it!

**Comment by clickclickonsal** [comment]
Thanks again for giving this secure talk @oliikit!
