### ISSUE TITLE
Blockchain coding on the Ethereum network(Will come up with clever title later)

### ISSUE THREAD

**Issue by jjshab** [charmCityJs/talks#114]
**Domenic Thomas ** 

**overview of blockchain basics. Discussion of Ethereum, Solidity programming language and smart contracts** 

**Do you consent to having your talk recorded*, if we choose to do so? YES** 

**Short talk title (optional):** 

**CCJS Slack username: domenicthomas*

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional)joeyshabadoo:** 

**Length: 15 min should work** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
Thanks @jjshab! Per our discussion in Slack, you're all set for next Wednesday. Thanks for volunteering!

**Comment by jjshab** [comment]
Cool see you then

**Comment by clickclickonsal** [comment]
Thanks again for giving this talk @jjshab!
