### ISSUE TITLE
Youth Tech Mentoring.

### ISSUE THREAD

**Issue by DJFalcon23** [charmCityJs/talks#115]
Derek Fields

A talk on why it's important to mentor kids that are interested in modern tech, and how to get involved. 

Yes, you may record.

**Short talk title (optional):** 

CCJS: djfields

Twitter: DJFalcon23

10min

**Comment by clickclickonsal** [comment]
Hey @DJFalcon23, can you give this talk on June 7th?

**Comment by esauter5** [comment]
Thanks for giving this talk @DJFalcon23!
