### ISSUE TITLE
Business and Computer Ethics

### ISSUE THREAD

**Issue by inunotaisho26** [charmCityJs/talks#116]
Ethan Fairweather
 
A talk on the need for business ethics. An issue that is not completely under control.

Would like it to be, but yes

**Short talk title (optional):** 

CCJS:@ethanfairweather

Twitter username (optional):@eburrowfair
 
10 minutes

**Comment by inunotaisho26** [comment]
Cliff notes, I will be tying this topic into the challenger disaster in 1986. Something my family and I have a personal connection to. My hope is to use that to drive my points home.

**Comment by jasonrhodes** [comment]
@inunotaisho26 can you say a little more about the overview/outline for this talk? thanks!
