### ISSUE TITLE
Intro to Spike, a modern static build tool powered by webpack

### ISSUE THREAD

**Issue by tkraak** [charmCityJs/talks#117]
**Your name:**

Tom Kraak

**Your talk idea, described briefly:** 

[Spike](https://github.com/static-dev/spike) is a full featured static website generator written in JavaScript. It is built on top of webpack, and a foundation of HTML, CSS, and JS parsers that accept plugins to transform the output. It’s fast, actively developed, and very data-friendly.

**Do you consent to having your talk recorded*, if we choose to do so?:**

Yes.

**Short talk title (optional):** 

Intro to 🌵 spike, a modern static build tool, powered by webpack.

**CCJS Slack username:**

@tkraak

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

@tkraak

**Length: (1-15 min please):** 

15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @tkraak, can I book you for our June meetup?

**Comment by tkraak** [comment]
@clickclickonsal ... you sure can! Thx.

**Comment by esauter5** [comment]
Thanks for giving this talk @tkraak!
