### ISSUE TITLE
Hiding in plain sight, fun with steganography

### ISSUE THREAD

**Issue by CKarper** [charmCityJs/talks#118]
**Your name:** Chris Karper

**Your talk idea, described briefly:** A quick overview of what steganography is, and a demo of how it works/how to use node to build your own.

**Do you consent to having your talk recorded*, if we choose to do so?:** Sure

**Short talk title (optional):** Hiding In Plain Sight

**CCJS Slack username:** ckarper

**Twitter username (optional):** Wickity

**Length: (1-15 min please):** Probably 15-ish minutes.  I haven't written the talk, but it's a thick subject with a demo attached for funs.

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @CKarper, can I book you for our June meetup? I'd love to see 👀  this talk.

**Comment by CKarper** [comment]
Yeah, I'd really like to give this talk

except I'm not really

sure where the Meetup is this month.

**Comment by CKarper** [comment]
☝️  Read the first letter of each line.

**Comment by clickclickonsal** [comment]
Haha Very clever! 😄 It's gonna be at [MindGrub Technologies ](https://www.google.com/maps?f=q&hl=en&q=1215+East+Fort+Avenue,+Baltimore,+MD,+21230,+us)

**Comment by CKarper** [comment]
[Slides are available](https://github.com/ckarper/talk-steganography)

**Comment by esauter5** [comment]
Thanks for giving this talk @CKarper!
