### ISSUE TITLE
Why Your Next Side Project Should Be An Explorable Explanation

### ISSUE THREAD

**Issue by mgold** [charmCityJs/talks#12]
Your name: Max Goldstein

Your idea: What Explorable Explanations are (~ data telling a story interactively), how they differ from other kinds of software projects and data visualizations, why JS is well-suited for them, what work has been done, and what I learned building one (gnarly D3.js hacks), and what challenges still remain. Will appeal to UI designers and Bret Victor fans.

Approx length: 10-15 minutes

Month(s) available: April or May - please give me a week's notice so I can prepare

**Comment by jasonrhodes** [comment]
@mgold sounds awesome! Our events are on the first Wed of the month, and I think we're set for May. Can you add availability for the summer to your issue here? We'll _definitely_ be in touch 1-2 weeks in advance of the event. Thanks!

**Comment by mgold** [comment]
Oh right, there's not an April meeting... I could do June, but further out is sketchier. Looking forward to the inaugural May meetup!

**Comment by mgold** [comment]
I think I've got an angle that gives me something for both newcomers and experienced JS programers. It might run closer to 20 minutes though. Hopefully there's a slot in the next few months - I've really enjoyed the meetups so far!

**Comment by AimeeKnight** [comment]
@mgold Are you interested in presenting for July? If so, we'd like to have you speak!

**Comment by mgold** [comment]
Yes, I'd be happy to. Thanks!

**Comment by AimeeKnight** [comment]
@mgold Great. Let us know if you have any questions. Looking forward to it!

**Comment by mgold** [comment]
@AimeeKnight Will the talk be recorded? And can I go last?

**Comment by AimeeKnight** [comment]
@mgold I'm not sure if it'll be recorded. @jasonrhodes, do you know? Also, going last should be fine.

**Comment by jasonrhodes** [comment]
Our talks are not recorded at this time, no.

**Comment by mgold** [comment]
[Slides](http://slides.com/mgold/explorable-explanations/fullscreen#/1) but I'll have my laptop. See you in a bit.
