### ISSUE TITLE
How to get started with DIY electronics.

### ISSUE THREAD

**Issue by alimacattack** [charmCityJs/talks#121]
**Alison MacMullan:** 

**Six months ago, I knew nothing about circuits or electronics or microcontrollers.  Now, I feel like I might know something (I even won 3rd prize in hardware at the Baltimore Hackathon).  I'd like to talk about how to select and buy a basic electronics toolkit, how to solder, online resources, community maker spaces, how to program an Arduino, and some demonstrations of things I've built.  ** 

**Do you consent to having your talk recorded*, if we choose to do so?: Yes, sounds great!** 

**Short talk title (optional):** 

**AlisonMacMullan:**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):  Ten minutes.** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
@alimacattack are you available to give this for July 5? we're thinking of doing a "maker" theme for the night (ish) and this would be an excellent fit

**Comment by alimacattack** [comment]
Yes, put me on the schedule! Can't wait for the other "maker" talks!

**Comment by esauter5** [comment]
Thanks and great job on this talk @alimacattack!
