### ISSUE TITLE
Elm Overview

### ISSUE THREAD

**Issue by jovid78** [charmCityJs/talks#123]
**Name:** Jose Vidal

**Talk Description:**
A brief overview of Elm functional programing language.

_Disclaimer:_ I'm no expert of elm. I was just curious about it and did some small tutorials to get the gist of it.

The talk is about Elm's syntax and main traits.

**Title:** An Overview of Elm

**CCJS Slack:** jovid78

**Length:** 12Min

(Recording of Talk is OK)

**Comment by jasonrhodes** [comment]
@jovid78 you available to do this one for october 4 at under armour?

**Comment by jovid78** [comment]
Yes.
Should I aim at making it 10 min or 15min?

**Comment by jasonrhodes** [comment]
Closer to 10 would be great.

**Comment by jovid78** [comment]
ok

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @jovid78!
