### ISSUE TITLE
Vue.js

### ISSUE THREAD

**Issue by jovid78** [charmCityJs/talks#124]
Jose Vidal

**Talk Description:** A brief introduction into the Vue.js Framework.

**Title:** What's up with Vue? 

**CCJS Slack username:** jovid78

**Length:**  12min

(recording is ok)

**Comment by jasonrhodes** [comment]
@jovid78 you think you can keep this to 10 min?

**Comment by jovid78** [comment]
Think so.  Will keep it short.

**Comment by jasonrhodes** [comment]
Cool @jovid78 are you available for July 5?

**Comment by jovid78** [comment]
@jasonrhodes ,  yep. I'm available

**Comment by esauter5** [comment]
Thanks for giving this talk @jovid78!

**Comment by jovid78** [comment]
@esauter5  You're welcome!  Thanks for having me.
