### ISSUE TITLE
Brawn Up and Brain Out

### ISSUE THREAD

**Issue by sparkysmitty** [charmCityJs/talks#125]
**Your name**:
Dave Smith

**Your talk idea, described briefly:** 
"Passion Talk" about making things.  Synergizes with meeting at City Garage -- **_The Foundery_** is in the same building, and they are willing to host a tour for the Meetup group (during break, after meetup, **_[need to tell them when]_**).  They have everything from basic forging and welding to a full wood shop to industrial CNC capabilities, and more -- very cool stuff.   In my experience manipulating the physical realm helps sharpen (and clarify) the ethereal constructs we work within.  Restated, build stuff you can touch and stay healthy.

**Do you consent to having your talk recorded, if we choose to do so?:** 
Sure, just get my good side.

**Short talk title (optional):**
 Brawn Up and Brain Out

**CCJS Slack username:**
sparky

**Twitter username (optional):** 
n/a

**Length: (1-15 min please):** 
10 min.

**Comment by jasonrhodes** [comment]
@sparkysmitty we're thinking of doing a "maker" theme for the July meetup and so this would fit great, can you do it for July 5? 

Also: we'd like to do the Foundery tour if we can make it work time-wise, I think having it be the last thing makes sense but timing will be slightly hard to predict so we'd have to tell them "sometime around 8:30-9ish"... if they would prefer a more solid or earlier time we could do our intro right at 7:30 and then walk over and be there around 7:50/8

**Comment by sparkysmitty** [comment]
Yes, can definitely do a talk on the 5th that will completely be in sync with a maker theme.

Will speak to Foundery folks regarding timing -- I got the impression that some amount of ambiguity is fine with them, I think they just wanted a framework to work within.   Will provide info when I get it.   Thanks much.

**Comment by esauter5** [comment]
@sparkysmitty Thanks so much for this talk @sparkysmitty. You definitely inspired me a bit, plus the tour after was great!
