### ISSUE TITLE
Neo4j, a graph database for highly interconnected data

### ISSUE THREAD

**Issue by jgaskins** [charmCityJs/talks#126]
**Your name:** Jamie Gaskins

**Your talk idea, described briefly:** Relational databases are pretty good at modeling how data is directly connected to other data, but if you need to see how data is _indirectly_ connected or you need to query on too many `JOIN`s, it starts having trouble. In this talk, we'll discover what that friction is with a SQL database and how Neo4j solves it.

**Do you consent to having your talk recorded, if we choose to do so?:** only if you capture my good side

**Short talk title (optional):** Neo4j

**CCJS Slack username:** jamie

**Twitter username (optional):** jamie_gaskins

**Length: (1-15 min please):** imma need the full 15 for this

**Comment by clickclickonsal** [comment]
You're are on the `charts` for next week! 🙃

**Comment by jgaskins** [comment]
Posted in Slack, but someone recommended that I post my [slides](https://charmcityjs.slack.com/files/jamie/F6H47QM6D/neo4j_-_charmcityjs.pdf) here, as well, which I thought was a good idea.

Thanks for letting me talk about things I like talking about!
