### ISSUE TITLE
Clojurescript - Pros and cons of a compile-to-js language

### ISSUE THREAD

**Issue by smitch88** [charmCityJs/talks#128]
**Your name:** 
Scott Mitchell

**Your talk idea, described briefly:** 
Give an overview of Clojurescript, a compile-to-js language based on Clojure. Illustrate at a high level w/ the pros and cons for Clojurescript compared to using modern js by looking at functional programming, interop w/ native js libs like React and highlighting code differences between Clojurescript and native Javascript and how each language tackles a particular set of problems.

**Do you consent to having your talk recorded, if we choose to do so?:** 
Sure, why not.

**Short talk title (optional):** 
What's this Clojurescript thing?

**CCJS Slack username:**
sbmitchell

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
15

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@smitch88 Any interest in giving this talk next Wednesday (8/2)?

**Comment by smitch88** [comment]
@esauter5 I could do that

**Comment by clickclickonsal** [comment]
Thank you for giving this talk @smitch88! I'm going to `closure` issue. 😄
