### ISSUE TITLE
Quote Attribution in Fictional Writing using Machine Learning

### ISSUE THREAD

**Issue by negfrequency** [charmCityJs/talks#129]
**Your name:** 
William Kinsman

**Your talk idea, described briefly:** 
Subject: NLP/ML
This talk describes a method I took to take a fictional book and convert it into an audiobook where each character has a unique voice, by using machine learning. Fictional books are a unique challenge when inanimate objects can talk. In this demo I convert Harry Potter and the Sorcerers Stone into an audio book. In short, this does quote extraction, entity resolution, and matches quotes to entities to generate a script, and then converts it to an audio file. I've done this presentation a few times.
[QuoteAttribution.pptx](https://github.com/charmCityJs/talks/files/1148250/QuoteAttribution.pptx)

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yea

**Short talk title (optional):** 
Quote Attribution in Fictional Writing using Machine Learning

**CCJS Slack username:**
N/A

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/
email: kinsman.will@gmail.com

**Twitter username (optional):** 
None

**Length: (1-15 min please):** 
10min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@negfrequency Are you available to give a talk next Wednesday 8/2?

**Comment by negfrequency** [comment]
Absolutely! Looking forward to it

**Comment by negfrequency** [comment]
Eric,

I'll await your confirmation. If you need anything else prior let me know!

On Jul 25, 2017 09:50, "will kinsman" <kinsmanwill@gmail.com> wrote:

Absolutely! Looking forward to it

**Comment by esauter5** [comment]
@negfrequency You're all set. Let me know if you have any questions, otherwise I'll get in touch with you the day before or day of to make sure we are all squared away

**Comment by clickclickonsal** [comment]
Thank you for giving this talk @negfrequency!
