### ISSUE TITLE
Talk idea: Under Javascript's Hood.

### ISSUE THREAD

**Issue by andreikoenig** [charmCityJs/talks#130]
**Your name: Andrei Koenig

**Your talk idea, described briefly: This will be a beginner-oriented talk. Let's take a quick peek under the hood of Javascript to understand how it works. We will talk about JS's execution context and its phases, global object (that weird thing), variable environments and scope chains. I have been learning JS for only about a month, and some of these things helped me a lot to get my head around some of JS's quirks. Again, very beginner-focused talk.

**Do you consent to having your talk recorded*, if we choose to do so?: Sure.

**Short talk title (optional): Under Javasript's Hood for Dummies. ¯\_(ツ)_/¯

**CCJS Slack username: not registered yet, but will register (andreikoenig)

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): @andreikoenig

**Length: (1-15 min please): will keep under 15 min.

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Want to give this talk for our September 6th meetup?

**Comment by andreikoenig** [comment]
hey, @clickclickonsal , yes, it would be awesome!
