### ISSUE TITLE
Blockchain for Front End Developers

### ISSUE THREAD

**Issue by danawhite** [charmCityJs/talks#131]
**Dana A. White** 

**The talk will cover how to build an interface using React JS and Solidity that will allow users to conduct smart contract transactions on the Ethereum platform** 

**Yes** 

**Blockchain: Smart Contracts x React** 

**danawhite**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**absolutgenius** 

**15 mins** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Want to give this talk for our September 6th meetup?

**Comment by danawhite** [comment]
Absolutely.

**Comment by danawhite** [comment]
@clickclickonsal something came up on my end that will not allow me to travel to Baltimore for tonight's meetup. If possible, I would love to reschedule this talk for a later date. Pardon me for the late notice and please let me know if we can reschedule. Thanks!

**Comment by jasonrhodes** [comment]
Hey @danawhite do you want to try this again for October? As a heads up, we really try to get at least a few days' notice on cancellations if at all possible, so let me know if you feel reasonably sure you can do it for Oct 4 and we'd love to have you. :)

**Comment by danawhite** [comment]
@jasonrhodes yes, October 4th works beautifully. I will be in Baltimore for the entire week as it's Steelers Week and Baltimore Innovation Week ;) Let me know what, if anything else, you need from me beforehand. I'm looking forward to it.

**Comment by danawhite** [comment]
Does this mean that we are all good for 10/4?

**Comment by jasonrhodes** [comment]
Yes! Sorry, missed your message. I'll ping you in slack with more details this week.

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @danawhite!
