### ISSUE TITLE
Monorepos and Lerna

### ISSUE THREAD

**Issue by markbrocato** [charmCityJs/talks#132]
**Your name:** 
Mark Brocato

**Your talk idea, described briefly:** 
Are you developing a suite of packages that depend on one another, are released concurrently, and published separately (for example, via npm)? If so, you should consider putting them in a monorepo.  In this talk I'll explain the what monorepos are, the problems they aim to solve, explore the mechanics of using lerna to maintain a monoreop, and share my experience working with lerna on ExtReact.

**Do you consent to having your talk recorded*, if we choose to do so?:** 

Yes

**Short talk title (optional):** 

**CCJS Slack username:**

sencha.mark

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

@mockaroodev

**Length: (1-15 min please):** 

15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability**
Pretty much any time.

**Comment by jasonrhodes** [comment]
@markbrocato you available to do this one for october 4 at under armour?

**Comment by markbrocato** [comment]
Yes

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @markbrocato!
