### ISSUE TITLE
Talk: Escape from JS: A History of Compile to JS languages

### ISSUE THREAD

**Issue by carlmjohnson** [charmCityJs/talks#133]
**Your name:** Carl Johnson

**Your talk idea, described briefly:** A look at various ways that people have tried to get out of writing JS over the years by compiling something else to JS, from coffeescript to assembly JS to WASM to ES201x babelify and whatever else I can fit into a 15 minute talk.

**Do you consent to having your talk recorded, if we choose to do so?:** Sure

**Short talk title (optional):** Escape from JS: A History of Compile to JS languages

**CCJS Slack username:** carlmjohnson

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):**  carlmjohnson

**Length: (1-15 min please):** 15 minutes

**Comment by esauter5** [comment]
Thanks for speaking @carlmjohnson!
