### ISSUE TITLE
Microsoft Typescript and Open Source Projects

### ISSUE THREAD

**Issue by inunotaisho26** [charmCityJs/talks#134]
**name:** 
Ethan Burrow Fairweather

**talk idea, described briefly:**
I would like to showcase typescript used in Angular and React. I also have typescript open source libraries I'd like to ask if developers would be interested in contributing to. The first is Typescripting to teach Typescript at nodeschool. The second is a typescript navigation plugin for both React and Angular. 

**Do you consent to having your talk recorded*, if we choose to do so?:**
Hell, I'll bring the camera equipment myself!! (Yes). 

**Short talk title (optional):** 
Typescripting

**CCJS Slack username:**
@ethanfairweather

**Twitter username (optional):** 
@eburrowfair

**Length: (1-15 min please):** 
Probably 15 minutes as I have a lot of ground to cover.

**Comment by esauter5** [comment]
@inunotaisho26 Are you still interested in giving this talk? It's probably too long of a talk for this month since we already have a couple of 15 minute talks, but we could definitely get you on the schedule in the coming months.

**Comment by inunotaisho26** [comment]
@esauter5 That would be fine by me. I am still recovering from a laparoscopic long biopsy.  I have some weird infection in my lungs. Not deadly or contagious, just a nuisance infection.

Let me know what month you have in mind so I can prep. 

Thanks

**Comment by jasonrhodes** [comment]
@inunotaisho26 hey Ethan, two things:
1. First, we'd love to help with guiding you on this talk outline so that it fits well for the group--based on what you've outlined here it sounds like it might be more material than will fit well so if you can get us a more fleshed-out talk outline, we'll have time to give you some feedback.
1. Once we've had a back and forth about the talk outline, let's get a hard date scheduled for the talk so we can get you up there. 

Sound good? Thanks!

**Comment by oliikit** [comment]
Hey @inunotaisho26, just following up on @jasonrhodes request. We'd love to get in the schedule rotation, would you mind sending us over the talk outline either on here, Slack, or email (charmcityjs@gmail.com)? If you send it through email, just let us know so we can check that inbox. Thanks!

**Comment by inunotaisho26** [comment]
@jasonrhodes @oliikit Sorry for taking so long to get back to you. I would like to have a back and forth before I started on the talk. I probably need someone to bounce ideas off of so I have a clearer plan in place.

**Comment by jasonrhodes** [comment]
Sounds good, let's chat in Slack sometime this month and see what kind of plan we can come up with. For now I'll close this and we can re-open or start a new issue depending on the path we decide to take. Thanks!!
