### ISSUE TITLE
Getting expo-sed to Mobile Development 

### ISSUE THREAD

**Issue by clickclickonsal** [charmCityJs/talks#135]
**Your name:** 
Sal Hernandez

**Your talk idea, described briefly:** 
I'll be talking about the tool expo.io which is built on top of React Native. I'll first give a brief overview about RN and then introduce Expo & explain how it makes it easier than ever to build cross-platform apps all why only needing to know JavaScript. 😄 

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Sure

**Short talk title (optional):** 
Getting expo-sed to Mobile Development 

**CCJS Slack username:**
clickclickonsal

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
clickclickonsal

**Length: (1-15 min please):** 
15 mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
Thanks for giving this talk @clickclickonsal!
