### ISSUE TITLE
Primer on writing CLI utilities in nodejs

### ISSUE THREAD

**Issue by beardyman** [charmCityJs/talks#136]
**Your name:** 
Jordan Nornhold

**Your talk idea, described briefly:** 
An intro into writing basic CLI tools in nodejs. Examples for presentation include: 
- Simple hello world
- Handling CLI arguments
- Handling Input and Output
- Handling Bash piping

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Sure, if you want to.

**Short talk title (optional):** 
Primer on writing CLI utilities in nodejs

**CCJS Slack username:**
@beardyman

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@nornholdj

**Length: (1-15 min please):** 
~15min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by hyeinu** [comment]
Hi Jordon, I also messaged you on slack about possibly giving this talk for the upcoming meetup in November. Just wanted to make sure I was able to reach you so please let me know either on here or on slack if you are able to give this talk! Thank you!
