### ISSUE TITLE
Hiring is hard, but it shouldn't be hard on candidates. 

### ISSUE THREAD

**Issue by naterkane** [charmCityJs/talks#137]
![Whiteboarding is bullshit](https://media.glassdoor.com/lst/a7/7b/1f/1e/software-engineering-whiteboarding-session.jpg)

**Your name:** 
Nater Kane

**Your talk idea, described briefly:** 
Our industry has been moving over the last 20 years to making increasingly inhumane hiring techniques normal. Having a painful interview experience SHOULD NOT BE NORMAL.
* I'm going to cover a number of craptastic practices I've seen recruiters and employers take in their flailing attempts to recruit talent. 
* I'm then going to cover red flags and some tips to help you avoid a negative interview experience, as well as tips on how to handle yourself in a bad interview. 
* Lastly I'm going to share an example of an interview done right, where nobody is stressed and everyone wants to hug each other at the end.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Do it

**Short talk title (optional):** 
Know when to run screaming from a job interview

**CCJS Slack username:**
@naterkane

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@naterkane

**Length: (1-15 min please):** 
You tell me, but I think 10-15 will be needed (for all the anonymized shaming and kvetching)

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
Thanks for speaking, @naterkane!
