### ISSUE TITLE
Copywhat? A talk about Licenses, Patents, and why people were mad about React

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#138]
**Your name:** Chris Uehlinger

**Your talk idea, described briefly:** A lot of people are confused about all the legal “stuff” that floats around our code: Why do I need to put a License on my code? Why is some code copyrighted and some code patented? Is “patenta non-grantis” a real Latin phrase? In this talk I’m going to walk through the very basics of copyright and patents, compare the MIT license and the GPL, and bring all these ideas together to explain why people were so mad at Facebook this summer, and what they’ve done about it.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Copywhat? A talk about Licenses, Patents, and React

**CCJS Slack username:** uehreka

**Twitter username (optional):** uehreka

**Length: (1-15 min please):** 20 minutes (or 15 really heavy minutes)

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by hyeinu** [comment]
@chrisuehlinger Hi I messaged you on slack but wanted to make sure I am able to reach you about this upcoming meetup happening in November! Please let me know either here or on slack if you are able to give this talk. Thank you!

**Comment by hyeinu** [comment]
confirmed in slack!
