### ISSUE TITLE
Writing Integration test with webdriver.io

### ISSUE THREAD

**Issue by NicholasAaronBrady** [charmCityJs/talks#139]
**Your name:** 
Nick Brady

**Your talk idea, described briefly:** 
I'd like to show an extremely simple setup of how to get started with writing integration test in webdriver.io. I'll stand up a selenium server with chromedriver, and have a front end running locally that test are run against. The whole process is surprisingly quick and easy which is what I'd like to demonstrate. I'll also likely cover how I've used the page object pattern to keep things DRY and write test quickly/cleanly. Note I am only going to focus on test for the web (not android, etc.).

**Do you consent to having your talk recorded*, if we choose to do so?:** 
yes

**Short talk title (optional):** 
Writing Integration test with webdriver.io

**CCJS Slack username:**
@corgiplex

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@nickaaronbrady

**Length: (1-15 min please):** 
10-15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@NicholasAaronBrady Any interest in giving this talk at our meetup next Wednesday, January 3?

**Comment by NicholasAaronBrady** [comment]
Hi @esauter5 , I should have commented on this. I'm based out of California but used to work with a company in Baltimore. I no longer do and won't be heading out to Baltimore anymore so this should be closed :(. Great meet up! Enjoyed it when I went. @clickclickonsal sorry dude, hope you're doing well!

**Comment by esauter5** [comment]
All good, @NicholasAaronBrady. Thanks for letting us know!
