### ISSUE TITLE
Intro to Moment.js

### ISSUE THREAD

**Issue by alimi** [charmCityJs/talks#14]
Your name: Ali Ibrahim

Your idea: Dealing with dates and times in JavaScript sucks. Moment.js makes dealing with dates and times fun! I would do a brief talk with a couple of examples.

Approx length: 5 minutes

Month(s) available: June

**Comment by latazzajones** [comment]
This would be a great opening talk for July. I'll go ahead an put you down.

**Comment by jasonrhodes** [comment]
(and by July she meant June, for the record) :)
