### ISSUE TITLE
Why are you “await-ing” to use async

### ISSUE THREAD

**Issue by arei** [charmCityJs/talks#140]
**Your name:** Glen R. Goodwin

**Your talk idea, described briefly:** With Node.js 8 going LTS there is no better time to jump on the async bandwagon. This talk will introduce the concepts of async and await and go over why all the things you have done before (callbacks, promises) should be thrown out forever.. but not really... and why async/await is the future of JavaScript. 

**Do you consent to having your talk recorded, if we choose to do so?:** yes

**Short talk title (optional):** Why are you “await-ing” to use async

**CCJS Slack username:** arei

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** areinet 

**Length: (1-15 min please):** 15 minutes. (Why would you ever trust a software engineer giving estimates.)

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@arei Are you available to give this talk next Wednesday, January 3?

**Comment by arei** [comment]
No, sorry. Can do in February though.

**Comment by esauter5** [comment]
Sounds good! I'll mark you for February and check back in a few weeks before.

**Comment by jasonrhodes** [comment]
@arei reminder you're on for February, I can't await!

**Comment by arei** [comment]
Actually I need a postponement... sorry. My wife is in the hospital and recovery is going to take a few months with a lot of hands on care.

**Comment by jasonrhodes** [comment]
Sorry, @arei — best wishes.

**Comment by jasonrhodes** [comment]
Gonna close to avoid repeat intrusions -- feel free to re-open if/when you want to do this again.

**Comment by arei** [comment]
That’s fair.  Sorry about this, I really wanted to do it.  It you know.. life...
