### ISSUE TITLE
Comparative Memory Management: Native JS vs. Traditional Languages

### ISSUE THREAD

**Issue by rpchurchill** [charmCityJs/talks#141]
**Your name:**  
Bob Churchill

**Your talk idea, described briefly:** 
Memory management and the native JS Object model, comparison to memory management in traditional compiled languages.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Sure.  

**Short talk title (optional):** 
Comparative Memory Management: Native JS vs. Traditional Languages

**CCJS Slack username:**
qulatan

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
none

**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

No supporting materials yet, I'll add them as they're developed.

**Comment by esauter5** [comment]
@rpchurchill Are you available to give this talk next Wednesday, January 3?

**Comment by rpchurchill** [comment]
Sure, I'll be ready.  It'll be short and sweet and I'll have the slides up a couple of days ahead of time for your review.

**Comment by rpchurchill** [comment]
rpchurchill.com/presentations/JavaScriptMemoryMgt/

**Comment by esauter5** [comment]
Thanks again for giving this talk the other night, @rpchurchill!
