### ISSUE TITLE
AWS Lambda Fundamentals

### ISSUE THREAD

**Issue by liamzdenek** [charmCityJs/talks#144]
#**Your name:** Liam Zdenek

**Your talk idea, described briefly:** AWS Lambda is a low-cost function execution service with strong scalability, both in price and performance. This talk covers the fundamentals of using JS with AWS Lambda.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** AWS Lambda Fundamentals

**CCJS Slack username:** N/A

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 10 mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
@liamzdenek are you available to give this on February 7?
