### ISSUE TITLE
Mapping the Wall between the Known and the Unknown, with 3JS, etc.

### ISSUE THREAD

**Issue by vand1** [charmCityJs/talks#146]
**Dennis VanDusen** 

**The Wall is where people can find the greatest detail about a topic, such as what the newest ideas are in a technology. Mapping that wall requires the assembly of many ideas from a large crowd, assembling with that information Huge (bigger than Big) data from ML, and 'semantic triples', using a consensus engine to produce a hierarchical graph where the leaves are the the most specific and the root most general in scope. The rest is just providing incentives, such as yielding valuations of technologies 20-50 years in the future.** 

**Yes (will only be discussing what is in a granted patent)*, if we choose to do so?:** 

**Mapping That Wall:** 

**vand1**

Loci - locipro.com - is seeking JS developers, and esp 3JS, Angular5, TypeScript, D3 developers. They are developing this commercially. 
 
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@vand1 Can you provide a little more detail about this talk? The description is a little abstract to me and I'm just trying to get a better understanding so we can figure out how to fit this talk in. It definitely sounds interesting!

**Comment by vand1** [comment]
Eric:  Sorry that I got talking to others rather than you last night.  
If you would like to have me explain the concept and how it ties into JS 
and front end work, I can do so on the phone when you wish - just pick a 
time.

And, of course, my son's company is moving fast and needs people. There 
was not too much interest shown last night, but whatever. It is really 
advanced work, intellectually challenging, and extremely valuable both 
for the participants and society.

Thx

D

**Comment by esauter5** [comment]
@vand1 It was great getting to meet you. We would love to have you or your son at a future meetup to explain the tech more. I think people would really enjoy it. Let me know if this is of interest.

As far as job interest, we have a #jobs channel in our Slack. Feel free to post information there as you will reach a bigger audience than the people who attended the meetup the other night.

**Comment by jasonrhodes** [comment]
@vand1 hey there! I think it'd help us understand how to fit something like this in if we understood the outline a bit better. Can you put together a slightly more fleshed-out outline of the talk and send it over either as a comment here or emailed to charmcityjs@gmail.com ? If you email, ping us here too so we remember to check that inbox. Thanks!

**Comment by oliikit** [comment]
Hey @vand1, just following up here. We'd like to schedule you in to talk soon, but we would just like to have some clarification on your talk. If you have slides or an outline available, can you post them here or email it to charmcityjs@gmail.com? Thanks! Look forward in hearing from you!

**Comment by jgzamora** [comment]
@vand1 We're closing this submission due to unresponsiveness. Please feel free to re-submit sometime later. Also, if it is your son who is giving the talk, please have him submit instead. Thank you

**Comment by dvandusen** [comment]
An email with a presentation was sent to charmcityjs@gmail.com on 1/29/18 10:30 AM.  Please confirm that the email was seen.
