### ISSUE TITLE
Telling Stories in React

### ISSUE THREAD

**Issue by merlinpatt** [charmCityJs/talks#147]
**Your name:** Merlin Patterson

**Your talk idea, described briefly:** How to use React Storybook to write and test components

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Telling Stories in React

**CCJS Slack username:** merlin

**Twitter username (optional):** merlinpatt

**Length: (1-15 min please):** 5

**Comment by jasonrhodes** [comment]
@merlinpatt are you available to give this on February 7?

**Comment by merlinpatt** [comment]
Unfortunately I won't be free on the 7th. The earliest I can give the talk is April 4th

**Comment by jasonrhodes** [comment]
Ah ok, I'll close for now and you re-open when you're available for consideration again, if you don't mind. Thanks!
