### ISSUE TITLE
Testing email delivery with MailSlurp

### ISSUE THREAD

**Issue by jgzamora** [charmCityJs/talks#149]
**Your name:** 
Jose Zamora

**Your talk idea, described briefly:** 
Quick demo of testing email delivery using MailSlurp, a new tool / API. What it is & why you should.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
No

**Short talk title (optional):** 
either "End-2-end email tests made easy" or "Testing email delivery with MailSlurp"...idk
**CCJS Slack username:**
jose

**Twitter username (optional):** 
@josegzamora

**Length: (1-15 min please):** 
5 min

**Comment by oliikit** [comment]
Hey @jgzamora! Would you like to present next Wednesday, March 7th?

**Comment by jgzamora** [comment]
Sure thing!

**Comment by oliikit** [comment]
Thanks for giving a great talk @jgzamora! 🙇‍♀️
