### ISSUE TITLE
Talk Proposal: Virtual Rendering Techniques in Modern Browsers

### ISSUE THREAD

**Issue by chrisdibble** [charmCityJs/talks#15]
Your name: Chris Dibble

Your idea: I'd love to introduce the concept of "virtual rendering" to the CharmCityJS community. Virtual rendering uses a combination of scroll/page positioning along with predictive user behavior to determine when elements should be rendered (or removed) to the DOM. Useful for linear (both long and/or wide) web layouts, virtual rendering can significantly improve the performance of your web application. I've created an example project implementing virtual rendering into a spreadsheet-like application written in JavaScript from the ground up that I'd love to share with the community. Metrics will be provided on the performance impact of virtual rendering compared to traditional rendering, along with code samples and a live demo.

Approx length: 15-20 minutes

Month(s) available: June, July, August

**Comment by AimeeKnight** [comment]
@chrisdibble We'd like to hear about this in July! Are you still available? If possible we'd also like to keep it closer to the 15 minute mark.

**Comment by chrisdibble** [comment]
Hi @AimeeKnight - I would be available in July and would love to give a talk on virtual rendering. I can certainly limit it as short as you need. What do you need from me if I were to be a presenter? Thanks for getting back to me, really excited about speaking and have been enjoying CharmCityJS a lot thus far!

**Comment by AimeeKnight** [comment]
@chrisdibble confirmation is all we need. 😀

**Comment by chrisdibble** [comment]
@AimeeKnight @jasonrhodes  I just got word that I'll have to be out of town the week of June 28th - July 5th. I'm still really eager to present (already have most of my slides done and together), could I possibly bump this back until the August meetup? Sorry!

**Comment by jasonrhodes** [comment]
Hey Chris, sorry it won't work out for July! We'll be picking August talks in a few weeks, so you'll hear from one of us. If not for August, sometime soon! Have a good trip and thanks for letting us know.

**Comment by apechimp** [comment]
@chrisdibble do you want to give the 15 minute version of this talk at the August 5th meetup?

**Comment by chrisdibble** [comment]
Sure, sorry, I was on vacation this past week and didn't see this until now. Thanks for keeping me in mind.

**Comment by apechimp** [comment]
Great! Thanks so much! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).

**Comment by chrisdibble** [comment]
Hey @AimeeKnight @apechimp @jasonrhodes ,

Unfortunately I'm going to have to cancel my talk later tonight, I've come down with a pretty nasty stomach bug this morning. My kids had it this past weekend, my wife had it earlier in the week, and now I'm doomed. I'm pretty bummed about missing the meetup in general, not to mention giving a talk. I'm just honestly not in an shape for standing in front of 60+ people for any amount of time.

So sorry to have to back out, especially on the day of. I know this puts you all (the organizers) in a crappy position. :(

Thanks for understanding,
Chris

**Comment by apechimp** [comment]
No worries! Hope you feel better soon! We kinda over booked tonight anyways :smile:

**Comment by apechimp** [comment]
@chrisdibble, We looking to schedule this talk for our 12/2 meetup. Think you can get the 15 minute version in shape for then?
