### ISSUE TITLE
Server Side React Rendering

### ISSUE THREAD

**Issue by eli0shin** [charmCityJs/talks#150]
**Your name:** 
Eli Oshinsky

**Your talk idea, described briefly:** 
React.js server side rendering. Why, why not, and what makes it so hard. Introduction to challenges involved and some of their solutions.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Absolutely

**Short talk title (optional):** 
Isomorphic Javascript and other useless buzzwords

**CCJS Slack username:**
eli0shin

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
eli0shin

**Length: (1-15 min please):** 
I'lll try to keep it to 10 but may run closer to 15

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
@eli0shin are you available for this talk on Feb 7?

15 min is of course fine, but consider this a friendly challenge to try for 10 and see if you end up with a tighter, more focused talk. :)

**Comment by eli0shin** [comment]
@jasonrhodes Feb 7 is perfect. Challenge accepted

**Comment by oliikit** [comment]
Thanks for giving the talk!
