### ISSUE TITLE
Redux Side Effects with RxJS

### ISSUE THREAD

**Issue by liamzdenek** [charmCityJs/talks#151]
**Your name:** Liam Zdenek

**Your talk idea, described briefly:** This is a continuation of my RxJS talk from January. This is introducing the redux middleware `redux-observable` to handle side effects. This talk requires a fundamental understanding of Redux. Familiarity with Sagas will help understanding, but isn't essential.

redux-observable presents to the user a stream of actions, and expects the user to return another stream. Side effects are handled by writing Rx operator chains that produce new actions. This talk is a live coding demo with the objective of solving a common side effect pattern.

**Do you consent to having your talk recorded, if we choose to do so?:** I was disappointed that the last one wasn't recorded, because several people asked for it. This question is actually a NOOP, but you have consent anyway.

**Short talk title (optional):** 

**CCJS Slack username:** liam

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 15.

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
Hey @liamzdenek -- thanks for all the talk submissions! I'm closing them for now since you just gave a talk last month, but we will re-open and sync back up with you after a few months or if we end up in a pinch before then.
