### ISSUE TITLE
Misconceptions About Progressive Web Apps

### ISSUE THREAD

**Issue by jgaskins** [charmCityJs/talks#152]
**Your name:** Jamie Gaskins

**Your talk idea, described briefly:** Progressive Web Apps are hype af, but the front-end community at large seems to be under the impression that the only way to create a PWA is in the style of Google: `ServiceWorker`, Web App Manifest, etc. In this talk, you'll learn why that's false, why we believe it, and why it matters. Hopefully, you'll also pick up a few tricks that web developers have used to great effect for almost 20 years now.

**Do you consent to having your talk recorded\*, if we choose to do so?:** Sure

**Short talk title (optional):** Misconceptions about Progressive Web Apps

**CCJS Slack username:** jamie

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** jamie_gaskins

**Length: (1-15 min please):** 15

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
@jgaskins hey man, wanna do this on Feb 7?

**Comment by jgaskins** [comment]
Absolutely

**Comment by oliikit** [comment]
Thanks for giving the talk!
