### ISSUE TITLE
Transcribing Lectures with GCP Speech API and Serverless

### ISSUE THREAD

**Issue by lamroger** [charmCityJs/talks#153]
**Your name:** Roger Lam

**Your talk idea, described briefly:** My partner attends JHU and tends to skip lectures. To help with catching up with 10 hours of lectures before a midterm, I transcribed lectures using GCP Speech API and automated most of it with Serverless.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Transcribing Lectures with GCP Speech API and Serverless

**CCJS Slack username:** Roger Lam

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @lamroger

**Length: (1-15 min please):** 10 mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by jasonrhodes** [comment]
This sounds great, @lamroger are you available to do this for Feb 7?

**Comment by lamroger** [comment]
Yea! Let's do it!

**Comment by jasonrhodes** [comment]
Perfect! I'll ping you in Slack with more details. :)

**Comment by oliikit** [comment]
Thanks for giving the talk!
