### ISSUE TITLE
Diversity Hiring

### ISSUE THREAD

**Issue by pgrant1** [charmCityJs/talks#154]
Patrick Grant 

Present diversity hiring for the future, how technology is creating new opportunities for people with disabilities.  Autism and coding. 

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes
**Short talk title (optional):** 

**CCJS Slack username:**
Patrick Grant
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
pgrant2311
**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by oliikit** [comment]
@pgrant1 Hey, we would love to include you in one of our meetups. However, I do have some questions. What technology are you particularly going to present on? Are you going to talk about the current problems with hiring disabilities (like statistics on diversity hiring)? 
It would be great to bring more awareness to this topic.

**Comment by pgrant1** [comment]
Hi Olivia,

I would present on the team of Autistic developers that I work with who are
performing software testing for BOSE.  My presentation would center around
diversity hiring and where people with disabilities are making great
strides in development, coding, testing, and analytics. Everyone has
special abilities.

-Patrick


[image: photo]
Patrick Grant
President, A6 STAFFING
<http://www.linkedin.com/in/patrick-grant-17343539/>
<http://twitter.com/pgrant2311>
  703-382-6196
  315-730-2348
  pgrant@a6staffing.com
  www.a6staffing.com
  1775 Tysons Blvd, 5th Floor Tysons, VA 22102
<http://www.linkedin.com/in/patrick-grant-17343539/>
<https://calendly.com/pgrant-1/30min> Schedule meeting with me
<https://calendly.com/pgrant-1/30min>

**Comment by oliikit** [comment]
Sounds great @pgrant1! Would you like to present next Wednesday, March 7th?

**Comment by pgrant1** [comment]
That would be wonderful, count me in. What are the logistics? Amount of
time, size of audience?

-Patrick

On Mar 1, 2018 1:36 PM, "Olivia Brundage" <notifications@github.com> wrote:

Sounds great @pgrant1 <https://github.com/pgrant1>! Would you like to
present next Wednesday, March 7th?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/charmCityJs/talks/issues/154#issuecomment-369687475>,
or mute the thread

**Comment by oliikit** [comment]
Wonderful! We typically have about 50-60 people come. You can find a list of attendees here: https://www.meetup.com/charmcityjs/events/lbvzgpyxfbkb/ 
You'll be second, so expect to speak around 8 PM. The meetup starts at 7:30, but please arrive around 7 to test out your computer. Please have all your slide material locally on your computer as the WiFi can be unreliable.

**Comment by pgrant1** [comment]
Good morning,

Do you provide food and drinks this evening? If so, I would like to sponsor.

-Patrick

**Comment by oliikit** [comment]
Hi @pgrant1 we do provide food and drinks for the event. If you would like to sponsor for a future event, you can send us an email at charmcityjs@gmail.com.

**Comment by oliikit** [comment]
Thanks for giving a great talk @pgrant1! 🙇‍♀️

**Comment by pgrant1** [comment]
Thank you for having me, it was a fun night.  Please let me know when the
site is up and I will sponsor the next meetup.

-Patrick


[image: photo]
Patrick Grant
President, A6 STAFFING
<http://www.linkedin.com/in/patrick-grant-17343539/>
<http://twitter.com/pgrant2311>
  703-382-6196
  315-730-2348
  pgrant@a6staffing.com
  www.a6staffing.com
  1775 Tysons Blvd, 5th Floor Tysons, VA 22102
<http://www.linkedin.com/in/patrick-grant-17343539/>
<https://calendly.com/pgrant-1/30min> Schedule meeting with me
<https://calendly.com/pgrant-1/30min>
