### ISSUE TITLE
How to Create An Automated Data Extraction Tool

### ISSUE THREAD

**Issue by joromewarner** [charmCityJs/talks#155]
**Your name:** Jorome Warner

**Your talk idea, described briefly:**   A talk geared toward new people like myself learning how to program. I built a web performance metric script, that collects data for each Url being tested.

**Do you consent to having your talk recorded*, if we choose to do so?:**  Sure

**Short talk title (optional):**

**CCJS Slack username:** Jorome

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 10min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by oliikit** [comment]
Hey @joromewarner! Excited to hear you have a beginner-friendly talk. Would you like to present on our March meetup on the 7th?

**Comment by joromewarner** [comment]
Yes, I'll present. I look forward for the opportunity and thank you.

**Comment by oliikit** [comment]
Thanks for giving a great talk @joromewarner! 🙇‍♀️
