### ISSUE TITLE
Blockchain is not Bitcoin - More

### ISSUE THREAD

**Issue by javastl** [charmCityJs/talks#157]
Peter Treese

What does Blockchain provide to the industry? Which API are you talking about
Ethereum, EOS, Hyberledger
You can record if the talk turns out 

Hyperledger fabric
What qualities of Blockchain are you needing
Public/Private
What is in your block of data?
What is consensus?
Do you need to mine a token all the time?

Slack ID ptreese

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey Peter this sounds exciting. Are you available to do this for April 4th?

**Comment by javastl** [comment]
Yes. have 36-page document that I have writing for as an Introduction to Blockchain.  I have get it down to a 7 page slide set to keep for the 15 min talk

**Comment by clickclickonsal** [comment]
Awesome I'll book you for April 4th. 👍 
And Oh my. 😅 I think if you focus on touching the topics you mentioned above at a high level you can keep it under 15 mins.

**Comment by clickclickonsal** [comment]
Thank you for giving a talk @javastl!
