### ISSUE TITLE
Talk Proposal: A Visual Approach to Learning JS

### ISSUE THREAD

**Issue by nikzb** [charmCityJs/talks#158]
**Name:** Nik Baltatzis

**Talk:** A Visual Approach to Learning JS: I will show how to use an online tool for visualizing code execution ("Python Tutor", which is not just for Python, it has JS amongst several other languages) and highlight how it helps people understand what exactly is going on as the code executes line by line. I will probably show some basic examples, and then a few examples of how visualizing the memory helps us understand trickier JS concepts like Prototypal inheritance or closures. I might also briefly present a few interactive tools I have built that let visualize other CS concepts like fractional numbers in binary, RGB colors, and lists, although it might be better to save those for another time.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** I see you JS! A visual approach to understanding code.

**CCJS Slack username:** nikzb

**Twitter username (optional):** nikzb7e

**Length: (1-15 min please):** 10-15, I can keep it to 10 if you want me to or go up to 15 if the other talks are not going to be super long. Just let me know

Note: Realistically, I probably will be able to better prepare this talk if I don't present in April as I am starting a new job in a couple weeks.

**Comment by clickclickonsal** [comment]
Hey Nik this sounds super cool. As for time length of this talk it's up to you. We're fine with either 10 or 15. 😄  Are you available to do this for April 4th?

**Comment by nikzb** [comment]
@clickclickonsal Hey Sal: In that case, I will probably be close to 15 minutes and try not to go over. April 4th is good. I am trying to make the talk title more fun. Maybe something like "I see you JS! A visual approach to understanding code", or is that too long now?

**Comment by clickclickonsal** [comment]
Awesome. You're all booked for April. 😄 Haha & I like the new title. I don't think it's to long. 👍

**Comment by clickclickonsal** [comment]
Thank you for giving this talk @nikzb!
