### ISSUE TITLE
Talk: Ext JS

### ISSUE THREAD

**Issue by mockaroo** [charmCityJs/talks#16]
Your name: Mark Brocato

Your idea: Ext JS is a soup-to-nuts MVCVM JavaScript framework for building HTML5 web apps for desktop, tablet, and mobile devices.  In this talk I'll give the audience a taste of what it's like to develop in Ext JS by live coding a simple admin app from scratch.

Approx length: 20 minutes

Month(s) available: Any

**Comment by jasonrhodes** [comment]
Hey there, we're taking a short break from frameworks but we're going to try to get this scheduled sometime this fall, didn't want you to think we totally forgot about it. Just had a lot of submissions come through! Thanks for submitting, you'll hear from us again at some point to work out a month that works for you and for us. :)
