### ISSUE TITLE
What’s New with React, 2018 Edition

### ISSUE THREAD

**Issue by jasonrhodes** [charmCityJs/talks#161]
**Your name:** 
Jason

**Your talk idea, described briefly:** Describing what’s new in React lately, what’s on the horizon, and why I am very glad we chose it at SparkPost

**Do you consent to having your talk recorded*, if we choose to do so?:** 
ha sure

**Short talk title (optional):** 
What’s New with React, 2018 Edition

**CCJS Slack username:**
rhodes.json

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
rhodesjason

**Length: (1-15 min please):** 
15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
componentWillUnmount () {
  console.log('Thanks for giving this talk @jasonrhodes!!');
}
