### ISSUE TITLE
Not so static sites with Gatsby and JAM stack

### ISSUE THREAD

**Issue by KDBDEV** [charmCityJs/talks#163]
**Your name:** 
Ken Brantley
**Your talk idea, described briefly:** 
How React based static site generator Gatsby along with the JAM stack architecture combines the speed of a static site while retaining many important features commonly missing from more traditional static sites.
**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes
**Short talk title (optional):** 
Not so static sites with Gatsby and JAM stack
**CCJS Slack username:**
Ken Brantey
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
KDBDEV
**Length: (1-15 min please):** 
10-15 minutes
\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @KDBDEV , thanks for submitting a talk. Are you available to give this talk at our next meet-up, on June 6th?

**Comment by esauter5** [comment]
@KDBDEV Following up on this, would you like to present at the next meetup on Wednesday, August 1?

**Comment by esauter5** [comment]
@KDBDEV Wanted to follow up. I believe at the meetup you said you'd like to give this talk next month at the September 5 meetup. Would you still like to do this?

**Comment by KDBDEV** [comment]
Yes! I'm available to give the talk at the September meetup
