### ISSUE TITLE
"So your a generalist?" ... "Well no. I prefer the term polymath."

### ISSUE THREAD

**Issue by CarringtonCreative** [charmCityJs/talks#165]
**Your name:** 
Carrington Dennis

**Your talk idea, described briefly:** 
Why all developers should become polymaths.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 

**CCJS Slack username:**
Carrington

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@carrdenn

**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Thanks for submitting @CarringtonCreative! 😄 Wanna give this talk for our next meetup, June 6th?

**Comment by esauter5** [comment]
Hey @carringtoncreative, could you give us a little more detail on your talk so we can figure out how it might fit in with our other talks?

**Comment by CarringtonCreative** [comment]
Sure, I'll be talking about learning the different facets of software
development.

**Comment by CarringtonCreative** [comment]
Does that help?

**Comment by esauter5** [comment]
@CarringtonCreative Sounds good. Would you like to talk next Wednesday??

**Comment by CarringtonCreative** [comment]
Yes, I'm excited to.

**Comment by esauter5** [comment]
Perfect! Can't wait.
