### ISSUE TITLE
full-stack architecture for good performance of a mobile app

### ISSUE THREAD

**Issue by RamiroIsBack** [charmCityJs/talks#167]
**Your name:** 
Ramiro Santamaria

**Your talk idea, described briefly:** 
A talk about why I chose an specific stack for the mobile app I'm putting together.
Comparing briefly the options and talking a bit about what it feels like working with those different tools.
React-native on the front end, Express+GraphQL on the backend and mongoDB for storing data.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
sure no problem, I'll probably record myself with the phone

**Short talk title (optional):** 
JavaScript full-stack architecture for good performance of a mobile app

**CCJS Slack username:**
Ramiro

**Length: (1-15 min please):** 
10 to 15 min

**Comment by RamiroIsBack** [comment]
I just realized I won't be able to talk about the full stack within the 15 minutes, I'll probably present an overview of the project and just getting more into detail about the front end part

**Comment by esauter5** [comment]
Hey @ramiroisback, can you give us a little more detail as to what your talk will cover?

**Comment by RamiroIsBack** [comment]
sure,
explanation about the options to build a mobile app in JavaScript (front-end) and why I chose React-native for it. _(50% of the talk)_
quick overview about how to build a back-end with an express server in NodeJs to connect with the React-Native app through GraphQL  _(50% of the talk)_

**Comment by RamiroIsBack** [comment]
hi there @esauter5 
do you need more detail about the talk? I would need to work a bit on it today and tomorrow after work if I am to present it on Wednesday.

**Comment by esauter5** [comment]
@RamiroIsBack Sorry for the delay. This sounds great. Let's plan on giving this Wednesday!

**Comment by RamiroIsBack** [comment]
no worries @esauter5 , I still have time :)
I'm excited!
Lets do the talk on wednesday!
