### ISSUE TITLE
Developing sites for User Inclusivity: a talk about web accessibility

### ISSUE THREAD

**Issue by CodeByAlex** [charmCityJs/talks#172]
**Your name: Alex Wilson

**Your talk idea, described briefly: Talk about web accessibility: a brief history, how it impacts us as developers and tools we can use to help improve site inclusivity.

**Do you consent to having your talk recorded*, if we choose to do so?:  Yes

**Short talk title (optional):**  

**CCJS Slack username: alex.wilson

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @codebyalex

**Length: (1-15 min please):**  15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by oliikit** [comment]
Hey @CodeByAlex, would you want to give the talk at our next meetup on October 3rd?

**Comment by CodeByAlex** [comment]
Hey Olivia, I would be happy to present at the next meetup on October 3rd.

**Comment by oliikit** [comment]
@CodeByAlex awesome! I got you scheduled.
