### ISSUE TITLE
enzyme vs react-testing-library

### ISSUE THREAD

**Issue by starmer** [charmCityJs/talks#174]
**Your name:** 
James Starmer

**Your talk idea, described briefly:** 
Compare and contrast react-testing-library and enzyme. Also a brief intro to testing front-end components.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes.

**Short talk title (optional):** 
react-testing-library vs enzyme

**CCJS Slack username:**
@starmer

**Twitter username (optional):** 
@starmer

**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@starmer Are you available to give this talk next Wednesday?

**Comment by starmer** [comment]
Yes!

**Comment by esauter5** [comment]
Great! You're on the schedule!

**Comment by oliikit** [comment]
Thanks for the talk, @starmer!
