### ISSUE TITLE
How my team interviews

### ISSUE THREAD

**Issue by starmer** [charmCityJs/talks#175]
**Your name:** 
James Starmer

**Your talk idea, described briefly:** 
Explain the interview process that we're currently using on my team. How we use codesandbox.io for take home exercises and for live coding.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
How my team interviews

**CCJS Slack username:**
@starmer

**Twitter username (optional):** 
@starmer

**Length: (1-15 min please):** 
15min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@starmer Any interest in giving this talk at our meetup next Monday?

**Comment by starmer** [comment]
Yeah, I'd love to!

**Comment by esauter5** [comment]
Thanks again for giving this talk!
