### ISSUE TITLE
Intro to Smalltalk

### ISSUE THREAD

**Issue by Vlad999999** [charmCityJs/talks#176]
**Your name:** 
Vlad Degen.
Talk will be by Arden Thomas, Cincom Smalltalk Product Manager

**Your talk idea, described briefly:** 
•	A brief introduction to Smalltalk and the benefits of knowing where OO languages began.
•	Includes the principles of the language, and the benefits of a modern Smalltalk implementation.
•	How knowing Smalltalk can enhance your skills for any OO language 
•	Base for JavaScript tools like AppeX (talk to follow)

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
Introduction to Smalltalk (By Arden Thomas)

**CCJS Slack username:**
contact Vlad

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @Vlad999999 Thanks for submitting! Would you like to give this talk at our next meetup?

**Comment by esauter5** [comment]
Thanks again for giving this talk!
