### ISSUE TITLE
An introduction to the AppeX Development Environment

### ISSUE THREAD

**Issue by Vlad999999** [charmCityJs/talks#177]
**Your name:** 
Vlad Degen

**Your talk idea, described briefly:** 
•	An introduction to the AppeX Development Environment:
•	A way of developing, debugging and managing JavaScript and HTML code (and external libraries)
•	Some fun with automating JavaScript applications for the purpose of functional testing.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
AppeX, a Smalltalk IDE for JavaScript Web Application development and deployment

**CCJS Slack username:**
Vlad

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @Vlad999999 Thanks for submitting! Would you like to give this talk at our next meetup?

**Comment by Vlad999999** [comment]
Hi Sal, 
    Yes I would!  Since there is one talk that  introduces Smalltalk, and a then this one that introduces AppeX, (the web application builder written in Smalltalk), naturally we'd like to give both talks back to back.

**Comment by clickclickonsal** [comment]
Is it possible if one can be given in December & the next one be given in January? I'm lining up 2 other people for our December meetup.

**Comment by Vlad999999** [comment]
Pushing out the date would be fine, with both of us together still preferred.  Would February work?

**Comment by oliikit** [comment]
@Vlad999999 we do have an opening for February. Would you like to take it? 😄

**Comment by Vlad999999** [comment]
Just one of the talks or both?

**Comment by oliikit** [comment]
@Vlad999999 hmm... we already have two talks planned already for February. We typically do 3 talks a month.

Seeing as they go back and forth, would you be able to do them side-by-side in 20 minutes?

**Comment by oliikit** [comment]
Hey @Vlad999999 - following up here, would you all be able to do the two talks in about 20ish minutes?

**Comment by Vlad999999** [comment]
Hi @oliikit,
     February is not longer an option for us.  I'm currently checking on March.

**Comment by oliikit** [comment]
@Vlad999999 let me know if you would like to do the two talks on March 6th. We could do like 20-30 minutes for both.

**Comment by Vlad999999** [comment]
You mean around 15 minutes each, and 30 minutes maximum total?

**Comment by oliikit** [comment]
Yup! Would that be more feasible?

**Comment by Vlad999999** [comment]
Sounds good!

**Comment by Vlad999999** [comment]
Confirmed for March 6 then?

**Comment by Vlad999999** [comment]
Hi Olivia, could you confirm March 6 for Arden and myself to talk?

**Comment by oliikit** [comment]
Yup @Vlad999999! Confirmed for March.

**Comment by Vlad999999** [comment]
Great, thanks!

**Comment by esauter5** [comment]
Thanks again for giving this talk!
