### ISSUE TITLE
Time Complexity

### ISSUE THREAD

**Issue by JenniferJonesCodes** [charmCityJs/talks#178]
**Your name**: Jen Jones

**Your talk idea, described briefly:** 
Introduction to Time Complexity
-Asymptotic notation
-Basic algorithms

**Do you consent to having your talk recorded**, if we choose to do so?: Yes

**Short talk title (optional):**An Introduction to Time Complexity and Why You Should Care About It

**CCJS Slack username:** Jen Jones

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** ~10 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Hey @JenniferJonesCodes ! Thanks for submitting! Sounds like a cool talk! Would you like to give this talk at our next meetup  on December 5th?

**Comment by clickclickonsal** [comment]
Awesome! I'll add you in for the December lineup! 😄

**Comment by clickclickonsal** [comment]
Thanks for giving this talk! 🙏
