### ISSUE TITLE
When things don't go quite right...

### ISSUE THREAD

**Issue by eli0shin** [charmCityJs/talks#179]
**Your name:** 
Eli Oshinsky

**Your talk idea, described briefly:** 
Logging on the server is typically done by appending lines to a file, which can be read later. But this isn't as easy on the client side. This talk is a brief look into techniques and services that allow you to better understand when and where things went wrong for your users.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
yes

**Short talk title (optional):** 
When things don't go quite right...

**CCJS Slack username:**
eli0shin

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
10mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by sparkysmitty** [comment]
Awesome!

**Comment by esauter5** [comment]
@eli0shin Are you available to give this talk on Wednesday? We had to push one of our talks back to a future month.

**Comment by eli0shin** [comment]
Sure! That works for me.

**Comment by esauter5** [comment]
@eli0shin Are we still good for next Wednesday?

**Comment by eli0shin** [comment]
@esauter5 yes I am!

**Comment by oliikit** [comment]
Thanks for the talk, @eli0shin!
