### ISSUE TITLE
Talk: Deep dive into "Thinking in React"

### ISSUE THREAD

**Issue by kylefritz** [charmCityJs/talks#18]
Your name: Kyle Fritz

Your idea: Deep dive into "Thinking in React". React challenges a lot of the current status quo in front-end web development. Some react concepts, like inline markup and specifying `onclick` handlers directly in markup and inline-ish CSS, seem like a blast from the past (the 90s are back!). But much has changed since these concepts were initially discarded and React offers a way of thinking that can fundamentally change the way you reason about Front-end & Client code. Learn about how to "Think in React" so you can decide if these approaches make sense for you.

Approx length: 20 minutes

Month(s) available: June, July

**Comment by jjulian** [comment]
:thumbsup: this is gonna be so good!

**Comment by jgaskins** [comment]
@kylefritz Are you available to present this on Sep 2?

**Comment by kylefritz** [comment]
hey @jgaskins august is a cray month for me. i would *love* to do this in october though.

**Comment by jasonrhodes** [comment]
@kylefritz hey are you free other months this fall, do you think? I'm aiming to have us take a month off of frameworks in general, and React in particular, but after a month off we'd all love to get this scheduled--we can even officially schedule you in for November now if you're available/interested?

**Comment by latazzajones** [comment]
Hi Kyle 😬! Sorry we didn't get you in for October. Would you be interested in doing this talk on November 4th? 

This talk looks amazing. Do you think it could be approachable for n00bs but also interesting for old fogies? @rayners BEWD class will probably be attending next month.

**Comment by kylefritz** [comment]
Hi Tash-

November 4th sounds great. Let's lock it in :)

**Comment by latazzajones** [comment]
Sweet!

**Comment by kylefritz** [comment]
slides from the talk: https://slides.com/kylefritz/react-thinking
