### ISSUE TITLE
Mobile Device Attribute Validation

### ISSUE THREAD

**Issue by lchasen** [charmCityJs/talks#180]
**Your name:** 
Les Chasen

**Your talk idea, described briefly:** 
Proving Something to Somebody in a Decentralized manner with Security, Privacy, and Truth with Mobile Device Attribute Validation (MDAV). MDAV is a React Native app that uses PKI in creative ways to create validated attribute certificates that can then be shared peer-to-peer with another person, no intermediaries. This talk will discuss the crypto implementation used within React Native. 

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
MDAV - Decentralized 

**CCJS Slack username:**
les.chasen

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@lchasen 

**Length: (1-15 min please):** 
15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by clickclickonsal** [comment]
Thanks for given this talk!
