### ISSUE TITLE
Mapping of the best places to run in Baltimore using R and Javascript

### ISSUE THREAD

**Issue by Jesse-Kerr** [charmCityJs/talks#181]
**Your name:** 
Jesse Kerr
**Your talk idea, described briefly:** 
Mapping of the best places to run in Baltimore using R and Javascript
**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes
**Short talk title (optional):** 
Mapping Bmore's Best Routes
**CCJS Slack username:**
Jesse Kerr
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
halfinit
**Length: (1-15 min please):** 
15
\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@Jesse-Kerr Would you like to give this talk next Wednesday, January 9?

**Comment by oliikit** [comment]
@Jesse-Kerr Would you be interested in doing this talk on February 6th?

**Comment by esauter5** [comment]
@Jesse-Kerr We have a spot open on March 6. Any interest? If I don't hear back from you, I'm going to close this for the time being until you're free.

**Comment by esauter5** [comment]
@Jesse-Kerr I'm going to close this due to inactivity. Please feel free to re-open once you are available!
