### ISSUE TITLE
Interactive Presentation Tool -- live demo of prototype

### ISSUE THREAD

**Issue by sparkysmitty** [charmCityJs/talks#183]
**Your name:** 
Dave Smith

**Your talk idea, described briefly:** 
Demo of a *prototype* of a tool to do interactive presentations.  Multiple client types (attendee, presenter, main display) with real-time feedback and control.  

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yeah

**Short talk title (optional):** 
Interactive presentation tool -- for connected community moments 

**CCJS Slack username:**
sparky

**Length: (1-15 min please):** 
15 minutes

**Availability:**
Please check off the dates in which you would be interested in presenting your talk:
- [ ] July 3rd, 2019 
- [ ] August 7th, 2019
- [X] September 4th, 2019 
- [X] October 2nd, 2019 
- [X] November 6th, 2019

**Comment by esauter5** [comment]
@sparkysmitty Are you available to give this talk next week at our Nov 6 meetup?

**Comment by sparkysmitty** [comment]
On 2019-10-28 14:40, Eric Sauter wrote:
> @sparkysmitty [1] Are you available to give this talk next week at our
> Nov 6 meetup?
> 

Eric,

Sounds good, yes I am.   Thanks,

Dave
