### ISSUE TITLE
Building and Awesome Enterprise API Server

### ISSUE THREAD

**Issue by arei** [charmCityJs/talks#184]
**Your name:** Glen R. Goodwin

**Your talk idea, described briefly:** An introduction to using thee new libraries from Awesome Engineering to rapidly build any enterprise ready API Server. Specifically will touch upon AwesomeServer, AwesomeLog, and AwesomeConfig, and how the three are used to build out an API server.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Building and Awesome Enterprise API Server

**CCJS Slack username:** arei

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @areinet 

**Length: (1-15 min please):** 20 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by oliikit** [comment]
We are a good to go for February! 🎉

**Comment by oliikit** [comment]
Awesome talk on some aweseome engineering. Thanks again @arei!
