### ISSUE TITLE
Introduction to Web Components (no frameworks)

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#185]
**Your name:** 
Shane Knudsen

**Your talk idea, described briefly:** 
An overview of custom elements, shadow DOM, and HTML templates. Some practical tips on getting started with native Web Components. A demo web application that illustrates how components are composed and communicate with each other.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
Introduction to native Web Components

**CCJS Slack username:**
ShaneKnudsen

**Twitter username (optional):** 
@CrclOfConfusion

**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by esauter5** [comment]
@circleofconfusion Are you available to give this talk next Wednesday, January 9?

**Comment by circleofconfusion** [comment]
I'm not fully ready to give this talk. I can do a weekend deathmarch if necessary, but if you've got other talks available, that's probably the safest approach. I'll be ready for February if you definitely want to hear the talk.

**Comment by esauter5** [comment]
@circleofconfusion That's fine. Let's put you on the schedule for February

**Comment by circleofconfusion** [comment]
Excellent. I'll have the talk ready for 2019-02-06.

**Comment by oliikit** [comment]
@circleofconfusion Are you still good for February?

**Comment by circleofconfusion** [comment]
Yep!

**Comment by oliikit** [comment]
@circleofconfusion great talk last night! Thanks again!
