### ISSUE TITLE
Keep in Touch with EmailJS

### ISSUE THREAD

**Issue by CodeByAlex** [charmCityJs/talks#186]
**Your name:** 
Alex Wilson

**Your talk idea, described briefly:** 
Why and how you can send emails from client-side Javascript by way of email templating and REST calls made to EmailJS

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
Keep in Touch with EmailJS

**CCJS Slack username:**
CodeByAlex

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@CodeByAlex

**Length: (1-15 min please):** 
10-15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Comment by oliikit** [comment]
@CodeByAlex Are you available to give this talk this Wednesday, January 9th?

**Comment by CodeByAlex** [comment]
Hey Olivia, I can give this talk on Wednesday

**Comment by oliikit** [comment]
Awesome! We got you scheduled.

**Comment by oliikit** [comment]
Thanks for the talk @CodeByAlex!
