### ISSUE TITLE
Using Web Sockets, WebGL and WebRTC to make projections for Theatre

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#188]
**Your name:** Chris Uehlinger

**Your talk idea, described briefly:** The past few months I’ve done projection work for Haute Patooties’ production of *The Rocky Horror Show* and Rapid Lemon’s production of *Thank You, Dad*. I built a lot of my effects (including live video feeds of the stage, videos synced to live music and projections targeting 3 projectors at once) using JavaScript. I’d like to dissect a few of my effects and talk about how the tech we use for work can be repurposed for art.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes please!

**Short talk title (optional):** Strike the Closures! JavaScript in Theatre Tech

**CCJS Slack username:** uehreka

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** uehreka

**Length: (1-15 min please):** 15 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_
- [x ] March 6th, 2019
- [ ] April 3rd, 2019
- [ ] May 1st, 2019
- [ ] June 5th, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019
I’m free for any of these and also February.

**Comment by oliikit** [comment]
Little birdy told me you would like to give this talk in February, is that correct @chrisuehlinger?

**Comment by chrisuehlinger** [comment]
That’s correct!

**Comment by oliikit** [comment]
@chrisuehlinger awesome talk last night! It inspired so many people to build things. 😍
