### ISSUE TITLE
Deciding between React.js & Ember.js

### ISSUE THREAD

**Issue by scottmessinger** [charmCityJs/talks#19]
Your name: Scott Messinger

Your idea: With the release of Ember 2.0 in June, Ember & React are looking increasingly similar. Both are based on components, have routers*, are tremendously performant, and have been adopted by large companies (React Facebook, Yahoo, Ember: Square, Yahoo, Intercom). How is a developer to choose? I've been using Ember for a few years (since 0.9.6) and React for the last few months and have shipped apps into production with both. I think they're both great. In this talk, I'll lay out some of the advantages (and disadvantages) of each project and present some ideas on how to decide which to use in your organization.

Approx length: 20 minutes

Month(s) available: June or July

*React actually has several third party routers. The most popular, react-router, is based off of Ember's.

**Comment by latazzajones** [comment]
Hi Scott, Would you be willing to do this talk for the June 3rd meetup?

**Comment by latazzajones** [comment]
@scottmessinger ^^  I hope all is well! If you're free on June 3rd, we'd love to have you give this talk.

**Comment by scottmessinger** [comment]
@latazzajones June 3rd works great! See you then!
