### ISSUE TITLE
Debounce for Beginners

### ISSUE THREAD

**Issue by sparkysmitty** [charmCityJs/talks#190]
**Your name:** 
Dave Smith

**Your talk idea, described briefly:** 
Intro to the concept of debouncing.  By a beginner, for beginners.  10 minutes.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Let me know if I need to comb my hair first, please.

**Short talk title (optional):** 
Debounce for Beginners

**CCJS Slack username:**
sparky

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
10 min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_
- [X] March 6th, 2019
- [X] April 3rd, 2019
- [ ] May 1st, 2019
- [ ] June 5th, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019

**Comment by esauter5** [comment]
@sparkysmitty Any interest in giving this talk next Wednesday?

**Comment by sparkysmitty** [comment]
On 2019-03-28 17:12, Eric Sauter wrote:
> @sparkysmitty [1] Any interest in giving this talk next Wednesday?

Just saw this.   Absolutely, will do -- sounds great.

**Comment by esauter5** [comment]
Great. We will see you on Wednesday!

**Comment by oliikit** [comment]
Thanks for the talk!
