### ISSUE TITLE
Building Web Components with ZephJS

### ISSUE THREAD

**Issue by arei** [charmCityJs/talks#191]
**Your name:** Glen R. Goodwin

**Your talk idea, described briefly:** An introduction to a new library ultra-lightweight library for building Web Components that are fast, easy to understand and read, and 100% standards compliant. This talk will serve as an introduction to the library and we will live code an example Web Component together. 

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Building Web Components with ZephJS

**CCJS Slack username:** Arei

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** areinet 

**Length: (1-15 min please):** 15 mins

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:** Would love to give this talk in February 2019!
_Please check off the dates in which you would be interested in presenting your talk:_
- [x] March 6th, 2019
- [x] April 3rd, 2019
- [x] May 1st, 2019
- [x] June 5th, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019

**Comment by arei** [comment]
Revised description: An introduction to the ZephJS library. ZephJS is an extremely easy to use, simple to understand, ultra-light framework for defining and using Web Components. ZephJS is perfect for people writing component libraries, teams building applications or sites that just require a few custom components, or projects building whole applications that do not want the gigantic weight of a modern JavaScript browser framework. ZephJS simplifies the process of defining custom Web Components into a highly readable declarative structure that uses standard JavaScript, standard HTML markup, and standard CSS styling. And ZephJS weighs in at less than 20k minified!

More information at https://gist.github.com/arei/8083a6270e704b830c68a2020f3e5e3e

**Comment by oliikit** [comment]
@arei Looks great! Would you be up for talking for May 1st?

**Comment by arei** [comment]
Yea, I can probably whip something together for Wednesday. I would like the last slot if possible.

**Comment by oliikit** [comment]
@arei we can do that!

**Comment by clickclickonsal** [comment]
Thank you for giving this talk! 🙏
