### ISSUE TITLE
Learn Coding With Spaced Repetition Systems

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#192]
**Your name:** 
Eric Masi

**Your talk idea, described briefly:** 
How to use an SRS to help learn coding (and many other subjects). I'll show spaced repetition systems in action and discuss some of the ways I've used it to bolster my memory. Useful for beginners, experts, and everyone in between.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes.

**Short talk title (optional):** 
Learn Coding With Spaced Repetition Systems

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_
- [x] March 6th, 2019
- [x] April 3rd, 2019
- [x] May 1st, 2019
- [ ] June 5th, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019

**Comment by esauter5** [comment]
@git-masi Any interest in giving this talk next Wednesday? I think it would be a great change of pace talk that's still applicable to JS!

**Comment by git-masi** [comment]
@esauter5 Yes, I'd be happy to give the talk next Wednesday!

**Comment by esauter5** [comment]
@git-masi Perfect! See you on Wednesday!

**Comment by oliikit** [comment]
Thanks for the talk!
