### ISSUE TITLE
Playing with Proxy

### ISSUE THREAD

**Issue by cixel** [charmCityJs/talks#193]
**Your name:** 
Ehden Sinai

**Your talk idea, described briefly:** 
The [Proxy](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object, added in ES6, adds new ways to intercept and change the way an object behaves. There are a number of really interesting and useful applications for this, but I want to focus on the useless, zany, and mind-bending possibilities Proxy brings with it. Those are more fun.

This talk will introduce and cover basic usage of Proxy and [Reflect](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect) (Proxy's sister object). Then, it will explore some of its useful applications before delving into some odd ways to use it that are probably useless, but definitely kinda fun to play with.

Proxy is relatively new, and its place in the ecosystem is still being slowly discovered, but it has the potential to completely reshape JavaScript security and metaprogramming. Let's explore!

**Do you consent to having your talk recorded, if we choose to do so?:** 
Yes

**Short talk title (optional):** 

**CCJS Slack username:**
ehden

**Length: (1-15 min please):** 
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_
- [ ] March 6th, 2019
- [x] April 3rd, 2019
- [x] May 1st, 2019
- [ ] June 5th, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019

(generally available any month after March, but I'd prefer sooner than June)

**Comment by esauter5** [comment]
@cixel Are you available for April?

**Comment by cixel** [comment]
Yep!

**Comment by esauter5** [comment]
Still good for next Wednesday @cixel?

**Comment by cixel** [comment]
Yeah

**Comment by cixel** [comment]
Presentation materials will be uploaded [here](https://github.com/cixel/charmcityjs-apr2019) some time before Wednesday.

**Comment by oliikit** [comment]
Thanks for the talk!
