### ISSUE TITLE
Introduction to CSS Grid layout

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#195]
**Your name:** 

Shane Knudsen (pronounced: kuh-NOOT-sen)

**Your talk idea, described briefly:** 

Introduction to CSS Grid layout.
- What is it for?
- Basic usage
- IE (!) support
- Examples of advanced usage

**Do you consent to having your talk recorded*, if we choose to do so?:** 

Yes

**Short talk title (optional):** 

**CCJS Slack username:**

ShaneKnudsen

**Twitter username (optional):** 

@CrclOfConfusion

**Length: (1-15 min please):** 

15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

I'm assuming this is for May 1, but other dates would work, too.

- [x ] June 5th, 2019
- [ ] July 3rd, 2019
- [x ] August 7th, 2019
- [x ] September 4th, 2019
- [x ] October 2nd, 2019
- [ ] November 6th, 2019

**Comment by clickclickonsal** [comment]
Thank you for giving this talk! 🙏
