### ISSUE TITLE
Learn, practice, and refine coding skills with code kata

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#196]
**Your name:** 
Eric Masi

**Your talk idea, described briefly:** 
A talk about "code kata", and specifically sites like Codewars and how they can be used to learn, practice, and refine coding skills in many languages (including Javascript of course).

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes

**Short talk title (optional):** 
Learn, practice, and refine coding skills with code kata

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 
10 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] May 1st, 2019
- [x] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019
- [ ] October 2nd, 2019
- [ ] November 6th, 2019

**Comment by clickclickonsal** [comment]
Thank you for giving this talk! 🙏
