### ISSUE TITLE
Taming Serverless

### ISSUE THREAD

**Issue by eli0shin** [charmCityJs/talks#199]
**Your name:** 
Eli Oshinsky

**Your talk idea, described briefly:** 
I love serverless. It really is the old-school mainframe time-sharing idea done better. But as with any platform, it exposes a set of imperative programmatic APIs. I believe that in event-driven computing (like serverless) a more declarative style allows for higher cohesion. Additionally, I have seen many projects end up rather fragmented due to the way vendors require us to configure the events that drive our systems.

I would like to give a quick overview of serverless technologies and how they change the way we think about writing software for the web. Afterwards, I will present a tool that I have been working on for several months that will help frame serverless in a more cohesive way and allow for cleaner growth of a serverless codebase.

**Do you consent to having your talk recorded*, if we choose to do so?:** 
yes. (I will likely record it myself as well)

**Short talk title (optional):** 
Taming Serverless

**CCJS Slack username:**
eli0shin

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
eli0shin

**Length: (1-15 min please):** 
15 mins (If possible I would like to run a little longer. I understand the need for a time limit, but I promise this will stay interesting)
\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] July 3rd, 2019
- [x] August 7th, 2019
- [x] September 4th, 2019
- [ ] October 2nd, 2019
- [ ] November 6th, 2019

**Comment by esauter5** [comment]
Thanks again for giving this talk @eli0shin!
