### ISSUE TITLE
Immutable.js

### ISSUE THREAD

**Issue by gtrak** [charmCityJs/talks#2]
Your name: Gary Trakhman

Your idea: Immutable.js, an immutable collection library for javascript.  I can show off what it can do and describe the benefits, plus show how to use it with React.js.
Approx length: 10-15 min (remember, talks should be 10-20 min long, just estimate for us here)

Month(s) available: All the months!!!!

**Comment by latazzajones** [comment]
Hey Gary - how about May 6th? If you can make it, which of these 3 talks would you like to give?

**Comment by gtrak** [comment]
I'll do ramda.js first.  May 6 is great!
