### ISSUE TITLE
meteor.js, stop wasting time

### ISSUE THREAD

**Issue by bgrayburn** [charmCityJs/talks#20]
This is how web coding should be. Reactive, isomorphic, reusable.

I'll show you how to use all your favorite npm modules while making websites that are blazingly fast and informative. Let's live code a site in 20min.

**Comment by bgrayburn** [comment]
Oh one more adjective: data-driven

**Comment by jasonrhodes** [comment]
Closing this one in favor of #40, so we have one proposal per person in queue, to help us narrow down decisions each month.
