### ISSUE TITLE
Advanced Website Theme Building with concrete5 CMS 

### ISSUE THREAD

**Issue by stewblack23** [charmCityJs/talks#202]
Wayne Stewart

Advanced Website Theme Building with concrete5 CMS 

Yes. I would like to have this talk recorded is possible 

CCJS Slack User Name: stewblack23

Twiter Name: stewblack23 & agency_stewart

Length: 15 Mins:

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [x] September 4th, 2019
- [X] October 2nd, 2019
- [ ] November 6th, 2019

**Comment by stewblack23** [comment]
Great. October it is. I will put it on my calendar now.

**Comment by stewblack23** [comment]
Hey Eric. Just wanted to make sure I'm still on for the talk next week. Thanks.

**Comment by esauter5** [comment]
@stewblack23 Thanks for giving your talk last night! Feel free to submit in the future if you have new ideas!
