### ISSUE TITLE
Taming -ms-grid the easy way

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#203]
**Your name:** 

Shane Knudsen

**Your talk idea, described briefly:** 

The CSS Grid API has made web page layout much easier and expressive, but the Grid implementation in Internet Explorer is rather lacking. Fortunately, the kind folks behind AutoPrefixer have come up with some new tricks to help alleviate the pain.

Topics covered:

 - Internet Explorer 10 & 11 grid limitations 
 - AutoPrefixer
 - Autoplacement of grid cells

**Do you consent to having your talk recorded*, if we choose to do so?:** 

Yes

**Short talk title (optional):** 

Taming -ms-grid the easy way

**CCJS Slack username:**

ShaneKnudsen

**Twitter username (optional):** 

@CrclOfConfusion

**Length: (1-15 min please):** 

15 minutes

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [x] September 4th, 2019
- [x] October 2nd, 2019
- [x] November 6th, 2019

**Comment by esauter5** [comment]
Thanks again for giving this talk @circleofconfusion!
