### ISSUE TITLE
Skip Class and Just Object: Composition and Behavior Delegation over Inheritance

### ISSUE THREAD

**Issue by cukejianya** [charmCityJs/talks#204]
**Your name:** 
Chinedum Ukejianya

**Your talk idea, described briefly:**
We talk about functional programing vs OOP, but we never talk about if we can do OOP differently in JS. Or even if classes is a thing we should do in JS. In this talk, we will be exploring behavior delegation and composition in replace of classic OOP design patterns. 

**Do you consent to having your talk recorded*, if we choose to do so?:** 
Yes. Can I record for my personal use as well?

**Short talk title (optional):** 
Composition Over Inheritance

**CCJS Slack username:**
cukejianya

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):**
@cukejianya_

**Length: (1-15 min please):**
10min

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019
- [x] October 2nd, 2019
- [x] November 6th, 2019

**Comment by esauter5** [comment]
Thanks again @cukejianya!
