### ISSUE TITLE
Neon - Native node modules in Rust

### ISSUE THREAD

**Issue by kjvalencik** [charmCityJs/talks#205]
**Your name:**
K.J. Valencik

**Your talk idea, described briefly:**
How to write safe, reliable, and fast native modules for node with Rust and the Neon library.

https://github.com/neon-bindings/neon
https://neon-bindings.com/

**Do you consent to having your talk recorded, if we choose to do so?:**
Preferably, no, but I could possibly be convinced.

**Short talk title (optional):** 
Node + Rust = Neon

**CCJS Slack username:**
K.J.

**Twitter username (optional):** 
N/A

**Length: (1-15 min please):** 
10min

**Availability:**

- [ ] November 6th, 2019
- [x] December 4th, 2019
- (No January Meetup in 2020)
- [x] February 5th, 2020
- [x] March 4th, 2020
- [x] April 1st, 2020

**Comment by arei** [comment]
@kjvalencik Could you indicate (by checking the boxes) when you could give this talk?
