### ISSUE TITLE
An Inside Look at an Online Bootcamp 

### ISSUE THREAD

**Issue by ericfeldman1** [charmCityJs/talks#207]
Your name: Eric Feldman

Your talk idea, described briefly: Discussing my experience so far with Bloc, the online bootcamp that I've been in for the past 4 months (about halfway through).

Do you consent to having your talk recorded*, if we choose to do so?: Yes

Short talk title (optional): Bloc - An Inside Look at an Online Bootcamp (Or feel free to just call it "An Inside Look at an Online Bootcamp" if you think it's too long...or really you can call it whatever you'd like)

CCJS Slack username: ericfeldman

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): n/a

Length: (1-15 min please): 10ish minutes  

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [x ] September 4th, 2019
- [ ] October 2nd, 2019
- [ ] November 6th, 2019

**Comment by esauter5** [comment]
Thanks for giving this talk last night @ericfeldman1! I'm bummed I had to miss it.
