### ISSUE TITLE
Life After Bootcamp

### ISSUE THREAD

**Issue by lulabromark** [charmCityJs/talks#208]
**Your name:** 
Mark Lawrence
**Your talk idea, described briefly:** 
Follow-up talk about preparing for job searches, networking and preparing for job interviews
**Do you consent to having your talk recorded*, if we choose to do so?:** 
yes
**Short talk title (optional):** 
Life After Bootcamp
**CCJS Slack username:**
Mark Lawrence
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
lulabromark
**Length: (1-15 min please):** 
5 min
\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019
- [x] October 2nd, 2019
- [x] November 6th, 2019

**Comment by esauter5** [comment]
Hey @lulabromark, want to give this talk on Oct 2?

**Comment by lulabromark** [comment]
Sure, that will work!

**Comment by esauter5** [comment]
Thanks for giving this talk last night @lulabromark. Nice job!
