### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by tony-decarlo-t1cg** [charmCityJs/talks#209]
**Your name:** Tony DeCarlo & James Nutter

**Your talk idea, described briefly:** We will talk about what is a progressive web app, how to build one, how to get it on the app store, and a demo of our app.

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** Progressive Web Apps (PWAs)

**CCJS Slack username:** Tony DeCarlo

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @tonydecarlo11 @theflockaveli

**Length: (1-15 min please):** 15

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] June 5th, 2019
- [ ] July 3rd, 2019
- [ ] August 7th, 2019
- [ ] September 4th, 2019
- [ ] October 2nd, 2019
- [x] November 6th, 2019

**Comment by esauter5** [comment]
@tony-decarlo-t1cg Are you available to give this talk on Nov 6?

**Comment by tony-decarlo-t1cg** [comment]
@esauter5 Yes
