### ISSUE TITLE
request: Exquisite Hues, a poetic experiment

### ISSUE THREAD

**Issue by janecakemaster** [charmCityJs/talks#21]
**Your name:** jane kim

**Your idea:** in which i talk about using technology to make art-- specifically, an exquisite corpse poetry app i made for the internet that shows the user the last line of a poem and prompts the user to write the next line. the background of the page is a certain color based on the "progress" of the poem

**Approx length:** 10 min probz..?

**Month(s) available:** !may, but most likely all the rest

**Comment by jjulian** [comment]
I love this! Using code to make art.

**Comment by jasonrhodes** [comment]
YES JANE!

**Comment by apechimp** [comment]
@janecakemaster, do you want to give this talk at the August 5th meetup?

**Comment by janecakemaster** [comment]
​all right, let's do this!

**Comment by apechimp** [comment]
Awesome! Thanks! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).
