### ISSUE TITLE
Designing complex Schemas for MongoDB with JSONSchema

### ISSUE THREAD

**Issue by naterkane** [charmCityJs/talks#210]
**Your name:**  Nater Kane

**Your talk idea, described briefly:** 

MongoDB is schemaless, so we use MongooseJS to provide an common interface to Mongo and it provides support for working with schemas. Mongoose isn't the best at supporting logical validation of those schemas or parts of the schemas. Just it just supports basic types, and lacks optional validators like `if x is 1 then y is 2`.. however it does support the writing of custom functions as validators. With that, we can extend the schema validation to then take an object and validate it against JSONSchema.

Similarly to how we would validate request objects that are sent to an API against JSONSchema.. this is a handy and declarative way to add guardrails for not only API consumers, but developers working on the API itself

**Do you consent to having your talk recorded*, if we choose to do so?:** sure, I'll probably bring a GoPro to record it myself

**Short talk title (optional):** 

**CCJS Slack username:** naterkane

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Length: (1-15 min please):** 

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] December 4th, 2019
- (No January Meetup in 2020)
- [x] February 5th, 2020
- [x] March 4th, 2020
- [x] April 1st, 2020
- [x] May 6th, 2020
- [x] June 3rd, 2020
- [x] July 1st, 2020
- [x] August 5th, 2020
- [x] September 2nd, 2020
- [x] October 7th, 2020
- [x] November 4th, 2020
- [x] December 2nd, 2020

**Comment by arei** [comment]
@naterkane Could you indicate when you can give this?

**Comment by naterkane** [comment]
Any time. Would you like me to put the talk together for November?

**Comment by arei** [comment]
@naterkane Can you update availability please? TY!

**Comment by naterkane** [comment]
I did after the first time you asked

**Comment by arei** [comment]
Sorry, It only went through November... I added through next year for you to indicate.

**Comment by naterkane** [comment]
Any month is fine...
