### ISSUE TITLE
A Component Story

### ISSUE THREAD

**Issue by PilotConway** [charmCityJs/talks#212]
**Your name:** John Conway

**Your talk idea, described briefly:** How I have come to incorporate Storybook into my workflow to develop view components in isolation and how this approach creates cleaner interfaces, more shareable components, and documentation. 

**Do you consent to having your talk recorded*, if we choose to do so?:** Yes

**Short talk title (optional):** A Component Story

**CCJS Slack username:** PilotConway

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @PilotConway

**Length: (1-15 min please):** 15

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] November 6th, 2019
- [X] December 4th, 2019

**Comment by arei** [comment]
John, thanks for giving your talk!
