### ISSUE TITLE
Beginner Sourdough for Software Engineers

### ISSUE THREAD

**Issue by lamroger** [charmCityJs/talks#213]
**Your name:** Roger Lam

**Your talk idea, described briefly:** Baking your own fresh sourdough loaf! Here's how to get started in a pragmatic sense that worked for me and hopefully works for you too.

**Do you consent to having your talk recorded, if we choose to do so?:** Yep

**Short talk title (optional):** Beginner Sourdough for Software Engineers

**CCJS Slack username:** Roger Lam

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @lamroger

**Length: (1-15 min please):** 10

\*Note: recordings, if made, will only ever be made freely available through CharmCityJs and never sold or otherwise distributed. Ping us via email (team@charmcityjs.com) or twitter (@charmcityjs) if you have questions.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] November 6th, 2019
- [x] December 4th, 2019
- [ ] January 1st, 2020
- [ ] February 5th, 2020
- [ ] March 4th, 2020
- [ ] April 1st, 2020
- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020

**Comment by lamroger** [comment]
Down to bring some starter and possibly a loaf

**Comment by esauter5** [comment]
@lamroger Are you able to give this talk on Nov 6?

**Comment by lamroger** [comment]
@esauter5 let do it!
