### ISSUE TITLE
A Taste of PureScript

### ISSUE THREAD

**Issue by sedram** [charmCityJs/talks#214]
**Talk Title: ** 
"A Taste of PureScript" (title subject to change)

**Talk Idea, described briefly: ** 
PureScript is a statically-typed functional language similar to Haskell which compiles to JavaScript. Rather than a real thorough introduction to using PureScript (which would be less interesting/couldn't get far in 15 min), I would dive into some cherrypicked examples of things I appreciate about it. I don't have the details fleshed out yet.

**Your name: ** 
Mark Spindler

**CCJS Slack username: **
Display name "Mark S."

**Estimated Talk Length: (1-15 min please): ** 
15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] November 6th, 2019
- [x] December 4th, 2019
- (No January Meetup in 2020)
- [x] February 5th, 2020
- [x] March 4th, 2020
- [x] April 1st, 2020
- [ ] May 6th, 2020
...

**Comment by asasmith** [comment]
@sedram can you update your availability to give this talk? Thanks!

**Comment by esauter5** [comment]
@sedram Do you still have any interest in giving this talk? We'd love to have you at our Dec 2 meetup. Otherwise, I'll close this issue.

**Comment by sedram** [comment]
Unfortunately, I am no longer in a position to give this talk any time soon.
