### ISSUE TITLE
Placeholder: Something to do with Modules

### ISSUE THREAD

**Issue by cukejianya** [charmCityJs/talks#215]
**Talk Title:**
Something to do with Modules (Might Change)

**Talk Idea, described briefly:**  
We all use them, but how many of us really know about them. I kind of want to talk about modules and the different implementations (AMD, Harmony, Commonjs). Or I might walk through implementing a simple module system of my own. Or I might talk about creating a module from concept to posting it on NPM. Maybe this can be a 3 part series. Not sure. 

**Your name:**  
Chinedum Ukejianya

**CCJS Slack username:** 
@cukejianya

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):**  
@cukejianya_

**Estimated Talk Length: (1-15 min please):**  
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] November 6th, 2019
- [x] December 4th, 2019
- (No January Meetup in 2020)
- [x] February 5th, 2020
- [x] March 4th, 2020
- [ ] April 1st, 2020
- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by oliikit** [comment]
Thanks for the talk @cukejianya!
