### ISSUE TITLE
Beyond var self = this; Leveraging the 'this' keyword

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#217]
**Talk Title: ** 

Beyond var self = this; Leveraging the 'this' keyword

**Talk Idea, described briefly: ** 

The JavaScript 'this' keyword can be a source of confusion. I'd like to take some time to demystify it, and explain how it can be used to our advantage.

Note: this may be related to #27, but I wasn't around at the time, and can't be sure. If it's too much of a repeat, I won't take it personally if you'd rather not have the talk.

**Your name: ** 

Shane Knudsen

**CCJS Slack username: **

@ShaneKnudsen 

**Twitter username (optional): ** 

@CrclOfConfusion

**Estimated Talk Length: (1-15 min please): ** 

15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] February 5th, 2020
- [x] March 4th, 2020
- [x] April 1st, 2020
- [x] May 6th, 2020
- [x] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [x] November 4th, 2020
- [x] December 2nd, 2020

**Comment by asasmith** [comment]
@circleofconfusion can you update your availability to give this talk? Thanks!

**Comment by circleofconfusion** [comment]
Give me a heads up when you think you'd want to hear this talk. It'll take some work to put together so that it's a tight talk.

**Comment by esauter5** [comment]
@circleofconfusion How about Nov 4?

**Comment by circleofconfusion** [comment]
Sure, I can have it ready by then. Thanks for the heads up.

Shane

**Comment by esauter5** [comment]
Sounds good! We will see you on 11/4.

**Comment by arei** [comment]
Shane, thank you for your talk.
