### ISSUE TITLE
Tracking Diamond Prices with Node, Lambda, and AWS Step Functions

### ISSUE THREAD

**Issue by lamroger** [charmCityJs/talks#219]
**Talk Title: ** Tracking Diamond Prices with Node, Lambda, and AWS Step Functions

**Talk Idea, described briefly: ** 
💍s are expensive. Why isn't there a camelcamelcamel for diamonds? I set out to make one. 

Conceptually, it's another price tracker but I leverage Lambda to perform scrapes in an entirely serverless fashion. 

**Your name: ** Roger Lam

**CCJS Slack username: ** Roger Lam

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): ** @lamroger

**Estimated Talk Length: (1-15 min please): ** 15

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] November 6th, 2019
- [ ] December 4th, 2019
- (No January Meetup in 2020)
- [ ] February 5th, 2020
- [ ] March 4th, 2020
- [] April 1st, 2020
- [] May 6th, 2020
- [] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [x] September 2nd, 2020
- [x] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by oliikit** [comment]
Hey @lamroger - would you be up to present remotely for either May 6th or June 3rd?

**Comment by lamroger** [comment]
hi @oliikit I didnt end up finishing this project so i'ma close this out. thanks for offering though!

**Comment by lamroger** [comment]
Reopening because I got it to work!

**Comment by asasmith** [comment]
@lamroger are you available to give this talk this week (9/2)?

**Comment by asasmith** [comment]
@lamroger thanks for a great talk!
