### ISSUE TITLE
iOS development with React Native

### ISSUE THREAD

**Issue by esauter5** [charmCityJs/talks#22]
Your name: Eric Sauter

Your idea: An overview of Facebook's recently open sourced React Native. I'll touch briefly on what makes React intriguing, then more specifically discuss React Native and show how it can help to break down the barriers of entering into iOS development.

Approx length: 20 minutes

Month(s) available: Any

**Comment by jgaskins** [comment]
@esauter5 Are you available to present this one at the meetup on Sep 2?

**Comment by esauter5** [comment]
That works for me!
