### ISSUE TITLE
XState: Javascript for Finite State Machines

### ISSUE THREAD

**Issue by nikzb** [charmCityJs/talks#220]
**Talk Title: ** XState: Javascript for Finite State Machines 

(Read the title like you would read "Fosters: Australian for Beer")

**Talk Idea, described briefly: ** While finite state machines is an old concept in computer science, it has become a very popular topic in the JS world recently. If you've ever thought about an app your building in terms of the various states it can be and how it gets from one to another, then you may have already used this concept without even knowing it!

XState is a library that provides a way to declare your application's behavior as a finite state machine (or statechart for expanded capabilities like compound and parallel states) which helps you avoid things like having a set of variable values in your state that don't actually make any sense in a particular combination. You define exactly what the valid states are and all the possible ways that one state can transition to another, so invalid states simply cannot occur. You can also add "extended state" to keep track of additional data and you can specify side effects that should happen when a state is entered, exited, or when a transition between two specific states happens.

There is also really cool visualizer that can show you your state machine and you interactively cause and see the state transitions happening. This lets you verify that your machine works as you expect. XState can be used for simple apps or can scale to represent very complex systems. It interfaces really nicely with existing libraries, for example, there is a React hook called "useMachine". 

I took an old project I had built years ago where I had drawn out a finite state machine in the planning stages, and I rewrote parts of it to use XState. The exercise convinced me that this a library worth considering whenever I build a new app. 

**Your name: ** Nik Baltatzis

**CCJS Slack username: ** nikzb

**Twitter username (optional): ** nikzb7e

**Estimated Talk Length: (1-15 min please): ** 10-15?

Availability: Please check off the dates in which you would be interested in presenting your talk:

Oct, Nov, Dec all should be ok.

**Comment by oliikit** [comment]
Hey @nikzb - would you be up for giving this talk remotely May or June? We can look at scheduling later once the current situation has past if you prefer in person.

**Comment by nikzb** [comment]
Hey @oliikit, so I've been thinking about it and it doesn't feel like doing a remote talk for this topic would be all that worthwhile since there's probably already a bunch of recorded talks on it that people could watch. That's probably true of lots of topics but there are potentially talk ideas that have some more personal or local connection that might be more engaging for a remote meetup. Honestly just thinking out loud here, but I'm wondering if it's worth exploring other ideas for how to get people engaged with CharmCityJS during the quarantining, for example instead of having talks, doing something like having one person interview another about their "JS story" or something.

Anyway, I think I would prefer to save the XState talk for an in person meetup but would still consider doing it if an in person meetup is not going to be possible for a super long time. I have been very busy lately at work, so I would probably want to put it off until at least June.

**Comment by arei** [comment]
While we understand your desires here, I do want tot say, don’t underestimate your usefulness to other on this topic...

**Comment by nbaltatzis** [comment]
Seeing as how there probably won't be any in person meetups for a long time, I am fine with presenting this remotely instead. I'd like to revise the talk title to:

"I'm Xstatic about XState (Finite State Machines in JavaScript)"

**Comment by asasmith** [comment]
@nbaltatzis can you update your availability for this talk? Thanks!

**Comment by nikzb** [comment]
Just noticed that I commented with my work GitHub account. Whoops, anyway, yeah I should be available pretty much any of the next few months as far as I know as of now.

**Comment by arei** [comment]
Thanks for this awesome talk Nik!
