### ISSUE TITLE
Driving a Twitter Bot with Open Data

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#223]
**Talk Title: ** 

Driving a Twitter Bot with Open Data

**Talk Idea, described briefly: ** 

The Twitter bot in question is @BadDrivingBmore. It listens for mentions that contain one or more automobile license plates, and responds with information about the vehicle's parking and automated camera violations stored in Open Baltimore's database.

The talk will focus on the overall architecture of the bot, and discuss various gotchas and missing pieces of Twitter's documentation.

**Your name: ** 

Shane Knudsen

**CCJS Slack username: **

@ShaneKnudsen 

**Twitter username (optional): ** 

@CrclOfConfusion
@BadDrivingBmore

**Estimated Talk Length: (1-15 min please): ** 

15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] March 4th, 2020
- [x] April 1st, 2020
- [x] May 6th, 2020
- [x] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by oliikit** [comment]
Thanks for the talk @circleofconfusion!
