### ISSUE TITLE
Suddenly Remote

### ISSUE THREAD

**Issue by olearycrew** [charmCityJs/talks#224]
**Talk Title: **

Suddenly Remote

**Talk Idea, described briefly: **

For all of those grappling with the new reality of remote working, the challenges and opportunities are plentiful.  Even for those of us who were working remotely before the current crisis, we have had to adjust our lives in ways we never anticipated.  How do you make your life and work well..work...in such uncertain times?  

In this talk, we'll discuss the tried and true strategies we've discovered at GitLab while building the largest all-remote company in the world.  It is important to separate work from life, find a structure that works for you and your loved ones, and allow yourself to try new things quickly. Also, social distance doesn't have to mean losing the social aspect of life.   

By being intentional about the way you address being remote - either suddenly or for your career - you can avoid burnout and loneliness while finding new ways to leverage your time and be more effective than when you used to go to the office every day. 

**Your name: **

Brendan O'Leary

**CCJS Slack username: **

@Brendan

**Twitter username (optional): **

@olearycrew

**Estimated Talk Length: (1-15 min please): **

15 minutes

Availability:
Please check off the dates in which you would be interested in presenting your talk:

- [x] May 6th, 2020
- [x] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by oliikit** [comment]
@olearycrew - this is a very timely talk! Would you be available to talk in May? We're trying to gather our first round of remote talks, and this would be a great opener.

**Comment by olearycrew** [comment]
@oliikit I think I can now that I look on my schedule again.  I'm actually on a Twich stream that ends AT 7 but I think I would be able to make that work

**Comment by oliikit** [comment]
@olearycrew - sounds good. We can also start at 7:30 PM to help accommodate. I was waiting if we could get some more talks in the queue, but looks like you'd be the only talk if you're able to do it. We're planning some other activities to help for the time.

**Comment by olearycrew** [comment]
@oliikit let's go with that - if we can plan on 7:30 that would be perfect!

**Comment by oliikit** [comment]
Awesome! We got you scheduled!

**Comment by arei** [comment]
Brenda did, thanks for giving this talk.it was awesome!
