### ISSUE TITLE
Terr-a-form out my experience to help reduce your deployment anxieties

### ISSUE THREAD

**Issue by clickclickonsal** [charmCityJs/talks#225]
**Talk Title:** Terr-a-form out my experience to help reduce your deployment anxieties

**Talk Idea, described briefly:** 
A talk about my thoughts & learnings from using terraform.(I can write a better description later)

**Your name:** Sal

**CCJS Slack username:** @clickclickonsal 

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @clickclickonsal 

**Estimated Talk Length: (1-15 min please):** 10-15 mins

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] May 6th, 2020
- [x] June 3rd, 2020
- [x] July 1st, 2020
- [x] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by esauter5** [comment]
Thanks again for giving this talk @clickclickonsal !
