### ISSUE TITLE
C2-36 : Being intentional about growth. 

### ISSUE THREAD

**Issue by Ekwuno** [charmCityJs/talks#227]
**Talk Title:** C2-36 : Being intentional about growth.   

**Talk Idea, described briefly:** This talk is about my personal experience of growing as a developer and ultimately my opinion on intentional growth from writing first lines of HTML 5 with out knowing I was learning to make stuff accessible and then becoming a Software Engineer at Gatsby . 

**Your name:** Obinna Ekwuno 

**CCJS Slack username:** Obinna Ekwuno 

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** obinnaspeaks 

**Estimated Talk Length: (1-15 min please):** 15mins 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [  ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [x] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by asasmith** [comment]
@Ekwuno are you still available to give this talk? If so, can you check with month/months would be good for you? Thanks!

**Comment by Ekwuno** [comment]
@asasmith I just picked a date, thanks for reaching out

**Comment by esauter5** [comment]
@Ekwuno Still good for November? If so, we'll get you on the list.

**Comment by Ekwuno** [comment]
@esauter5 Yea for sure!

**Comment by esauter5** [comment]
Sounds good! We will see you on 11/4.

**Comment by Ekwuno** [comment]
Hey, I'm currently in the UAE and I think I messed up the time zones as I was in transit from Lagos Nigeria. 

I am so sorry about this, if I missed it already can we schedule for December?  I'd really love to chat with your community.

**Comment by arei** [comment]
You havent missed it yet. This would be tonight, Eastern Time Aone, which is about 19 hours from now. Can you do this or do we need to find a replacement?

- Glen

**Comment by Ekwuno** [comment]
Ah! That's like 4am! Do you have any slots GMT +1 or +3 favorable ?

**Comment by arei** [comment]
No, sorry, we only run once a month, from 7pm to 9pm EST (GMT -5). 

Are you not going to be able to make this for tonight? (7 hours from the time this message was posted.)

**Comment by arei** [comment]
We will not be moving forward with this talk at this time.
