### ISSUE TITLE
Cross Browser Support © 2020 Adam Ayd

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#229]
**Talk Title:** 
Cross Browser Support © 2020 Adam Ayd

**Talk Idea, described briefly:** 
Cross browser support has never been easier but that still does mean there aren't things to watch out for. Join me as I rail against IE in 2020, talk about moral questions regarding the dominance of Chrome, and even share some data on browser support from CCJS users

**Your name:** 
Eric Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 mins, let's be real I've never done a talk shorter

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] July 1st, 2020
- [x] August 5th, 2020
- [x] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by esauter5** [comment]
Hey @git-masi are you (or Adam?) still available to give this talk in August/September?

**Comment by git-masi** [comment]
Hi @esauter5  yes I am still available to give this talk

**Comment by esauter5** [comment]
Great, let's plan on August then! See you next Wednesday.

**Comment by arei** [comment]
Eric, thank you for another talk!
