### ISSUE TITLE
Using GraphQL as a wrapper around a REST API

### ISSUE THREAD

**Issue by jhyman2** [charmCityJs/talks#230]
**Talk Title: Using GraphQL as a wrapper around a REST API**

**Talk Idea, described briefly: You can setup GraphQL and have it point to your REST API with virtually no code! I'll show you what this looks like, and the benefits this provides.** 

**Your name: Jamison Hyman** 

**CCJS Slack username: jhyman2**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): @hyman_says** 

**Estimated Talk Length: (1-15 min please): 12** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] August 5th, 2020
- [x] September 2nd, 2020
- [x] October 7th, 2020
- [x] November 4th, 2020
- [x] December 2nd, 2020

**Comment by esauter5** [comment]
Hey @jhyman2! Are you still available to give this talk in August/September?

**Comment by jhyman2** [comment]
Hey @esauter5, yes I am. Let me know which month I should be prepared for. I will need a couple days to polish the slide deck.

**Comment by esauter5** [comment]
Let's go with September!

**Comment by esauter5** [comment]
Hey @jhyman2 , just double checking that youre still available to speak at our meetup next Wednesday, the 2nd?

**Comment by jhyman2** [comment]
Hey @esauter5, yes I'm all set!

**Comment by jhyman2** [comment]
For posterity:

Slides: https://docs.google.com/presentation/d/1rbmFIxu8gVuX3n-i3jvHNTvv8dx_k0bFwhjsYRd73jQ/edit#slide=id.p
Repo: https://github.com/jhyman2/CCJS4PETS
