### ISSUE TITLE
I'm not technical enough to give this talk

### ISSUE THREAD

**Issue by olearycrew** [charmCityJs/talks#231]
**Talk Title:** 
I'm not technical enough to give this talk

**Talk Idea, described briefly:** 
I don't have a computer science degree. I haven't ever been paid to write code for a living. In fact, the only programming "class" I've ever taken was a VB business school class 15 years ago.

In this talk, I'll prove that the qualifications to learn, teach, and talk about technology are not the "traditional" ones. No one should feel that their opinion or experience is less than someone who has more of a typical software engineering resume. By giving three mini-demos of technology that I have no right talking about, I'll show that being self-taught doesn't mean you shouldn't share your knowledge with others. The only requirement is a little creativity and a lot of curiosity, and anyone can stand up on stage or write a blog or teach their coworkers something new. 

**Your name:** 
Brendan O'Leary

**CCJS Slack username:**
Brendan

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
olearycrew

**Estimated Talk Length: (1-15 min please):** 
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] August 5th, 2020
- [x] September 2nd, 2020
- [ ] October 7th, 2020
- [x] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by esauter5** [comment]
Hey @olearycrew! Are you still available to give this talk in August/September?

**Comment by olearycrew** [comment]
@esauter5 yes those dates still work for me.

**Comment by esauter5** [comment]
Perfect! let's plan for next Wednesday at our August meetup then!

**Comment by arei** [comment]
Brendan, thank you as always for another awesome talk!
