### ISSUE TITLE
What design patterns can teach us about JavaScript: singleton pattern

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#232]
**Talk Title:** 
What design patterns can teach us about JavaScript: singleton pattern

**Talk Idea, described briefly:** 
I've been studying design patterns recently and I think that they highlight some of the differences between JS and other OO languages like Java. In particular I think the singleton pattern, given its relatively straightforward nature, provides an interesting opportunity to learn about some of these differences. Though I am not advocating for any specific usage of the singleton pattern.

This may or may not become a series of talks about design patterns. Yes, I realize that at the last meetup I said my next talk was going to be about regular expressions but I have this one ready to go because of the way that I study so I'm saving regex for later.

**Your name:** 
Eric Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] September 2nd, 2020
- [x] October 7th, 2020
- [x] November 4th, 2020
- [x] December 2nd, 2020

**Comment by asasmith** [comment]
@git-masi are you available to give this talk this week (9/2)?

**Comment by git-masi** [comment]
@asasmith yes I can give the talk at the meetup this week!

**Comment by asasmith** [comment]
@git-masi thanks for a great talk!
