### ISSUE TITLE
ElectronJS: Breaking out of the browser sandbox with Javascript

### ISSUE THREAD

**Issue by eli0shin** [charmCityJs/talks#233]
**Talk Title:** 
ElectronJS: Breaking out of the browser sandbox with Javascript

**Talk Idea described briefly:** 
Javascript is no longer a toy language used solely to add interactivity to websites. Some of our favorite desktop apps are built almost entirely with JS. Let's take a look at some of the limitations that exist when building an app for the browser and how Electron changed that. I will go over why electron was created and what existed before it. We'll also take a look at some of the features available in Electron that don't exist in the browser. Finally, we'll build a basic app in Electron to demonstrate how to get started.

**Your name:** 
Eli Oshinsky

**CCJS Slack username:**
eli0shin

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@eli0shin

**Estimated Talk Length: (1-15 min please):** 
15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] September 2nd, 2020
- [x] October 7th, 2020
- [x] November 4th, 2020
- [x] December 2nd, 2020

**Comment by arei** [comment]
Eli, thank you for the super informative dive into Electron. Super informative!
