### ISSUE TITLE
New Features in TypeScript 4.0

### ISSUE THREAD

**Issue by towsonTigers** [charmCityJs/talks#234]
**Talk Title: New Features in TypeScript 4.0** 

**Talk Idea, described briefly: Describe the new features in TypeScript 4.0 and provide a brief example of each** 

**Your name: Dave Morris** 

**CCJS Slack username:David Morris**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):15mins (could go 30mins if necessary)** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [x ] November 4th, 2020
- [x ] December 2nd, 2020

**Comment by esauter5** [comment]
@towsonTigers Are you still good for Nov 4?

**Comment by towsonTigers** [comment]
Sure. Thank you! -Dave

**Comment by esauter5** [comment]
Sounds good! We will see you on 11/4.

**Comment by arei** [comment]
Dave, thank you for your talk!
