### ISSUE TITLE
WebRTC: Get Your User's Media and Make Art With It

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#235]
**Talk Title:** WebRTC: Get Your User's Media and Make Art With It

**Talk Idea, described briefly:** WebRTC can be roughly divided into two topics: the getUserMedia "grab the user's camera/microphone and do stuff" part, and the RTCPeerConnection "send things peer-to-peer between browsers" part. This talk is going to dive into the former, talking about how to access Webcam and microphone feeds, and some of the awesome things you can do with them.

**Your name:** Chris Uehlinger

**CCJS Slack username:** @uehreka

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @uehreka

**Estimated Talk Length: (1-15 min please):** 15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ x] October 7th, 2020
- [ ] November 4th, 2020
- [ ] December 2nd, 2020

**Comment by arei** [comment]
As always chris, thank you for a great talk!
