### ISSUE TITLE
WebRTC Part 2: A STUNning TURN of Events!

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#236]
**Talk Title:** WebRTC Part 2: A STUNning TURN of Events!

**Talk Idea, described briefly:** This talk is a continuation of my talk from October 2020, but this time we're diving straight into the part of WebRTC concerned with sending audio, video and data between browsers on different computers. We're gonna get into all of it: ICE, STUN, TURN, NAT Punching and "What's The Deal With IPv4?" By the end, I'll have a couple downloadable examples that will allow you to try out WebRTC on computers in your house, as well as information on where to go next.

**Your name:** Chris Uehlinger

**CCJS Slack username:** uehreka

**Twitter username (optional):** @uehreka

**Estimated Talk Length: (1-15 min please):** 15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] May 6th, 2020
- [ ] June 3rd, 2020
- [ ] July 1st, 2020
- [ ] August 5th, 2020
- [ ] September 2nd, 2020
- [ ] October 7th, 2020
- [ ] November 4th, 2020
- [ x ] December 2nd, 2020

**Comment by esauter5** [comment]
@chrisuehlinger I'm going to put you down for December. We'll follow up before then, but if anything changes please let us know.

**Comment by esauter5** [comment]
@chrisuehlinger Just checking that you're still available for December?

**Comment by chrisuehlinger** [comment]
Yes I am

**Comment by arei** [comment]
Thanks for another amazing talk Chris!
