### ISSUE TITLE
a talk about regular expressions

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#238]
**Talk Title:** 
Regular Expressions - They're not just gibberish in your text editor

**Talk Idea, described briefly:** 
Regular expressions can be confusing the first time you see them. They are a topic that many people feel uncomfortable with. Let's discuss where regular expressions shine, learn the basics, and even get into some more esoteric ideas.

**Your name:** 
Eric Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):**
15 mins (are my talks ever short?) 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] December 2nd, 2020
- [x] February 3rd, 2021

**Comment by asasmith** [comment]
@git-masi are you still able to give this talk at our february meetup?

**Comment by arei** [comment]
Thank you for giving this talk Eric!
