### ISSUE TITLE
Introduction to 3D Printing!

### ISSUE THREAD

**Issue by oliikit** [charmCityJs/talks#239]
**Talk Title:** Intro to 3️⃣🇩🖨

**Talk Idea, described briefly:** While not code related, during COVID times, I found a new side hobby: 3D Printing. So this talk will go over the mechanics of 3D printing, how to get started, best practices, and more! (And maybe how to print with food! 😜) By the end of the talk, you'll have the knowledge to get started and maybe the desire to print everything. 

(Slides are currently here: https://github.com/oliikit/talks/tree/main/3d-printing. I'll need to trim it done so it's digestable in 15 minutes. 😃)

**Your name:** Olivia

**CCJS Slack username:** olivia

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** oliikit

**Estimated Talk Length: (1-15 min please):** 15min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [x] March 3rd, 2021
- [x] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
@oliikit would you be able to give this talk at our february meetup?

**Comment by oliikit** [comment]
I am not available for February, but I can still do March/April.

**Comment by asasmith** [comment]
Hi, @oliikit are you still able to give this talk at our march meetup?

**Comment by oliikit** [comment]
If you all need another for March, I can do it. 😃 I can also do April,

**Comment by asasmith** [comment]
March would be great. Thanks!

**Comment by asasmith** [comment]
Thanks for giving this talk Olivia!
