### ISSUE TITLE
Using Mapbox Impact Tools to make a spreadsheet-powered interactive map

### ISSUE THREAD

**Issue by trevorspecht** [charmCityJs/talks#240]
**Talk Title:** 
Using Mapbox Impact Tools to make a spreadsheet-powered interactive map

**Talk Idea, described briefly:** 
[Mapbox Impact Tools](https://www.mapbox.com/impact-tools/) are designed to help organizations create interactive maps without having to run a database or write thousands of lines of code. I will demonstrate how I have used two of these tools to generate a map of Baltimore black-owned restaurants with a Google Sheet as the back end, published with GitHub Pages. I'll show how I customized the map to meet the needs of my "customer". Then I'll show how I used a Python script to scrape the web page that has the list of restaurants, used a geocoder library to derive coordinates from street addresses, and populated the Google sheet.

**Your name:** 
Trevor Specht

**CCJS Slack username:**
`@trevor`

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
`@TrevorSpecht`

**Estimated Talk Length: (1-15 min please):** 
15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [x] March 3rd, 2021
- [x] April 7th, 2021
- [x] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
@trevorspecht would you be able to give this talk at our february meetup?

**Comment by trevorspecht** [comment]
@asasmith yes I can do that

**Comment by asasmith** [comment]
thanks!

**Comment by arei** [comment]
Thank you for giving this talk Trevor!
