### ISSUE TITLE
Google's Page Experience Update

### ISSUE THREAD

**Issue by ecarlisle** [charmCityJs/talks#241]
**Talk Title:**  Google's Page Experience Update

**Talk Idea, described briefly:** In May 2021 Google will release the Page Experience Update, an algorithm update that will evaluate speed, responsiveness, and visual stability. This update will incorporate Google's Core Web Vitals, new search signals to measure the effectiveness of site experience. This presentation focuses on:
1. What are the Core Web Vitals?
2. How to evaluate this new search signals with Google Lighthouse 7 & browser utilities.
3. The Lighthouse npm module.

**Your name:** Eric Carlisle

**CCJS Slack username:** eric.carlisle

**Twitter username (optional):** eric_carlisle

**Estimated Talk Length: (1-15 min please):** 10-15 minutes

**Availability:**
Any future dates would be fine. Thanks! 👍🏼

**Comment by asasmith** [comment]
@ecarlisle good for our february meetup?

**Comment by arei** [comment]
Thank you for giving this talk Eric!
