### ISSUE TITLE
All About WebTransport

### ISSUE THREAD

**Issue by bmanek** [charmCityJs/talks#242]
**All About WebTransport** 

*What is WebTransport? Why is WebTransport? Why read the docs when a guy who wants to submit a talk is ready to read and summarize it all for you?*

**Ben Manekin** 

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Estimated Talk Length: ~15 minutes:** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] February 3rd, 2021
- [x] March 3rd, 2021
- [x] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Hi @bmanek, are you still able to give this talk at our march meetup?

**Comment by bmanek** [comment]
Yes, I'm confident I'll have it ready by then

**Comment by asasmith** [comment]
Thanks for giving this talk Ben!
