### ISSUE TITLE
(De)Comming Telemetry or Bashing Bits with JavaScript

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#243]
**Talk Title:** 

(De)Comming Telemetry or Bashing Bits with JavaScript

**Talk Idea, described briefly:** 

Sometimes, you choose to or just can't get around working with binary data, especially when working with telemetry. We'll go over your options.

**Your name:** 

Shane Knudsen

**CCJS Slack username:**

ShaneKnudsen

**Twitter username (optional):** 

CrclOfConfusion

**Estimated Talk Length: (1-15 min please):** 

15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] March 3rd, 2021
- [x] April 7th, 2021
- [x] May 5th, 2021
- [x] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Hi @circleofconfusion, just want to confirm you're available to give this talk at our march meetup.

**Comment by circleofconfusion** [comment]
Yep, I can be ready for March.

**Comment by asasmith** [comment]
Thanks for giving this talk Shane!
