### ISSUE TITLE
Treehouse TechDegree & Getting Started with JS

### ISSUE THREAD

**Issue by hellobencarlson** [charmCityJs/talks#244]
**Talk Title:** Treehouse TechDegree & Getting Started with JS

**Talk Idea, described briefly:** Review the TechDegree program from Treehouse (2 relevant certifications- Front End Web Dev (includes JS) and Full Stack JS), including a brief overview (highlights of areas covered, projects, resources, and student support) and how these helped me progress after being stuck trying several other resources before.

**Your name:** Ben Carlson

**CCJS Slack username:** Ben Carlson

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 10 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 3rd, 2021
- [x] April 7th, 2021
- [ ] May 5th, 2021
- [x] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Hi Ben, are you still able to give this talk at our april meetup?

**Comment by hellobencarlson** [comment]
Sure!

**Comment by asasmith** [comment]
Thanks for giving this talk Ben!
