### ISSUE TITLE
Broadcasting on the Web with HLS and DASH

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#245]
**Talk Title:** Broadcasting on the Web with HLS and DASH

**Talk Idea, described briefly:** My previous two talks were about WebRTC: A modern API for doing lossy-but-zero-latency audio and video in the browser. But what if you want to do what YouTube and Twitch do: High quality live video but with a 10-ish second delay? Can you easily build your own Twitch?

Yes. And believe it or not, it's actually *easier* than working with WebRTC. In fact, you can broadcast video across America with an Express server and an S3 bucket. This talk is going to look into what it takes to support HTTP Live Streaming (HLS) and MPEG-DASH, the two most commonly used techniques for live streaming video to the browser.

**Your name:** Chris Uehlinger

**CCJS Slack username:** uehreka

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** uehreka

**Estimated Talk Length: (1-15 min please):** 20 minutes (sorry!)

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [x] April 7th, 2021
- [x] May 5th, 2021
- [x] June 2nd, 2021
- [x] July 7th, 2021
- [x] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks for giving this talk Chris!
