### ISSUE TITLE
Help a Junior Dev Practice Talking About Her Code!

### ISSUE THREAD

**Issue by SamanthaSolomon** [charmCityJs/talks#246]
**Talk Title:** Help a Junior Dev Practice Talking About Her Code!

**Talk Idea, described briefly:** One of the challenges of everything being virtual is less opportunities to talk about code. For me, writing about it is easier, but that is not how job interviews work! I am a recent full-stack bootcamp grad that would like to practice talking about my JS code by presenting something I have built. I would encourage feedback via chat so I can improve. It would be really cool if this was a "themed" night and other junior devs presented too!

**Your name:** Samantha Solomon

**CCJS Slack username:** Samantha Solomon

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** @SamLeahSol

**Estimated Talk Length: (1-15 min please):** 10 min or less

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [x] May 5th, 2021
- [x] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
thanks for giving this talk Samantha!
