### ISSUE TITLE
MemeStock: Making an AI

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#247]
**Talk Title:** 
MemeStock: Making an AI

**Talk Idea, described briefly:**
MemeStock is a stock trading social media hybrid (all stocks and money are fake) that I am developing with some fellow CCJS members. Some aspects of MemeStock resemble a game, particularly the AI. In this talk I will discuss how the AI was developed.

**Your name:** 
Eric Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 mins (do I ever have talks less than that?)

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] May 5th, 2021
- [ ] June 2nd, 2021
- [x] July 7th, 2021
- [x] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
thanks for giving this talk Eric!
