### ISSUE TITLE
Hackaton Expirience 

### ISSUE THREAD

**Issue by purisquiri** [charmCityJs/talks#248]
**Talk Title: Hackaton Experience as a junior developer** 

**Talk Idea, described briefly: I want to talk about my first hackathon, what languages we use, how we worked as a team, and how we organize the workflow 

**Your name: Mauro Dorigo-Cortes

**CCJS Slack username: Mauro Dorigo

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):@dorigo_cortes

**Estimated Talk Length: (1-15 min please): 8 mins

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [x ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
thanks for giving this talk Mauro!

**Comment by purisquiri** [comment]
Thank you all for having this amazing group !!
