### ISSUE TITLE
Control a Vehicle with a Web Browser

### ISSUE THREAD

**Issue by circleofconfusion** [charmCityJs/talks#249]
**Talk Title:** 

Control a Vehicle with a Web Browser

**Talk Idea, described briefly:**

Let's explore how to control a small vehicle using inexpensive hardware and JavaScript!

**Your name:** 

Shane Knudsen

**CCJS Slack username:**

ShaneKnudsen

**Twitter username (optional):** 

@CrclOfConfusion

**Estimated Talk Length: (1-15 min please):** 

15

- [ x ] June 2nd, 2021
- [ x ] July 7th, 2021
- [ x ] August 4th, 2021
- [ x ] September 1st, 2021
- [ x ] October 6th, 2021
- [ x ] November 3rd, 2021
- [ x ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks for giving this talk!
