### ISSUE TITLE
The lazy way to better code quality

### ISSUE THREAD

**Issue by rayners** [charmCityJs/talks#25]
Your name: David Raynes

Your idea: Lint(ers). Not just for dryers anymore. There are tools that will tell you just how awful your code really is.

Approx length: 20 minutes

Month(s) available: August/September

**Comment by latazzajones** [comment]
I love this idea!

**Comment by jgaskins** [comment]
@rayners Wanna talk about this at the September 2 meetup?

**Comment by rayners** [comment]
@jgaskins Hey! Sorry I missed the note. I have a couple big things lining up in the next month. Give me a day or so to decide if I can toss a talk prep into the mix?

**Comment by rayners** [comment]
@jgaskins Count me in!

**Comment by jgaskins** [comment]
Sweet! You're on the list for Sep 2. Thanks @rayners!
