### ISSUE TITLE
A web socket primer

### ISSUE THREAD

**Issue by Homerade** [charmCityJs/talks#250]
**Talk Title:** 
 A web socket primer

**Talk Idea, described briefly:** 
Basics on what web sockets are 

**Your name:** 
Stephanie Vizzi

**CCJS Slack username:**
@steph / Stephanie Vizzi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
@homerade

**Estimated Talk Length: (1-15 min please):** 
10 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_
Whenever Shane does his
- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [x] June 2nd, 2021
- [x] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks for giving this talk!
