### ISSUE TITLE
Git Gud: An Assortment of Tips for Getting Better at Git

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#251]
**Talk Title:** Git Gud: An Assortment of Tips for Getting Better at Git

**Talk Idea, described briefly:* There are a lot of cool Git features and workflows that not many people know about, I’ll demonstrate and explain a bunch of them, including:
- `git mv` for renaming things
- `git reflog` for saving your bacon when things get bad
- What the heck “detached HEAD” means
- Using `git cherry-pick` To reconstruct a branch

**Your name:** Chris Uehlinger

**CCJS Slack username:** uehreka

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** uehreka

**Estimated Talk Length: (1-15 min please):** 15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ x ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by chrisuehlinger** [comment]
Unfortunately I have a big project right now and can’t do June.

**Comment by asasmith** [comment]
Thanks @chrisuehlinger! Scheduling this for our july meetup.

**Comment by arei** [comment]
@chrisuehlinger Thanks for the super informative talk last night!
