### ISSUE TITLE
plopdown.video talk

### ISSUE THREAD

**Issue by spaceribs** [charmCityJs/talks#252]
**Talk Title:** Plopdown.Video - Vandalizing Netflix for remix and commentary

**Talk Idea, described briefly:** An introduction to the [plopdown.video](https://plopdown.video) feature set, system architecture, next steps and a demonstration of the tool.

**Your name:** Aaron Brewer

**CCJS Slack username:** N/A (request put in)

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [x] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks @spaceribs ! Scheduling this for our july meetup.

**Comment by spaceribs** [comment]
@asasmith I haven't been able to get into the meetup, is there something wrong?

**Comment by arei** [comment]
@spaceribs Thank you for your excellent talk last night. Please come give another talk soon!
