### ISSUE TITLE
Using JavaScript as my Butler

### ISSUE THREAD

**Issue by kndshein** [charmCityJs/talks#253]
**Talk Title:**
Using JavaScript as my Butler: Automating My Laziness

**Talk Idea, described briefly:**
Backstory: I have been chugging away at algorithms, and as a way to centralize all the algorithms I have learned/solved, I store them on my GitHub. However, I wanted more -- I wanted a Table of Contents page for the algorithms in a markdown file.

The problem: After every algorithm uploaded onto GitHub, I have to manually go into my markdown file and input said uploaded algorithm alphabetically into the Table of Contents, like a chump.

The solution: Not wanting to spend half a minute everyday, I spent 3 hours figuring out how to automate the entire process. Thus, my first ever automation code was born -- the code looks through my local JavaScript files, renames the titles, converts the titles into clickable links in the md file, and commit-pushes the code onto my GitHub.

The outcome: Everyday, whenever I run the script, I feel like I just discovered e = mc^2.

**Your name:** 
Kaung Shein

**CCJS Slack username:**
kndshein

**Estimated Talk Length:**
7 - 10 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [x] July 7th, 2021
- [x] August 4th, 2021
- [x] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks @kndshein! Scheduling this for our july meetup.

**Comment by asasmith** [comment]
@kndshein are you able to give this talk at our september 1 meetup?

**Comment by kndshein** [comment]
Yes, I can do that! @asasmith

**Comment by asasmith** [comment]
Excellent! Thanks!

**Comment by asasmith** [comment]
Thanks for giving this talk!
