### ISSUE TITLE
Using WebSockets in a serverless back end

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#254]
**Talk Title:** 
WebSockets & serverless & buzzwords, oh my!

**Talk Idea, described briefly:** 
WebSockets are long lived connections allow for two way data from from client to server. Serverless is a backend architecture that leverages short lived cloud functions on demand for massive scalability. Let's explore how to get these two mismatched technologies to play nicely together... or at least play together period.

**Your name:** 
Eric "Glen's Nemesis" Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 at least

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [x] October 6th, 2021
- [x] November 3rd, 2021
- [x] December 1st, 2021

**Comment by asasmith** [comment]
@git-masi Are you able to give this talk at our september 1 meet up?

**Comment by chrisuehlinger** [comment]
_Please_ give this talk.

**Comment by asasmith** [comment]
Thanks for giving this talk!
