### ISSUE TITLE
Building an automated outside collaborator lifecycle system

### ISSUE THREAD

**Issue by trevorspecht** [charmCityJs/talks#255]
**Talk Title:** 

Building an automated outside collaborator lifecycle system

**Talk Idea, described briefly:** 

I will describe a system I've built using Node.js and AWS services to streamline and automate GitHub outside collaborator lifecycle management. I'll explain the architecture and why I built it this way, as well as some technical details of how it works.

**Your name:** 

Trevor Specht

**CCJS Slack username:**

@trevor

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

Tree4Specht

**Estimated Talk Length: (1-15 min please):** 

15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [x] October 6th, 2021
- [x] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks for submitting @trevorspecht ! Are you still able to give this talk at our september (9/1) meetup?

**Comment by trevorspecht** [comment]
Hi @asasmith. I just looked and realized I have a conflict on Sept 1. The October meeting should still be fine.

**Comment by asasmith** [comment]
Thanks! I'll schedule you for October and confirm once we're a little closer to that meetup.

**Comment by asasmith** [comment]
Thanks for giving this talk!
