### ISSUE TITLE
Using the Power of Data to Create a Simple CMS with Forestry and Eleventy

### ISSUE THREAD

**Issue by troyvassalotti** [charmCityJs/talks#256]
**Talk Title:** 
Using the Power of Data to Create a Simple CMS with Forestry and Eleventy

**Talk Idea, described briefly:** 
As my website got more complex (a problem strictly of my own doing), I searched for a way to make my life easier. How could I add new content without having to open my editor and get distracted with something else? Better yet, how can I use the power of JSON, front matter, and Nunjucks to guarantee new content goes exactly where it should with all the proper styling? Enter Forestry CMS.

Forestry is a git-based CMS and Eleventy is a static site generator, both fully customizable to do only what you tell it to do. With the right configurations, you can use both to create a fully-featured website without too much hassle.

**Your name:** 
Troy Vassalotti

**CCJS Slack username:**
@ troyv

**Twitter username (optional):** 
@ validcharacters

**Estimated Talk Length: (1-15 min please):** 
10 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [x] October 6th, 2021
- [x] November 3rd, 2021
- [x] December 1st, 2021

**Comment by asasmith** [comment]
Hi @troyvassalotti, are you still available to give this talk at our October meetup?

**Comment by troyvassalotti** [comment]
@asasmith Yes, I am!

**Comment by asasmith** [comment]
Thanks for giving this talk @troyvassalotti !
