### ISSUE TITLE
Embracing the Graph

### ISSUE THREAD

**Issue by eli0shin** [charmCityJs/talks#257]
**Talk Title:** 
Embracing the Graph

**Talk Idea described briefly:** 
For a long time, I resisted the movement toward GraphQL APIs. When it became a requirement for a new project at work I finally broke down and set out to understand how the paradigm fit our domain model. I will dig into the concepts behind GraphQL and why it exists,  how it fits into an enterprise microservice environment, and when it may be the wrong solution for your use case.

**Your name:** 
Eli Oshinsky

**CCJS Slack username:**
eli0shin

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 minutes

**Availability:**

- [x] September 1st, 2021
- [x] October 6th, 2021
- [x] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by asasmith** [comment]
Thanks for your submission @eli0shin ! Cool if I go ahead and schedule you for 9/1?

**Comment by eli0shin** [comment]
That works

**Comment by asasmith** [comment]
Thanks for giving this talk!
