### ISSUE TITLE
Talk: i18n in Angular Applications

### ISSUE THREAD

**Issue by jmartin4563** [charmCityJs/talks#26]
*Your name:* Jessica Martin

*Your idea:* We live in a globalized world, so why is your Angular application only in English? In this talk, we'll discuss what internationalization actually means to you, the developer, and how we need to think about the text of the app, as well as any date/times and numbers. Finally, we'll look at some great libraries out there to help make localizing your app super easy. (Same talk done at Maryland JS meetup in columbia, but shorter :D)

*Approx length:* 10 - 15ish

*Month(s) available:* June+

**Comment by latazzajones** [comment]
Hi Jessica, Would you be willing to do this talk for the June 3rd meetup?

**Comment by jmartin4563** [comment]
Absolutely I can :D

**Comment by latazzajones** [comment]
Yay! Let me know if you have any questions. Looking forward to it :smile:
