### ISSUE TITLE
Plvylist: A Web Component For Playing Your Music

### ISSUE THREAD

**Issue by troyvassalotti** [charmCityJs/talks#260]
**Talk Title:**
Plvylist: A Web Component For Playing Your Music

**Talk Idea, described briefly:**
Born from a desire to learn how audio on the web works and can be customized, Plvylist is a web component made to look and feel like a multi-song audio player for your website. As long as you have a `json` file and are hosting your songs somewhere, you can stream your own music anywhere (on a website).

**Your name:**
Troy Vassalotti

**CCJS Slack username:**
troyv

**Twitter username (optional):**
validcharacters

**Estimated Talk Length: (1-15 min please):** 
10 minutes

**Availability:**
- [x] December 1st, 2021
- [x] January 5th, 2022

**Comment by asasmith** [comment]
Thanks for giving this talk @troyvassalotti
