### ISSUE TITLE
Patching Videostream

### ISSUE THREAD

**Issue by interactiveRob** [charmCityJs/talks#261]
**Talk Title:** 
Patching Videostream 

**Talk Idea, described briefly:** 

Videostream is a popular app for Google Cast devices. When a recent Google Chrome update broke the app's core functionality, its maintainers were unresponsive. I investigated the bug and made a very simple front-end fix. 

Videostream is not open-source, so I published a patch in the form of a Chrome extension called [Videostream Patch](https://github.com/interactiveRob/videostream-patch).

The patch fixed the issue for hundreds of users and received a surprising amount of positive support on Reddit including a bunch of people [buying me coffee](https://buymeacoffee.com/interactiverob).

Talk touchpoints:

- Tell the story, outline the problem and solution. 
- Demonstrate code and briefly demystify the architecture and configuration options of a Chrome extension, which is made up of `.js `and `.json` files. 
- Discuss the pros & cons of my fix, along with ethics of distributing an unofficial patchfix.

**Your name:** Rob Kirkner

**CCJS Slack username:** rob.kirkner

**Twitter username (optional):** @rob_kirkner

**Estimated Talk Length: (1-15 min please):** 10 mins

**Availability:**

- [x] November 3rd, 2021
- [x] December 1st, 2021

**Comment by asasmith** [comment]
@interactiveRob thanks for submitting this talk! I'm going to schedule you for our Nov 3 meetup. Let me know if that still works.

**Comment by asasmith** [comment]
Thanks for giving this talk!
