### ISSUE TITLE
CSS Subgrid: What is it, and why do we need it?

### ISSUE THREAD

**Issue by ShaneKWb** [charmCityJs/talks#262]
**Talk Title:** 

CSS Subgrid: What is it, and why do we need it?

**Talk Idea, described briefly:** 

I'll explain what Subgrid is, how it's used, and why it's a killer feature.

**Your name:** 

Shane Knudsen

**CCJS Slack username:**

ShaneKnudsen

**Twitter username (optional):** 

CrclOfConfusion

**Estimated Talk Length: (1-15 min please):** 

15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] December 1st, 2021
- [x] January 5th, 2022

**Comment by asasmith** [comment]
Thanks for giving this talk @ShaneKWb
