### ISSUE TITLE
Software Engineer interviewing for new or not so new engineers 

### ISSUE THREAD

**Issue by trevorspecht** [charmCityJs/talks#264]
**Talk Title:** 

Software Engineer interviewing for new or not so new engineers 

**Talk Idea, described briefly:** 

I just spent three months job searching and interviewing, and just got my first job offer as a software engineer. I’d like to share my experiences and some shared with me by others along the way. 

**Your name:** 

Trevor Specht

**CCJS Slack username:**

trevor 

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

trevorspecht

**Estimated Talk Length: (1-15 min please):** 

10-15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 3rd, 2021
- [ ] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021
- [x] Any dates in 2022

**Comment by asasmith** [comment]
Thanks for your submission @trevorspecht ! Are you still available to give this talk at our february meetup (2/2/22)?

**Comment by trevorspecht** [comment]
@asasmith yes I can give this talk on Feb 2

**Comment by asasmith** [comment]
@trevorspecht thanks for giving this talk!
