### ISSUE TITLE
Async/Await and you made me promises promises

### ISSUE THREAD

**Issue by towsonTigers** [charmCityJs/talks#265]
**Talk Title: Async/Await and promises promises

**Talk Idea, described briefly:**  5 minute power point presentation overview of Async/Await and promises in JavaScript followed by JavaScript demo in VSC and nodejs.
**Your name:**  David Morris

**CCJS Slack username:** David Morris, I gave a CharmCityJS presentation a while ago on TypeScript.

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): @dave_morr

**Estimated Talk Length: (1-15 min please):** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] February 3rd, 2021
- [x] March 3rd, 2021
- [ ] April 7th, 2021
- [ ] May 5th, 2021
- [ ] June 2nd, 2021
- [ ] July 7th, 2021
- [ ] August 4th, 2021
- [ ] September 1st, 2021
- [ ] October 6th, 2021
- [ ] November 3rd, 2021
- [ ] December 1st, 2021

**Comment by towsonTigers** [comment]
15 minute Talk (can be longer if needed)

**Comment by asasmith** [comment]
Thanks for your submission @towsonTigers ! Are you available to give this talk at our february meetup (2/2/22)?

**Comment by towsonTigers** [comment]
Hi Asa

Yes I can give this talk at the February meetup.

Thanks!
Dave

**Comment by asasmith** [comment]
@towsonTigers thanks for giving this talk!
