### ISSUE TITLE
The Swiss Army Knife of JS: .reduce explained

### ISSUE THREAD

**Issue by PearsonHill** [charmCityJs/talks#266]
**Talk Title: The Swiss Army knife of JS: .reduce explained ** 

**Talk Idea, described briefly:** 
An explanation of the higher order function reduce() and its wildly versatile application. 

**Your name:** 
Pearson Hill 

**CCJS Slack username:**
Pearson

**Estimated Talk Length: (1-15 min please):** 
10 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ x] February 2nd, 2022
- [ x] March 2nd, 2022
- [ x] April 6th, 2022
- [ x] May 4th, 2022
- [ ] June 1st, 2022
- [ x] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022
- [ ] January 4th, 2023

**Comment by asasmith** [comment]
Thanks for your submission @PearsonHill ! Are you still available to give this talk at our february meetup (2/2/22)?

**Comment by asasmith** [comment]
Thanks for giving this talk @PearsonHill
