### ISSUE TITLE
You're not too small for a monorepo - Improving developer experience with Turborepo

### ISSUE THREAD

**Issue by tknickman** [charmCityJs/talks#268]
**Talk Title:** 
---

> **You're not too small for a monorepo**
 _Improving developer experience with Turborepo._
---

**Talk Idea, described briefly:** 
>This talk will include a brief overview of monorepos - why they are useful, how they work, and what tooling is most commonly used to support them. This talk will mainly focus on how turborepo can take a lot of the pain out of developing in a monorepo, and how it makes it easy and beneficial enough for everyone to leverage the power of a monorepo. I have helped architect, scale, and maintain several large scale (100+ developers) monorepos at my current job, and have recently ported my personal sites (5 applications and 6 shared packages) to a monorepo using Turborepo and am excited to talk about the benefits.

**Your name:** 
> Thomas Knickman

**CCJS Slack username:** 
> [`@tknickman`](https://charmcityjs.slack.com/?channel=UM7QQNH1B)

**Twitter username (optional):** 
> _N/A_

**Estimated Talk Length: (1-15 min please):** 
> ~_10 minutes_

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February 2nd, 2022
- [ ] March 2nd, 2022
- [X] April 6th, 2022
- [X] May 4th, 2022
- [X] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022
- [ ] January 4th, 2023

**Comment by asasmith** [comment]
Hi @tknickman are you still able to give this talk at our April meetup?

**Comment by asasmith** [comment]
scheduled for april

**Comment by asasmith** [comment]
Thanks for giving this talk!
