### ISSUE TITLE
Quick and Simple Tooling with Gulp

### ISSUE THREAD

**Issue by troyvassalotti** [charmCityJs/talks#269]
**Talk Title:** Quick and Simple Tooling with Gulp

**Talk Idea, described briefly:** 

I recently took on a project at work and needed a system we could all use for authoring and processing our assets. Coming from a point of _no tooling_ on the team, I wanted it to be simple and easy for everyone to jump in. With Gulp, we now have a way to write our code and pipe it all through the right processors and minifiers.

**Your name:** Troy Vassalotti

**CCJS Slack username:** troyv

**Twitter username (optional):** validcharacters

**Estimated Talk Length: (1-15 min please):** 10-15

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] March 2nd, 2022
- [x] April 6th, 2022

**Comment by asasmith** [comment]
Thanks for your submission @troyvassalotti ! Going to schedule you for march.

**Comment by asasmith** [comment]
Thanks for giving this talk @troyvassalotti !
