### ISSUE TITLE
Thinking with prototypes

### ISSUE THREAD

**Issue by unstoppablecarl** [charmCityJs/talks#27]
Your name: Carl Olsen

Your idea: Go over the problems presented with inheritance in js. Present techniques to leverage prototypal OO instead of trying to emulate classical inheritance. 

somewhat relevant article: https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a

Approx length: 20 - 60 min

**Comment by apechimp** [comment]
@unstoppablecarl, do you want to give a 15-20 minute version of this talk at the August 5th meetup?

**Comment by unstoppablecarl** [comment]
sounds good

**Comment by apechimp** [comment]
Perfect! Thanks! I'll bug you about this again a week beforehand; otherwise, feel free to reach out in slack if you need anything.

**Comment by unstoppablecarl** [comment]
ok
