### ISSUE TITLE
Keyboard accessibility: What, Why, and How

### ISSUE THREAD

**Issue by airandfingers** [charmCityJs/talks#270]
**Talk Title:** 
Keyboard accessibility: What, Why, and How

**Talk Idea, described briefly:** 
I'll discuss what keyboard accessibility is, why it's important, and how we can test, fix, and avoid keyboard accessibility issues.

**Your name:** 
Aaron Yoshitake

**CCJS Slack username:**
@Aaron Yoshitake

**Twitter username (optional):** 
airandfingers (inactive)

**Estimated Talk Length: (1-15 min please):** 
10-15 minutes?

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 3rd, 2021
- [X] April 7th, 2021
- [X] May 5th, 2021
- [X] June 2nd, 2021
- [X] July 7th, 2021
- [X] August 4th, 2021
- [X] September 1st, 2021
- [X] October 6th, 2021
- [X] November 3rd, 2021
- [X] December 1st, 2021

**Comment by asasmith** [comment]
Hi @airandfingers are you still able to give this talk at our April meetup?

**Comment by asasmith** [comment]
Thanks for giving this talk!
