### ISSUE TITLE
So you think you know ASI?

### ISSUE THREAD

**Issue by WillRun4Cake** [charmCityJs/talks#274]
**Talk Title: So you think you know ASI?* 

**Talk Idea, described briefly: A very brief presentation on ASI. What it is, pros/cons, why important. Followed by a quiz of 12 example code snippets. A real-time quiz powered by DirectPoll.com to go alongside the presentation snippets.

Presently, all quiz questions are static text with the answers animated to appear after clicking. I don't currently plan to execute the example snippets. 

**Your name: Joseph Warner** 

**CCJS Slack username: Joseph ???*

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional): None** 

**Estimated Talk Length: (1-15 min please): 25 mins** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [x] June 1st, 2022
- [x] July 6th, 2022
- [x] August 3rd, 2022
- [x] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022

*The original presentation is in LibreOffice Impress (ODP). I converted to PowerPoint and cleaned it up best I could using a trial version which expires 4/17. I will probably use the ODP file to present.*
[ASI-Slides.pptx](https://github.com/charmCityJs/talks/files/8477744/ASI-Slides.pptx)
[ASI-Slides.odp](https://github.com/charmCityJs/talks/files/8477760/ASI-Slides.odp)

**Comment by asasmith** [comment]
Thanks for your submission @WillRun4Cake! Are you still available to give this talk at our June meetup?

**Comment by asasmith** [comment]
@WillRun4Cake are you still available to give this talk at our July meetup (7/6)?

**Comment by asasmith** [comment]
Thanks for giving this talk! Please remember to post your slides to our slack.
