### ISSUE TITLE
Getting started with Go as a JS developer

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#275]
**Talk Title:** 
Help I'm turning into a Gopher!

**Talk Idea, described briefly:**
Let's talk about how you can, and why you should, get started using the Go programming language as a JavaScript developer. We will compare two backend applications: one written using the Express framework for Node JS and one using Fiber the Express inspired framework for Go. Oh and also, Ember JS sucks 🐹 🔨 

**Your name:** 
Eric Masi

**CCJS Slack username:**
gitMasi

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
Lol when have I ever gone under 15 mins?

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [x] May 4th, 2022 - Star Wars Day
- [x] June 1st, 2022
- [x] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022

**Comment by asasmith** [comment]
Thanks for giving this talk @git-masi EMBER FTW!
