### ISSUE TITLE
Pick a Kit: Scrapers, Affiliates, and Charity

### ISSUE THREAD

**Issue by airandfingers** [charmCityJs/talks#277]
**Talk Title:** 

Pick a Kit: Scrapers, Affiliates, and Charity

**Talk Idea, described briefly:** 

Discussing the genesis and evolution of a project I've been building (off and on) since 2017: https://pickakit.com

**Your name:** 

Aaron Yoshitake

**CCJS Slack username:**

@Aaron Yoshitake

**Twitter username (optional):** 

airandfingers

**Estimated Talk Length: (1-15 min please):** 

15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [X] August 3rd, 2022
- [X] September 7th, 2022
- [X] October 5th, 2022
- [ ] November 2nd, 2022
- [X] December 7th, 2022

**Comment by asasmith** [comment]
@airandfingers thanks for your submission! Scheduling you for our august meetup.

**Comment by asasmith** [comment]
Thanks for giving this talk @airandfingers !
