### ISSUE TITLE
What the web components!?

### ISSUE THREAD

**Issue by nicklemmon** [charmCityJs/talks#278]
**Talk Title:** 
What the web components!?

**Talk Idea, described briefly:** 
High level overview of web components, their strengths, limitations, and how to implement them using [Lit](https://lit.dev/).

**Your name:** 
Nick Lemmon

**CCJS Slack username:**
🤔 unable to find this - searching for "Nick Lemmon" seems to work

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
nicklemmon

**Estimated Talk Length: (1-15 min please):** 
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [x] August 3rd, 2022
- [ ] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022

**Comment by asasmith** [comment]
Thanks for giving this talk @nicklemmon !
