### ISSUE TITLE
Intro to Electron Workshop

### ISSUE THREAD

**Issue by caseywatts** [charmCityJs/talks#279]
**Talk Title:** Intro to Electron Workshop

**Talk Idea, described briefly:**  [Electron](electronjs.org) is a framework you can use to make desktop applications using javascript. You likely use Electron apps every day -- Slack and VSCode are two examples. With electron, making a simple desktop application is as easy as making a simple web application. Learn to make your own Electron app in this 2 hour workshop :D

Here's the curriculum I've done last time I did this a few years ago (I'll update it before this workshop, of course!): https://gist.github.com/caseywatts/83783910d681989656962a434ef33c94

**Your name:** Casey Watts

**CCJS Slack username:** @caseywatts

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):**  @heycaseywattsup

**Estimated Talk Length: (1-15 min please):** This is a different format than the usual CCJS format -- a 2h interactive workshop where people bring their laptops.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [x] September 7th, 2022
- [x] October 5th, 2022
- [x] November 2nd, 2022
- [ ] December 7th, 2022

**Comment by asasmith** [comment]
@caseywatts I love this idea but I'm not sure how it would work for our format. Is there anyway to divide the content up in to smaller talks that could be given over successive months?

**Comment by caseywatts** [comment]
I totally understand if you all are committed to your format! Unfortunately I can't really do it in this interactive way in shorter time slots, no.

I bet many charmCityJS people would be interested in this. I wonder what attendees would say if you asked them about it at the next event?

**Comment by caseywatts** [comment]
If I end up doing this with another Meetup in the area, I'll let you all know!

(I don't think there's another JS Meetup in the area, is there?)

**Comment by arei** [comment]
There is a DC JS Meetup (sorry I dont have more detail than that) and this is more conducive to their format.
