### ISSUE TITLE
Terrible Lamb Types.

### ISSUE THREAD

**Issue by adamayd** [charmCityJs/talks#280]
**Talk Title:** Terrible Lamb Types

**Talk Idea, described briefly:** Terraform, Lambdas and TypeScript.  Discuss Terraform, AWS Lambdas, and TypeScript.  Touch on AWS CDK and AWS CLI, but focus on getting a working demo of a TypeScript Lambda built and implemented using Terraform

**Your name:** Adam Ayd

**CCJS Slack username:** @AdamAyd

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 15 min

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022 <- Maybe, but doubtful
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022

**Comment by asasmith** [comment]
Thanks for you submission @adamayd ! Scheduling you for our October meetup.

**Comment by adamayd** [comment]
@asasmith I will not be ready for this talk in October. My spare time has been consumed by AWS study as my current cert is expiring in October.

**Comment by asasmith** [comment]
Thanks for the heads up @adamayd . I'll update the schedule and make an announcement.

**Comment by adamayd** [comment]
Unable to devote time to this.  Behind on school and home items.
