### ISSUE TITLE
Back to the monolith

### ISSUE THREAD

**Issue by git-masi** [charmCityJs/talks#281]
**Talk Title:** 

Back to the monolith - from monolith to serverless and back
Also, why Glen is wrong about Serverless Framework

**Talk Idea, described briefly:** 

Let's talk about monolithic and serverless architectures, and why you probably won't do serverless right if you can't do a monolith right.

In the first half we'll pull in ideas from the books "Strategic Monoliths and Microservices" and "Learning Domain Driven Design".

In the second half we'll look at architecture diagrams, folder structures, and code snippets (in JS and Go) so that's it's not just theory.

**Your name:** 

Eric Masi

**CCJS Slack username:**

gitMasi

**Twitter username (optional):** 

Nah, catch me on LinkedIn

**Estimated Talk Length: (1-15 min please):** 

30 mins in defiance of 👆but seriously I have a lot of ground to cover so it would be best if we could do 2x 15 min sessions with a short break in between

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [x] September 7th, 2022
- [x] October 5th, 2022
- [ ] November 2nd, 2022
- [ ] December 7th, 2022

**Comment by asasmith** [comment]
@git-masi thanks for your submission. We've decided to cancel the september meetup so I'm scheduling you for october. As always, you're a gentleman and a scholar.
