### ISSUE TITLE
Talk idea: A very biased review of Remix

### ISSUE THREAD

**Issue by nikzb** [charmCityJs/talks#282]
**Talk Title:** 
A very biased review of Remix

**Talk Idea, described briefly:** 
Over the last 6 months or so I built a SaaS application with Remix. Having gone through the experience, I would like to explain the basics of using the framework and just share a bit about why I enjoyed using it. I am admitting up front that the experience was very positive and I'm a big fan, but I'll probably have at least some tradeoffs to share in terms of pros vs cons.

This talk will focus exclusively on Remix. I won't have time to talk about the application itself as there is already lots to explain about Remix itself.

**Your name:** 
Nik Baltatzis

**CCJS Slack username:**
nikzb

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022
- [X] October 5th, 2022
- [X] November 2nd, 2022
- [X] December 7th, 2022

**Comment by nikzb** [comment]
Btw, the title is totally open to changes. It could really just be "Intro to Remix" or something if you think that I don't need to be so obvious about the fact that I am a React / Remix fan 😄

**Comment by asasmith** [comment]
Thanks for your submission @nikzb ! Scheduling you for our october meetup.
