### ISSUE TITLE
Talk on MVC

### ISSUE THREAD

**Issue by Chaseocodes** [charmCityJs/talks#283]
**Talk Title:**  Shallow dive into MVC

**Talk Idea, described briefly:** 
 A brief over view of MVC and its structure as applied to a simple CRUD app.
**Your name:** 
Chase O'Hara
**CCJS Slack username:**
Chase O'Hara

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
 @chase0hara
**Estimated Talk Length: (1-15 min please):** 
 15-20 mins
**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 2nd, 2022
- [ ] April 6th, 2022
- [ ] May 4th, 2022 - Star Wars Day
- [ ] June 1st, 2022
- [ ] July 6th, 2022
- [ ] August 3rd, 2022
- [ ] September 7th, 2022
- [ ] October 5th, 2022
- [ ] November 2nd, 2022
- [x ] December 7th, 2022

**Comment by asasmith** [comment]
thanks for your submission @Chaseocodes ! Scheduling you for our 12/2022 meetup
