### ISSUE TITLE
Low-Code & No-Code with Many Code Choices

### ISSUE THREAD

**Issue by ecarlisle** [charmCityJs/talks#284]
**Talk Title:** 
Low-Code, No-Code... But There's Still Lots to Code!

**Talk Idea, described briefly:**
Static Site Generators like [11ty](https://www.11ty.dev/), [Gatsby](https://www.gatsbyjs.com/), and [Astro](https://astro.build/) give opportunity for high-performance, secure websites. In selecting one, there are several questions to ask such as:

> "Should I rely more on JavaScript templating or a component architecture?"

> "How can I control what is static and what is interactive?"

> "How may I integrate with services like headless CMSes or asset management systems?"

> "How can I best implement this site with Serverless or Edge?"

This presentation will be a short demonstration using [11ty](https://www.11ty.dev/) and [Vite](https://vitejs.dev/) using [Slinkity](https://slinkity.dev/). Examples of content generation, service integration, and JavaScript hydration will be provided.

**Your name:** 
Eric Carlisle

**CCJS Slack username:**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ http://charmcityjs.herokuapp.com/

**Twitter username (optional):** 
`eric.carlisle`

**Estimated Talk Length: (1-15 min please):** 
15 minutes, tops. I could make it 10 if that's too long.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

_(Any time works for me)_
- [x] March 2nd, 2022
- [x] April 6th, 2022
- [x] May 4th, 2022 - Star Wars Day
- [x] June 1st, 2022
- [x] July 6th, 2022
- [x] August 3rd, 2022
- [x] September 7th, 2022
- [x] October 5th, 2022
- [x] November 2nd, 2022
- [x] December 7th, 2022

**Comment by asasmith** [comment]
thanks for your submission @ecarlisle ! Scheduling you for our 12/2022 meetup.

**Comment by ecarlisle** [comment]
Sounds great, @asasmith ! Thanks!
