### ISSUE TITLE
Visual test-driven web development with Cypress Component Testing

### ISSUE THREAD

**Issue by astone123** [charmCityJs/talks#286]
**Talk Title:** Visual test-driven development with Cypress Component Testing

**Talk Idea, described briefly:** Introduce Component Testing with Cypress by talking about what it is, what problems it can potentially solve, and demonstrating how we can use it to drive the development of front-end components.

**Your name:** Adam Stone-Lord

**CCJS Slack username:** @astonelord

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** @astonelord_js

**Estimated Talk Length: (1-15 min please):** 10

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] February meetup
- [x] March meetup
- [x] April meetup
- [x] May meetup

**Comment by asasmith** [comment]
Hi @astone123! Thanks for you submission. Are you still able to give this talk at our April (wednesday 4/5) meetup? We're still meeting virtually.

**Comment by astone123** [comment]
@asasmith yes I can as long as it's virtual

**Comment by asasmith** [comment]
yep, we're still virtual. I'll add you to the schedule. Thanks!

**Comment by asasmith** [comment]
Thanks for giving this talk @astone123 !
