### ISSUE TITLE
Under the Knife: Dissecting how iteration works in JavaScript

### ISSUE THREAD

**Issue by WillRun4Cake** [charmCityJs/talks#291]
**Talk Title: Under the Knife: Dissecting how iteration works in JavaScript** 

**Talk Idea, described briefly: Discover how iteration works internally in JavaScript. This talk covers Symbol.iterator, the Iterable Protocol, Generators. It finishes by creating some custom iterators and even intentionally "botching" an operation to see what happens.** 

**Your name: Joseph Warner** 

**CCJS Slack username: willrun4cake**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please): 15 minutes** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 1st, 2023
- [x] April 5th, 2023
- [x] May 3rd, 2023
- [x] June 7th, 2023
- [x] July 5th, 2023
- [ ] August 2nd, 2023
- [ ] September 6th, 2023
- [ ] October 4th, 2023
- [ ] November 1st, 2023
- [ ] December 6th, 2023

**Comment by arei** [comment]
Love this idea!

**Comment by asasmith** [comment]
Thanks for the submission @WillRun4Cake! Are you still able to give this talk at our April (4/5) meetup?

**Comment by WillRun4Cake** [comment]
Yes I can give this talk for the April 5 meetup. I will post my slides so far soon.

**Comment by asasmith** [comment]
Thanks for this talk @WillRun4Cake !
