### ISSUE TITLE
How not to learn React and the npm eco-system

### ISSUE THREAD

**Issue by steranka** [charmCityJs/talks#293]
**Talk Title: How not to learn React and the npm eco-system** 

**Description:** 
I explain a technique I've used for years to learn many technologies:
(1) Operating Systems,
(2) Programming Languages: C, C++, Java, Maven, bash, python, php
(3) Learn how the foundation works and then you can solve any problem because you know the foundation.

To understand a specific APi, I'll create one or more stand alone programs or functions to illustrate how the technology works.  Years later, I can refer back to that sample code and know how something works.

I explain how that approach has failed me when I tried using it with React and the React eco-system and why it has failed.

(1) The constant need to improve and rewrite, instead of stabilize.
(2) The stigma surrounding something that is "stable" is old/outdated not being maintained. (9 mo is a long time in JS)
(3) The underlying problem is lack of maturity of the eco-system.
(4) The lack of support for managing version control of dependencies. (prior to package-lock.json).
(5) The lack of tools to support interoperability of a set of libraries.
(6) The lack of standardized libraries for common functionality.
(7) The continual change of the Javascript language itself.  Support for classes, await, threads...

Typical scenario:
(1) A bug is found in some code that was implemented 6mo-1 year ago,
(2) You try to build it from scratch and it won't build...
    - Might be older version of node/npm needed, turn to nvm install
    - Might be a minor dependency changed that was actually a breaking change
    - Might be npm changed how dependencies are now manged or introduced peer dependencies.
    - Might old webpack (react-build tooling) that uses old version of node to compile
(3) Challenge is to decide how much you care about understanding the underlying problem and reason for build failure with just getting it to compile again so you can actually make the change you want to make.
In the past I would try to understand the reason.... Now I just make best guess changes and move on.

I still try to have snippets of code that demonstrate how something works, I just care a lot less if it doesn't run in 6 months. :-)

**Patrick Steranka** 

**Patrick Steranka**

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please): 10-15min** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] July 5th, 2023 (maybe but still needs to be written)
- [v] August 2nd, 2023
- [v] September 6th, 2023
- [v] October 4th, 2023
- [ ] November 1st, 2023
- [ ] December 6th, 2023

**Comment by asasmith** [comment]
Hi @steranka! Thanks for submitting this talk. Confirming you're still able to give it at our august meetup (8/2)?

**Comment by steranka** [comment]
I can commit to that.  I haven't done it yet, but can have it done by 8/2.

I haven't ever done the screen sharing and presenting before, so to avoid snafu I'd like to test that process out prior to the meeting.

Pat
________________________________

**Comment by asasmith** [comment]
yep, we can work out a demo run at some point. Scheduling you for august. Thanks!

**Comment by asasmith** [comment]
@steranka can you join our slack https://charmcityjs.slack.com/join/shared_invite/zt-jdx7xtzq-ybTD_F0dFR52H~urr7e16Q#/shared-invite/email

**Comment by asasmith** [comment]
Hi @steranka just checking in to confirm you're still available for next Wednesday @ 7:00. Our meetup is virtual so no need to show up anywhere. If you get a chance could you join our slack http://slack.charmcityjs.org so we can discuss meetup details? Thanks!

**Comment by asasmith** [comment]
Thanks for giving this talk!

**Comment by steranka** [comment]
You are quite welcome.   Do you know how well it was received?  Would you recommend any changes for the next one?  I wouldn't mind doing one on dealing with git merge issues on package-lock.json!  I've lost many hours dealing with this one!
