### ISSUE TITLE
Regulatory Compliance APIs

### ISSUE THREAD

**Issue by HiGregory** [charmCityJs/talks#294]
**Talk Title:**  Regulatory Compliance APIs 

**Talk Idea, described briefly:** 

How JS Developers can integrate APIs for compliance and why this matters in an AI-first world. Reviews over LLMs, Open Data, and use cases that might be appropriate by the industry for JavaScript Developers.

We will cover general branded APIs like Open API's Moderation API and Twilio Regulatory Compliance we will then cover how this work in practice with an app written in 98% JavaScript covering how compliance APis can save developers time.

**Your name:**  Gregory Johnson

**CCJS Slack username:** Greg

**Estimated Talk Length: (1-15 min please):** 10 mins

**Availability:**
_Please check off the dates on which you would be interested in presenting your talk:_

- [ ] March 1st, 2023
- [ ] April 5th, 2023
- [ ] May 3rd, 2023
- [ ] June 7th, 2023
- [ ] July 5th, 2023
- [x] August 2nd, 2023
- [ ] September 6th, 2023
- [ ] October 4th, 2023
- [ ] November 1st, 2023
- [ ] December 6th, 2023

**Comment by asasmith** [comment]
Hi @HiGregory! Thanks for your submission! Confirming you're still available to give this talk at our august (8/2) meetup?

**Comment by HiGregory** [comment]
Yes, confirmed.

**Comment by HiGregory** [comment]
<img width="814" alt="MarketingMaterialforCharmCityJS" src="https://github.com/charmCityJs/talks/assets/10216510/b90aebdf-528d-4aa5-98f6-f113e12c5b7d">

Let me know when Charm City JS approves, so I can start sharing the talk with others in the Bmore Tech Slack.

**Comment by asasmith** [comment]
@HiGregory can you join our slack https://charmcityjs.slack.com/join/shared_invite/zt-jdx7xtzq-ybTD_F0dFR52H~urr7e16Q#/shared-invite/email

**Comment by asasmith** [comment]
Thanks for giving this talk!
