### ISSUE TITLE
Intro to AI

### ISSUE THREAD

**Issue by julianfl0w** [charmCityJs/talks#296]
**Talk Title** 
Intro to AI

**Talk Idea, described briefly:** 
Slides here:
https://docs.google.com/presentation/d/1SmkzMM8nB0Nu13DO8xypkzJZJOpAZ6J2BXr2X-5Y5mk/edit?usp=sharing

There are many slides, which I will advance quickly. This is a 10 minute talk, which I gave at Code and Coffee in July. It covers basic principles of AI, and a history from 1943. 

**Your name:** 
Julian Loiacono

**CCJS Slack username:**
Julian Loiacono

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
10 Minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] March 1st, 2023
- [ ] April 5th, 2023
- [ ] May 3rd, 2023
- [ ] June 7th, 2023
- [ ] July 5th, 2023
- [ ] August 2nd, 2023
- [ ] September 6th, 2023
- [X] October 4th, 2023
- [ ] November 1st, 2023
- [ ] December 6th, 2023

**Comment by asasmith** [comment]
Thanks for your submission @julianfl0w! Scheduling you for out october meetup!

**Comment by asasmith** [comment]
Thanks for giving this talk @julianfl0w
