### ISSUE TITLE
We're Snaking it Live! (Adapted from LibertyJS)

### ISSUE THREAD

**Issue by Schoonology** [charmCityJs/talks#297]
**Talk Title:** We're Snaking it Live!

**Talk Idea, described briefly:** Battlesnake is a multiplayer version of Snake “where your code is the controller”. We’ll build a bot to play Battlesnake from scratch. We’ll start with the most approachable bot imaginable, incorporating tools and techniques  optimized for Maximum Fun, including flood fill, A*, and height mapping.

**Your name:** Schoon

**CCJS Slack username:** @schoon

**Twitter username (optional):** Schoonology

**Estimated Talk Length: (1-15 min please):** 30 minutes. [Discussed it with Glen](https://charmcityjs.slack.com/archives/CP0QYMVH7/p1694120867218419); this is a shortened adaptation of a talk I'm giving at LibertyJS on October 12th.

**Availability:**

- [x] October 4th, 2023 - IDEAL
- [x] November 1st, 2023
- [x] December 6th, 2023

**Comment by asasmith** [comment]
Thanks for submitting a talk @Schoonology! Scheduling you for our october meetup.
