### ISSUE TITLE
Two tricks to achieve end-to-end type safety with TypeScript

### ISSUE THREAD

**Issue by nicklemmon** [charmCityJs/talks#298]
**Talk Title:**
Two tricks to achieve end-to-end type safety with TypeScript

**Talk Idea, described briefly:** 
Two simple strategies for validating types at run-time and build-time using TypeScript

**Your name:** 
Nick Lemmon

**CCJS Slack username:**
`@Nick Lemmon`

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 
`@nicklemmon`

**Estimated Talk Length: (1-15 min please):** 
15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] March 1st, 2023
- [x] April 5th, 2023
- [ ] May 3rd, 2023
- [ ] June 7th, 2023
- [ ] July 5th, 2023
- [ ] August 2nd, 2023
- [ ] September 6th, 2023
- [ ] October 4th, 2023
- [ ] November 1st, 2023
- [ ] December 6th, 2023

**Comment by asasmith** [comment]
Hi @nicklemmon checking in to see what your availability is to give this talk in 2024. Thanks.

**Comment by nicklemmon** [comment]
hey, @asasmith - I could do March or April - I just ticked the boxes up there.

**Comment by asasmith** [comment]
Thanks @nicklemmon! Scheduling you for March (tuesday 3/6).

**Comment by asasmith** [comment]
Thanks for giving this talk @nicklemmon !
