### ISSUE TITLE
Achieving Script Zen - Tools & Techniques for Healthier Work

### ISSUE THREAD

**Issue by WillRun4Cake** [charmCityJs/talks#303]
**Script Zen - Tips & Techniques for Healthier Work** 

**I offer some tools and techniques you can try for achieving healthier work habits, work environment.** 

**Joseph Warner** 

**Joseph**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please): 20** 

**Below is URL for my BitBucket repo with the Slidev project:**

**git clone https://willrun4cake@bitbucket.org/willrun4cake/slidev.git**

It should be publicly available but shoot me a message if it is not.
The branch I am actively working on is "healthtips"  (not "main").

Feel free to submit a pull request if you find any issues.

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] January 3rd 2024
- [ ] February 7th 2024
- [ ] March 6th 2024
- [ ] April 3rd 2024
✓ May 1st 2024
✓ June 5th 2024
✓ July 3rd 2024
✓ August 7th 2024
✓ September 4th 2024
✓ October 2nd 2024
✓ November 6th 2024
✓ December 4th 2024

**Comment by asasmith** [comment]
Hi @WillRun4Cake. Checking to see if you're still available to give this talk at our May meetup (5/1). Thanks!

**Comment by WillRun4Cake** [comment]
Hi Asa.

Yes, I will be available to give this talk online on May 1. 

Joseph

**Comment by asasmith** [comment]
Thanks for giving this talk @WillRun4Cake !
