### ISSUE TITLE
1)  Using Proxies to make singleton factories.  2)  Singleton factories for promises (allowing "parallel programming").

### ISSUE THREAD

**Issue by Codex-Orange** [charmCityJs/talks#305]
**1)  Using Proxies to make singleton factories.  2)  Using a promise singleton factory for "state-based parallel programming").** 

**In JavaScript, Proxies can be used to create singleton factories.  One interesting use of singleton factories is to create a "promise singleton factory".  Such a factory can be used to write a form of "state-based parallel programming".  I personally have used this form of programming when my app opens, allowing me to do start up tasks in parallel, using a human-readable coding style.** 

**Example code:**

```
async main() {
    const sf = new StateFactory();
    sf.start.then(async () => {
        // sf.start is already resolved
        // login and sync here
        sf.synced.resolve();
    });
    sf.start.then(async () => {
        // sf.start is already resolved
        // initialize mixins here
        sf.initialized.resolve();
    });
    sf.initialized.then(async () => {
        // render here
        sf.rendered.resolve();
    });
    sf.rendered.then(async () => {
        // update here
        sf.updated.resolve();
    });
    sf.rendered.then(async () => {
        // after render here
        sf.afterRendered.resolve();
    });
    sf.all(sf.synced, sf.updated)
        .then(async () => {
            // go to today page here
            sf.today.resolve();
        });
    sf.all(sf.afterRendered, sf.today)
        .then(() => {
            console.log("==== main() end ====");
        });
}
```

**Your name: Stan Silver** 

**CCJS Slack username: Codex-Orange**

_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please): 10 minutes** 

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] January 3rd 2024
- [ ] February 7th 2024
- [ ] March 6th 2024
- [ ] April 3rd 2024
- [ ] May 1st 2024
- [ ] June 5th 2024
- [x] July 3rd 2024
- [x] August 7th 2024
- [ ] September 4th 2024
- [ ] October 2nd 2024
- [ ] November 6th 2024
- [ ] December 4th 2024

**Comment by asasmith** [comment]
Thanks for submitting this talk @Codex-Orange! Scheduling your for our july (7/3) meetup.
