### ISSUE TITLE
Bootcamp experience

### ISSUE THREAD

**Issue by Dleibe1** [charmCityJs/talks#307]
**Talk Title:** 
Bootcamp Experience and Progress Since.
**Talk Idea, described briefly:** 
I want to share my bootcamp experience and the portfolio project I started there and have worked on since, as well as my plans for the future of the project.
**Your name:** 
Daniel P Leibensperger
**CCJS Slack username:**
Daniel Leibensperger
_If you're not a member of CCJS slack, sign up here so we can communicate about your talk, if you don't mind:_ [http://slack.charmcityjs.org](http://slack.charmcityjs.org)

**Twitter username (optional):** 

**Estimated Talk Length: (1-15 min please):** 
15 mins.
**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [ ] January 3rd 2024
- [ ] February 7th 2024
- [ ] March 6th 2024
- [ ] April 3rd 2024
- [ ] May 1st 2024
- [ ] June 5th 2024
- [ ] July 3rd 2024
- [ ] August 7th 2024
- [X] September 4th 2024
- [ ] October 2nd 2024
- [ ] November 6th 2024
- [ ] December 4th 2024

**Comment by asasmith** [comment]
Hi @Dleibe1 thanks for submitting this talk! Are you still available to give it at our meetup on september 4th? Thanks!

**Comment by Dleibe1** [comment]
Good evening,Yes, I wasn’t sure about which platform you guys use for online meetups, could you please send a link to the meetup?Best,DanielOn Aug 27, 2024, at 3:43 PM, Asa Smith ***@***.***> wrote:﻿
Hi @Dleibe1 thanks for submitting this talk! Are you still available to give it at our meetup on september 4th? Thanks!

**Comment by asasmith** [comment]
@Dleibe1 we use google meet. The link will be created and distributed the night of the meetup. There will be time before the meetup for you to log on and do a test run to make sure your permissions are set correctly etc. If you have any other questions feel free to ping me or one of the other organizers in our slack. Thanks!

**Comment by asasmith** [comment]
Thanks for giving this talk @Dleibe1 !
