### ISSUE TITLE
Why React Is Awesome

### ISSUE THREAD

**Issue by skevy** [charmCityJs/talks#31]
**Your name:** Adam Miskiewicz

**Your idea:**

Many of you have heard of React. It's the hottest thing out there right now. But with it's hype comes a lot of misinformation. In this talk, hear about how JSX is not a templating language, why the 5 billion Flux implementations shouldn't scare you, why immutable data and React are best friends, and where React is headed in the future.

**Approx length:** 20 minutes

**Comment by scottmessinger** [comment]
+1

**Comment by skevy** [comment]
Thanks Scott! Great talk tonight. And totally loved the conversation afterwards. We need more people in the local community thinking about all these ideas. And I think it's great that your talk started the conversation!

**Comment by jgaskins** [comment]
@skevy How do you feel about presenting this at the meetup on Sep 2?

**Comment by skevy** [comment]
Sure. This talk is kind of broad at the moment...should I narrow it down? Or keep it broad?

**Comment by jgaskins** [comment]
The title itself seems to imply breadth, so I don't think that's necessarily bad unless you end up going too deep into any of the points you made in your synopsis. I feel like the Flux stuff might require a bit too much depth (it's more than enough for its own talk), but touching on JSX, immutability, and the future of React (and anything else you can think of) would be great.

Basically, when I hear people talk about how awesome React is, the thing I hear most is "it's fast". While that's entirely true, I'd love to hear more about what makes it awesome. How does it reduce the probability of bugs and/or improve the developer experience? Again, nothing too deep unless you feel like narrowing the scope a bit.

**Comment by skevy** [comment]
Sounds good. I'm down for this. Sep 2 it is.
