### ISSUE TITLE
Request: Compile to JS libraries & languages

### ISSUE THREAD

**Issue by mgold** [charmCityJs/talks#32]
I could possibly give this talk myself, but I've already been accepted to give another talk, so I won't hog the stage. If someone is looking for a topic, this might be a good one since you get to leaf through a lot of different technologies rather than becoming an export in one.

Roughly in order of distance from vanilla JS (and also OO to functional), here are some libraries and languages that compile to JavaScript. You don't need to do all of them.
- Google Closure Compiler
- ECMAScript 6 (Babel)
- Coffeescript, LiveScript
- Dart (by Google), TypeScript (by Microsoft)
- ClojureScript
- PureScript and Elm
  - For those unfamiliar with functional programming, these might be intimidating. PureScript will likely only appeal to Haskell developers, but Elm is consciously simplifying and reaching out to JS devs.

You can also weigh in on whether native JS will be able to out-compete new languages, and what properties we might want and not want when choosing such a language.

Hopefully this is useful to someone.

**Comment by mgold** [comment]
Seems to be a partial dupe of #11, however this ticket looks beyond ES6 towards anything that compiles to JS.

**Comment by mgold** [comment]
I've left town so I can't give this talk, but someone else might be able to.

**Comment by jgaskins** [comment]
Whoa, left town? As in moved away? :-(

**Comment by mgold** [comment]
Yup, I was there for some of last Wednesday, must have missed you.

**Comment by esauter5** [comment]
Closing. We've had a few submissions for these pop up.
