### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by kschmelter1** [charmCityJs/talks#33]
Your name: Katrina Schmelter

Your idea: I'd like to show off a simple color typewriter I made using JavaScript. I designed it for a web design class last semester when challenged to create something that hadn't been done before. I'm more of a beginner using JavaScript, so the code is really basic.
See it for yourself at http://www.colortypewriter.com/
I'm currently creating a gallery page so that users can show off their cool designs. This is one made by a Sitepoint user: 
![img1-ozramos-560x400](https://cloud.githubusercontent.com/assets/10749722/8342030/4e87a384-1a97-11e5-9398-303e5d472427.png)

Approx length: Should take 5 mins, definitely less than 10 mins.

**Comment by jasonrhodes** [comment]
This is awesome, I can't wait for this talk. Are you on Twitter? I want to give you credit for this cause I know some people who will think this is super rad...

**Comment by kschmelter1** [comment]
Hi Jason,


I am not on twitter, but it might be possible to tag my Facebook. Can I do the talk this Wednesday, or do I need to wait for the next meeting?


Thanks,

Katrina


________________________________

**Comment by jasonrhodes** [comment]
Not on Wednesday as we have our lineup all set, but you'll hear from me or one of the other organizers as they schedule the next few months and we'll get you worked in along with others who have submitted. If you have months you know you won't be able to do, just let us know. Thanks!

**Comment by kschmelter1** [comment]
Thanks, I know I'll be able to do next month, but I do not have my fall class schedule yet so I'll notify you if September can't work for me. Just changed my e-mail on Github since I don't know how much longer I will have an owlmail account. So I can be reached through there or at katrina.schmelter@yahoo.com



________________________________

**Comment by apechimp** [comment]
@kschmelter1, do you want to give this talk at the August 5th meetup?

**Comment by kschmelter1** [comment]
Yes, August works great for me! 


     On Monday, July 6, 2015 3:40 PM, Mike Atkins <notifications@github.com> wrote:
   

 @kschmelter1, do you want to give this talk at the August 5th meetup?—

**Comment by apechimp** [comment]
Great! Thanks so much! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).

**Comment by jasonrhodes** [comment]
@kschmelter1 thanks again for speaking, it was fantastic! I hope you submit that to other places! Let me know if you need any help, ideas, etc.

btw, have you seen make8bitart.com ? Your talk reminded me of it. Thanks again!

**Comment by kschmelter1** [comment]
Thanks for having me, it was a great experience! I plan on continuing to develop my typewriter. I'll definitely keep in touch!Make8bitart.com is pretty awesome. The source code for that site is full of dinosaurs, it's hilarious.  


     On Wednesday, August 12, 2015 9:49 AM, Jason Rhodes <notifications@github.com> wrote:
   

 @kschmelter1 thanks again for speaking, it was fantastic! I hope you submit that to other places! Let me know if you need any help, ideas, etc.btw, have you seen make8bitart.com ? Your talk reminded me of it. Thanks again!—
