### ISSUE TITLE
Talk: Making async programming fun again

### ISSUE THREAD

**Issue by zanchin** [charmCityJs/talks#35]
Your name: Ilya Braude

Your idea: There's a new sheriff in town, and his name is Generator. Generators now let us write async code that looks synchronous in JavaScript without callbacks. There's a new web framework developed around this concept (koa) that I will talk about as well after introducing the concept.

Approx length: 20 min

**Comment by jasonrhodes** [comment]
Hey Ilya -- would you be interested in giving a slightly shorter talk that focuses just on generators in general? I'm trying to shy away from frameworks for this month and need something in the 10-15 minute range and I think this could be great, esp now that nodejs v4 is released with generators by default. 

If you'd prefer to wait and include the koa parts, that's totally fine, we'll schedule you for another month this fall, just let me know!

**Comment by zanchin** [comment]
Yeah, I can fit the talk into 10-15 min. I was going to focus the talk on using generators for async calls (vs callbacks and promises) when combined with the "co" library (as opposed to generators in general). Mentioning koa just to point out that there is a web framework out there built on these concepts, but not going into any details about it except maybe a hello world code sample. Does that fit with what you have in mind?

**Comment by jasonrhodes** [comment]
Yeah this sounds great! Scheduling this for October :+1:
