### ISSUE TITLE
Using Forever as a daemon

### ISSUE THREAD

**Issue by bizob2828** [charmCityJs/talks#36]
Your name: Bob Evans

Your idea: Talk about using forever as a server daemon that wraps a node.js script.  Also, lessons learned when trying to implement graceful shutdowns

Approx length: 10-15mins

Month(s) available: Any month

**Comment by jasonrhodes** [comment]
Closing this because we have #37 scheduled and we're not doing repeat speakers for now. Will re-open later when we start needing to do repeats, this should be a good talk.

**Comment by esauter5** [comment]
Per our talk, setting you up for September @bizob2828. Let me know if anything changes.

**Comment by esauter5** [comment]
We are forever grateful that you gave this talk @bizob2828. Thanks again!
