### ISSUE TITLE
Unit Testing tool chain for js(Mocha/Karma/Istanbul/Sinon)

### ISSUE THREAD

**Issue by bizob2828** [charmCityJs/talks#37]
Your name: Bob Evans

Your idea: I always hear people are reluctant to write unit tests because it takes too long to wrap their head around a test framework, or lack tools to make it easier to run tests and see reports, or code can't be unit tested.  I'd like to talk/share some grunt/gulp files, patterns for writing tests and using stubs/mocks to truly test.  I know this could get out of control so I will limit it to that showing examples of tests and code coverage, and maybe do a follow up another meetup.

Approx length: 15-20mins

Month(s) available: Any month

**Comment by jasonrhodes** [comment]
Do you think you could make this focus on a basic 15 minute intro to JS unit testing for folks who haven't done much? We have an audience that is probably familiar with testing somewhat from Ruby, etc. but who may not have done any at all with JS, especially client-side.

If so, this will work great for October.

**Comment by bizob2828** [comment]
Sure. Let's talk more about it. I can do whatever is desired
