### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by jgaskins** [charmCityJs/talks#38]
**Your name:** Jamie Personface (not even gonna change that)

**Your idea:** The thing to talk about these days for managing your app state with React is Flux. Flux is a neat way to manage data in React applications, where your app dispatches actions to all your stores. Redux lets you manage your state in a similar, but more functional style. In this talk, we'll gloss over the fundamentals of Flux and then show how Redux differs.

**Approx length:** 20ish minutes

**Comment by jasonrhodes** [comment]
I think I'm gonna close this with another Redux talk going tonight -- but now that we are opening up the gates for repeat speakers please feel free to submit something else soon sir!
