### ISSUE TITLE
Oboe.js, better JSON through streams

### ISSUE THREAD

**Issue by JuanCaicedo** [charmCityJs/talks#39]
**Name**: Juan Caicedo

**Idea**: 

Working with large JSON documents in a web app can be slow and cumbersome. Don't let your UX or performance suffer! 

Instead bring the event driven nature of Unix streams to your REST data transfer, using Oboe.js. By blending these two different yet familiar approaches, this talk will show how to make your apps faster and more reliable. 

This new way of looking at REST makes it possible to:
- Handle dropped connections with grace 
- Step outside the trade-off between big and small JSON 
- Convert any API to a mobile-friendly data source. 

By the end of this talk, developers will know how to implement Oboe.js in their client and server-side code and the practical applications for doing so.

**Approx length**: 15 minutes

**Comment by scottmessinger** [comment]
I would love to hear a talk on Oboe. I've heard of the library, but never done anything with it.

**Comment by JuanCaicedo** [comment]
Awesome!

**Comment by apechimp** [comment]
@JuanCaicedo, would you like to give this talk 12/2?

**Comment by JuanCaicedo** [comment]
@apechimp Yeah, I'd love to!

**Comment by apechimp** [comment]
Awesome! Thanks! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).

**Comment by JuanCaicedo** [comment]
@apechimp Do you need anything from me before Wednesday?

**Comment by apechimp** [comment]
@JuanCaicedo Was about to send you an email :wink: If there's anything you want me to say when I introduce you, let me know. See you Wednesday!
