### ISSUE TITLE
Getting Comfortable Being Uncomfortable - Lessons Learned One Year After the Nashville Software School

### ISSUE THREAD

**Issue by AimeeKnight** [charmCityJs/talks#4]
Your name: Aimee Knight

Your idea: Present my Nodevember talk (see below)

Title: Getting Comfortable Being Uncomfortable - Lessons Learned One Year After the Nashville Software School 

Description: There's no denying that engineers are in high demand. Bootcamps are popping up everywhere, and while they're churning out highly motivated juniors, often it's seniors that companies are really after. So how do we bridge this gap together? On the surface it often looks like we've 'naturally' developed into our current roles. And, as we progress it's incredibly easy to forget what it was like being new. Rest assured however, for most the journey has been filled with a whole lot of grit, determination, and discipline. In this talk, we'll discuss lessons learned one year after going from a bootcamp grad, to a full time, full stack JavaScript developer. Plan to walk away empowered, and with renewed passion for the incredible industry we're all a part of!.

Approx length: 25 minutes (can be flexible here)

Month(s) available: October (Prefer November) and there after.

**Comment by latazzajones** [comment]
Hey Aimee. Are you still willing to give this talk in November?

**Comment by AimeeKnight** [comment]
Yep. Sounds good! :+1:

**Comment by rayners** [comment]
Yay! :shipit:

**Comment by AimeeKnight** [comment]
:smile:
