### ISSUE TITLE
meteor.js/d3/react dashboards talk

### ISSUE THREAD

**Issue by bgrayburn** [charmCityJs/talks#40]
Your name: Brian Rayburn

Your idea: Meteor.js dashboards! I've been working on real-time dashboards using Meteor.js, D3 and React. [Here's](http://dashboarder.meteor.com/) a demo of the Meteor.js part that I've released on Github. It'd be great to first walk everyone through what Meteor is (5min), then explain the dashboards (5min) then start to build a new dashboard page (5min).

Approx length: 15min, could be trimmed to 10 by dropping the live code part

**Comment by jasonrhodes** [comment]
This format sounds great, we're taking a short break from framework talks but we'll try to get this scheduled sometime this fall/winter for sure. Thanks for submitting! (I'm going to go ahead and close the other metor talk proposal as we clean up this issue queue and aim for having everyone just have one talk submission in the queue.)

**Comment by bgrayburn** [comment]
Awesome, yeah I made a duplicate after I noticed the issue format change.
Thanks for eliminating the duplicate. Let me know whe  there is a slot
available and you guys are looking for another framework talk.  Looking
forward to it!

This format sounds great, we're taking a short break from framework talks
but we'll try to get this scheduled sometime this fall/winter for sure.
Thanks for submitting! (I'm going to go ahead and close the other metor
talk proposal as we clean up this issue queue and aim for having everyone
just have one talk submission in the queue.)

—
Reply to this email directly or view it on GitHub
<https://github.com/charmCityJs/talks/issues/40#issuecomment-139237145>.

**Comment by apechimp** [comment]
@bgrayburn, would you like to give this talk at our 12/2 meetup? One caveat is that our meetup has been a little framework deep-dive heavy as of late, so if possible, try to make the focus of your talk the of story developing the dashboards and allow meteor to play a supporting role.

**Comment by bgrayburn** [comment]
@apechimp Whoops! had a draft saved in my email. 12/2 sounds great, and I'll focus on the data/viz aspects utilizing tools that js developers will be familiar with rather than diving deep into meteor or other tools. Thanks for the opportunity!

**Comment by apechimp** [comment]
Awesome! Thanks! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).
