### ISSUE TITLE
My Ludum Dare JS game

### ISSUE THREAD

**Issue by kiloliter** [charmCityJs/talks#41]
Your name: Eric

Last weekend was Ludum Dare game competition, a 48 hour internet game creation competition. It happens three times a year, and this time, about 2700 games were made. I spent the weekend making a game, completely in Javascript, and I'd like to talk about what I did.

Approx length: 5 minutes?

**Comment by apechimp** [comment]
Hi, @kiloliter, this sounds really cool! Would you be willing to give this talk at our 12/2 meetup?

**Comment by apechimp** [comment]
@kiloliter, any chance you'd be available for our 12/2 meetup?

**Comment by kiloliter** [comment]
Sure, I could do that.

**Comment by apechimp** [comment]
Awesome! Thanks! I'll bug you directly a week or so beforehand. Let me know if you need anything via this thread or [:sparkles: slack :sparkles:](http://charmcityjs.herokuapp.com/).

**Comment by apechimp** [comment]
@kiloliter, is there anything you'd like me to say when I introduce you? or anything else you need from me? Regardless, see you Wednesday!

**Comment by kiloliter** [comment]
I think I should be fine. Thanks.

**Comment by kiloliter** [comment]
Here's the link to my game, that you requested:

http://coconut.xen.prgmr.com/bw/ludumdare2015/
