### ISSUE TITLE
Documentation Generator

### ISSUE THREAD

**Issue by easilyBaffled** [charmCityJs/talks#42]
Your name: Dan Michaelis

Your idea: Every front-end documentation generators up until now have required a lot of extra effort to create. The text strings and labels clutter the source files, and there is no good system of accountability to maintain them. Until now we have gone without any documentation because of that extra effort, but I have created a generators that uses our Jasmine tests to create the docs. This would be a short talk(5 min.) about the reasoning behind it and then a demo(5 min.) of what it can do and how others can use it.  

Approx length: 10 minutes

Month(s) available: October

**Comment by Oladele** [comment]
Great talk idea. I'd love to hear it whenever it gets scheduled. Cheers

**Comment by jasonrhodes** [comment]
I know it's been a while... @easilyBaffled are you still available to give this talk at a future meetup or did I hear correctly that you're no longer in the Baltimore area?

**Comment by easilyBaffled** [comment]
Yeah, I'm on the West Coast now.

**Comment by jasonrhodes** [comment]
Aw snap, sorry we didn't get you in before you left. Best of luck out west, and if you're near Sacramento or LA or SF or Portland or Seattle etc hope you get a chance to check out the awesome JS communities out that way!
