### ISSUE TITLE
Visualizing Web Apps in 3D

### ISSUE THREAD

**Issue by Oladele** [charmCityJs/talks#43]
Your name: Ola Adedoyin

Your idea: I'd like to talk about how we can go beyond 2D sticks and clouds drawings of (web) apps. In my talk I'll show how even a *PRODUCTION* version of the oft-maligned todo app is a fairly complex system involving people, processes, infrastructure, that goes way beyond the stereotypical idea of (web) apps as "just server/client code" (albeit made up of the latest-greatest-omnipotent frameworks). My talk will involve 3D models of our code and the overall "system" that makes up our sample app. Using 3D modeling, we'll get the benefit of intuitive appreciation, by both devs and non-devs (yes, its possible) of scale and complexity. Plus...3D is just cool.

Approx length: 20 minutes

**Comment by latazzajones** [comment]
Hi Ola! I took over curating this month :) 

Would you be willing to give this talk on November 4th? It's such a great talk I'm really eager to hear it again and I think the JS community will super dig it. 

Side note - @rayners BEWD class will probably be attending. So the audience will be super diverse in knowledge/skill-set.

**Comment by Oladele** [comment]
Hey Tash, Happy to do it on Nov 4th.  Sounds like a great audience. Also, happy to trim it. Perhaps @rayners and I could collaborate to taylor the 15min abridged version exactly to the audience/time-slot? Of course, I'm happy to use my discretion and cut to 15min (or any other length).
