### ISSUE TITLE
Git: Commands you don't know but should

### ISSUE THREAD

**Issue by mgold** [charmCityJs/talks#44]
I already gave a talk (#12) but Tasha requested that I submit this after giving this talk at B'more on Rails. The talk is/would be entirely live coding at the command line. At BoR, I spent 5-10 minutes on the basics of commits, branches, and pull requests. I can also target a more advanced audience, adding more advanced commands that are still useful on occasion.

I'd like to say it's a 15 minute talk, but at BoR it ran about 25 minutes with questions.

**Comment by jasonrhodes** [comment]
Hey @mgold we've nixed the live Q&A section for talks so without that, do you think we can keep this to 10-15 minutes? I like the idea of keeping it pretty basic, with maybe just a couple of advanced tips to close out. If that works, are you available to do it for April? Let me know ASAP! :)

**Comment by mgold** [comment]
Yeah, I hadn't really planned on doing Q&A the last time and it just kind of happened. Here's what I'm thinking: five minutes of "here is the basic value proposition of git: stage, commit, checkout, push, pull", five minutes of "seeing: status, log, show, diff, show" and five minutes of "advanced: reset, merge, rebase, reflog". I'll try to run through things and see if the timing comes close to working.
