### ISSUE TITLE
Using Splint.js to refactor jQuery messes

### ISSUE THREAD

**Issue by jboverfelt** [charmCityJs/talks#47]
Your name: Justin Overfelt

Your idea: For when you can't throw away that morass of jQuery code, there's Splint.js! Splint.js is an open source library specifically designed to incrementally improve jQuery projects which are "light on architecture". It makes use of reactive programming constructs to eliminate global state and callback hell. This talk will use examples similar to those presented in [this blog post](http://adzerk.com/blog/2015/06/splint-functional-first-aid-jquery/) to show how Splint can be used to rescue your data from the DOM. 

Approx length: 15 minutes

**Comment by jasonrhodes** [comment]
Hey @jboverfelt are you still interested/available for giving this talk?

**Comment by jboverfelt** [comment]
Sure! Would this be for February or March?

**Comment by jasonrhodes** [comment]
Feb if that works?

**Comment by jboverfelt** [comment]
Yeah I can probably get it together by then. I'm assuming it's on 2/1? If so, could I go first?

**Comment by jboverfelt** [comment]
Something has come up and I can't do 2/1 if that's the date. I can do March though

**Comment by jasonrhodes** [comment]
Aw ok, Feb 1 was what we were shooting for, yes. Let me know if that changes!

**Comment by jasonrhodes** [comment]
@jboverfelt how are you feeling for March?

**Comment by jboverfelt** [comment]
It turns out Wednesdays are not going to work until after March 15. April should work though, I swear!!

**Comment by clickclickonsal** [comment]
Cool, we'll check back with you next month then. 😄

**Comment by jboverfelt** [comment]
I can definitely do this in April - I've RSVP'ed for the event.

**Comment by clickclickonsal** [comment]
Awesome I'll book you for April! 👍

**Comment by clickclickonsal** [comment]
Hey @jboverfelt are you on our slack by any chance? If your are whats your slack handle? If not you can signup here -> http://charmcityjs.herokuapp.com/
We like to invite our upcoming speakers to our private #greenroom channel to help prepare or answers questions before our meetup. :-)

**Comment by jboverfelt** [comment]
Yep I'm on there - handle is jboverfelt

**Comment by clickclickonsal** [comment]
Thanks for giving this talk @jboverfelt !
