### ISSUE TITLE
Analytics.js for single-page web apps

### ISSUE THREAD

**Issue by brigittewarner** [charmCityJs/talks#48]
Your name: Brigitte Warner

Your idea: Using Analytics.js to integrate Segment.io, Mixpanel, and Google Analytics with single-page web apps

Approx length: 5 min

Month(s) available: January-March

**Comment by latazzajones** [comment]
:+1: This would be great!

**Comment by jasonrhodes** [comment]
yesssssss yes yes yes yes yesssssss

**Comment by rayners** [comment]
:+1:
