### ISSUE TITLE
Native Applications with Electron

### ISSUE THREAD

**Issue by willbarrett** [charmCityJs/talks#49]
Your name: Will Barrett

Your idea: I was part of developing http://www.sqwiggle.com and http://speak.io. Speak used NW.js for a native application on Mac, and Speak.io used Electron for a native app on Windows, Mac, and Linux. I'd like to give a walkthrough of Electron, a demo of a simple sample application that shows some of the power of the tool, and talk a little bit about why we moved from NW.js to Electron.

Related to #34 

Approx length: 10 to 15 minutes? Definitely less than 20.

**Comment by rayners** [comment]
:+1:

**Comment by paultyng** [comment]
:+1: as well

**Comment by cgarvis** [comment]
:+1:

**Comment by jasonrhodes** [comment]
hey @willbarrett are you available to do the 10-ish minute version of this talk for april?

**Comment by willbarrett** [comment]
Hey @jasonrhodes - I actually moved to San Francisco about a month ago, so sorry to say I won't be able to do it. It looks like @jgaskins could take up the mantle though!

**Comment by jasonrhodes** [comment]
Aww too bad, lost another to the west coast! Best of luck :)
