### ISSUE TITLE
Bower Power - Supercharging Front-End Maintainability

### ISSUE THREAD

**Issue by ecarlisle** [charmCityJs/talks#50]
**Name:** Eric Carlisle

## Bower Power - Supercharging Front-End Maintainability.

I recently gave this [presentation](http://sched.co/3oVw) at CSS Dev Conf. It's an introduction to Bower and usage with the command line, API, plugins, as well as automation with Gulp or Grunt.

 - [Slideshare Deck](http://www.slideshare.net/ericcarlisle/bower-power-54549427)
 - [Github Repository](https://github.com/ecarlisle/bower-power)

The presentation has much to do with "here's how to use it," but also includes rationale of why you may choose to use it. We can explore questions like "Why use multiple dependency managers?" (e.g. NPM and Bower).

## Approx length
I could easily do 20 minutes of rich content with this one, but could summarize it down to 15 or 10 if that's preferable.

Thanks!

Eric

**Comment by ecarlisle** [comment]
I've stopped using Bower and use other tools now.
Bower's a great tool, but I'd rather speak on other topics.

**Comment by esauter5** [comment]
Would you say your interest in Bower has gone sour? :trollface:

**Comment by ecarlisle** [comment]
Ha, I wouldn't go that far! It's really a great tool and there's two reasons I used it in addition to NPM for a long time:
1. **Flat Dependency Tree:** Not only was Bower easier to sort through than the thousands of files and folders in *npm_modules*, but the flat tree put the oneness on the developer for good version management and including what you need.  Now NPM has a flat dependency tree. Its still harder to sort through, but the oneness is still there.
2. **Front-End Abstraction:** It used to be good to keep all the client-side tools in one place and leave all other Node dependencies elsewhere. Now, that isn't the case the moment you start wanting "require" in front-end static assets.

Hey, that's a lightning talk right there. ;-)
