### ISSUE TITLE
Interacting with the physical world through software (Node.js and WebSockets)

### ISSUE THREAD

**Issue by cmstone** [charmCityJs/talks#51]
Your name: Chris Stone

Your idea: I bought a traffic light (like you see driving around) from Ebay and hooked it up to the Internet.  Using an Arduino and Raspberry Pi, we can control the state of the lights, flash them, turn them on, turn them off, etc..

We'll talk about the the role of the Arduino and Raspberry Pi in this setup along with checking out how we use Node.js and WebSockets to handle the communication between clients and their requests with the traffic light.  

The traffic light will come along for the ride, demoing and playing around.

Approx length: 20

**Comment by jasonrhodes** [comment]
Hey d00d this sounds great, can you do this for the Feb 2/3 event?

**Comment by cmstone** [comment]
Sure can!

**Comment by jasonrhodes** [comment]
Awesome!! We're gonna give it a shot with 4 talks for the first time so if you can keep it on the 15-20 minute side of things, that'd be sweet (ie don't go over 20 like I did in my supposed-to-be-10-minute npm talk last week :sob: ) -- i'm going to be MC-ing so i'll be in the back with countdown cues :)
