### ISSUE TITLE
Introduction and Exploration of the Web Audio API

### ISSUE THREAD

**Issue by abbernie** [charmCityJs/talks#52]
Your name: Andrew Bernstein

Your idea: I'd like to talk about the Web Audio API, a Javascript API that makes it possible to synthesize, spatialize, manipulate, and visualize sound in the browser. I'll give a brief introduction to Web Audio followed by a demonstration of some more advanced features, and discuss the possibilities for art, data sonification, user interface design, and game audio.

Approx length: 15min

**Comment by jasonrhodes** [comment]
Hey there, this talk sounds awesome—are you available to give this for our Feb 2/3 meetup?

**Comment by abbernie** [comment]
Hello, thanks! I sure am.

**Comment by jasonrhodes** [comment]
Awesome! We're going with 4 talks for the first time ever so if you can keep yours on the "10-15 minute" side, that'd be great (at the very least not going over 15 will be important, but I'll be MC-ing so I'll be in the back with countdown cues)

**Comment by abbernie** [comment]
Yes! 10-15 min is fine. Looking forward to it!
