### ISSUE TITLE
A Tale of Two Asterisks (ES2015, TC39, Babel, etc.)

### ISSUE THREAD

**Issue by paultyng** [charmCityJs/talks#53]
**Your name:** Paul Tyng

**Your idea:** ES2015, TC39, Babel, etc.  Talk about the new process from TC39 for features going forward.

Was thinking of using the exponentiation operator as an example of how the process works:

https://bocoup.com/weblog/designing-an-exponentiation-operator-for-javascript

**Approx length:** 15mins?

**Comment by paultyng** [comment]
Should cover #11

**Comment by apechimp** [comment]
@paultyng can you give this talk at the March meetup?

**Comment by paultyng** [comment]
I can't really for March, but I could do April.

**Comment by apechimp** [comment]
Ahh, bummer. @Oladele, putting this on your radar for April.

**Comment by jasonrhodes** [comment]
@paultyng still up for april?

**Comment by paultyng** [comment]
Sure, I can do that.

**Comment by paultyng** [comment]
This is ending up less about actual ES2015 features and more about ES* process and TC39 and the history.  Is that cool?

**Comment by jasonrhodes** [comment]
Perfect! There's a 5 min talk on destructuring that I'll put right after yours, should be a good complement

**Comment by jasonrhodes** [comment]
Just try to watch your time—I know when I go into history and story it gets super fun and I end up with 3x the content! ;)

**Comment by paultyng** [comment]
@jasonrhodes sorry about this, but had a business trip come up this week, so will be out of town unfortunately, I was looking forward to it.

**Comment by jasonrhodes** [comment]
Do you want to try this again for May 4th?

**Comment by paultyng** [comment]
Hey, I'd love to but May 4th is Under Armour's big work party thing.

**Comment by esauter5** [comment]
Let's give this another go. @paultyng how does June 1 sounds for you?

**Comment by paultyng** [comment]
Yeah I can do that.
