### ISSUE TITLE
Electron: JS on the Desktop

### ISSUE THREAD

**Issue by mockaroo** [charmCityJs/talks#54]
Want to write a desktop app using node.js and web tech?  GitHub's Electron is a chromium-based runtime that provides the foundation for the Atom editor as well as Microsoft's Visual Studio Code.  Electron allows you to package your own cross-platform JavaScript desktop apps.   Need to write a headless utility or CLI?  JXCore may be the answer.  With either solution, your users won't have to install any dependencies!  This talk will introduce and compare both with some quick live coding.  I'll also talk about some real world apps that I've deployed with each.

**Comment by jgaskins** [comment]
We've already got an Electron submission in #49 with a few thumbs up, but that proposal doesn't mention JXCore. If that proposal is accepted, would you be interested in building on it with a JXCore-specific talk?

**Comment by mockaroo** [comment]
Sure, I think both talks would be great on the same night.  I could certainly split out JXCore into a separate talk, and if it followed the Electron talk it would be easy to show the different use cases for one vs the other.

**Comment by jgaskins** [comment]
My thoughts exactly. :-)

@jasonrhodes Thoughts/opinions?

**Comment by jasonrhodes** [comment]
That sounds like a great idea to me—might not get this booked for Feb but maybe March? Stay tuned!

**Comment by jasonrhodes** [comment]
If we cut out the Electron part of this talk, it'd be nice to aim for about 10-15 min on the JXCore stuff -- that sound do-able @mockaroo ?

**Comment by mockaroo** [comment]
Sure, 10-15 minutes will be fine.

**Comment by jasonrhodes** [comment]
hey mark, you available to give the 10-ish minute JXCore version of this for april? (sorry it's taken so long to get you scheduled!!)

**Comment by jasonrhodes** [comment]
Hey based on a quick talk in charmcityjs slack, we're gonna change this to be a 10-minute intro to Electron since JXCore is "somewhat irrelevant now" and "there is headless electron and better support for js on mobile devices".

To keep it focused for our crowd, I personally wouldn't even mention JXCore at this point. I'll update the title here.

**Comment by jasonrhodes** [comment]
Thanks, this was great! :)
