### ISSUE TITLE
Character Animtaions and Posabe Dinosaurs with create.js

### ISSUE THREAD

**Issue by FlashMapper** [charmCityJs/talks#55]
Your name: James Miller

Your idea: I have an outline for a talk about create.js. It involves samples I have made with some animated characters, an interactive celestial sphere, and posable dinosaur figures for an iOS app I released last year.

Approx length: 15-20

**Comment by jasonrhodes** [comment]
I updated your talk title for you--feel free to rename to anything.

**Comment by apechimp** [comment]
@FlashMapper do you want to give this at the March meetup?

**Comment by jasonrhodes** [comment]
Let us know if you still want to give this talk and we can re-open it.
