### ISSUE TITLE
Teaching JavaScript as a Foreign Language

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#56]
Your name: Chris Uehlinger

Your idea: After college, I spent a year teaching programming to 11th graders in Thailand. This turned out to be extremely difficult: I had to teach people with no experience how to program (challenging enough on its own!) while explaining things in a language they were only partially familiar with. It was trial-by-fire: I had to re-evaluate how I taught and quickly hone in on techniques that worked, or I would lose my students' interest within the first 5 minutes of class.

In the end, this experience shaped how I think about teaching programming (including mentoring, writing documentation, etc.), but I feel that many of the lessons I learned can be applied to teaching any topic. In my talk, I'll cover some of the problems I faced, how I was able to solve them, and how you can apply these solutions when teaching people in your everyday life.

Approx length: 20 minutes

**Comment by apechimp** [comment]
@chrisuehlinger would you like to give this talk at the March meetup?

**Comment by apechimp** [comment]
@chrisuehlinger Please let me know if you're able to give the talk at that March meetup.
