### ISSUE TITLE
Intro to KrakenJS

### ISSUE THREAD

**Issue by starmer** [charmCityJs/talks#58]
Your name: James Starmer

Your idea: I'd like to talk about Kraken, PayPal's open source extension to the Express Node.js framework.

Approx length: 20 minutes

**Comment by esauter5** [comment]
@starmer Any interest in giving this talk at the Wednesday, Aug 3 meetup?

**Comment by esauter5** [comment]
Closing this as we have not heard back from you. Please reopen if you are still interested in giving this talk @starmer!
