### ISSUE TITLE
A React Native Retrospective

### ISSUE THREAD

**Issue by esauter5** [charmCityJs/talks#59]
I'm giving a lightning talk at React Conf in February and a couple of the charmCityJS organizers recommended I give a test run at February's meetup.

React Native has been out for almost a year. It represents a big change in the way developers (especially JavaScript developers) can develop mobile apps. This short 5 minute lightning talk will look back at the year since RN was open sourced. Because we usually tend to focus on the awesome parts of React Native, this talk focuses specifically on some of the shortcomings and pain points of it in hopes of highlighting how things have evolved in the last year (for the better), how things are continuing to evolve, and some suggestions for the future.

This talk is pretty React Native specific, but many of the conclusions drawn from it can apply to other large and "bleeding edge" open source projects.

**Comment by jasonrhodes** [comment]
Got you penned in for Feb, looking forward to it!

**Comment by esauter5** [comment]
:+1:
