### ISSUE TITLE
How to write multi-threaded node.js

### ISSUE THREAD

**Issue by apechimp** [charmCityJs/talks#6]
How to use the node native layer and why you would want to do that. Probably start with an app that does something stupidly CPU intense (like add all the integers) over http and show how it fails to respond to requests while it's working, then put the stupidly CPU intense thing onto the thread pool via the node native layer and watch requests get processed while slamming the CPU.

**Approx length:** 15 min

**Months available:** May, July

**Comment by jasonrhodes** [comment]
Hey @apechimp thanks for submitting. We're waiting to hear back from a potential out of town speaker for May but we should know in a few days. If they can't make it, we'd love to have you for May 6, otherwise July will be great, too. We'll be in touch soon :)

**Comment by apechimp** [comment]
Sounds good! I feel like this topic may be a little niche, so I may change topics if someone makes a request for something I have a competency in.

**Comment by AimeeKnight** [comment]
@apechimp We'd like to book you for July 1st! Does that still work for you?

**Comment by apechimp** [comment]
Yup!

**Comment by AimeeKnight** [comment]
Sounds good. I'm looking forward to it! 

We'll let you know the order when the event gets closer. Please let me know if you have any questions before then.

**Comment by apechimp** [comment]
:+1:
