### ISSUE TITLE
Leveling Up: ES6 Destructuring Tips/Tricks

### ISSUE THREAD

**Issue by cgarvis** [charmCityJs/talks#61]
Name: Chris Garvis

Idea: Talk about the new ES6 destructuring syntax and how it can influence the way we wrote JS code.

Length: 5 mins (Lighting Talk)

**Comment by jasonrhodes** [comment]
This is a great idea—are you able to do this for Feb?

**Comment by cgarvis** [comment]
I sure can.

**Comment by cgarvis** [comment]
@jasonrhodes something came up today, and i'm not going to be able to make it tonight.  Can we push to March?

**Comment by jasonrhodes** [comment]
Hey @cgarvis -- we don't reschedule on the fly but we'll put the talk back on the log and consider it with the rest for future events.

**Comment by cgarvis** [comment]
Fair enough.  Sorry about minute change.

**Comment by apechimp** [comment]
@cgarvis, can you give this talk at the March meetup?

**Comment by cgarvis** [comment]
Just seeing this.  Maybe next time.

**Comment by jasonrhodes** [comment]
@cgarvis if you see this in the next few days, let me know if you'd like to do this for april?

**Comment by cgarvis** [comment]
Yup.  I can do it.

**Comment by jasonrhodes** [comment]
Great! Come a little early and you can test out your projector hookup. Also, the lighter your slide backgrounds are, the better you'll be able to see the crowd. :)
