### ISSUE TITLE
Performance and VM Optimizations

### ISSUE THREAD

**Issue by jgaskins** [charmCityJs/talks#62]
**Your name:** Jamie Gaskins

**Your idea:** Most JavaScript VMs have various levels of optimization they can perform on your code, from a simple AST transform to dead-code removal to native-code compilation. This can make your code blazing fast, but there are certain operations the VM cannot optimize. In this talk, we'll explore those and learn a few ways to avoid them.

**Approx length:** Probably going to need every bit of 20 minutes

**Comment by apechimp** [comment]
@jgaskins would you like to give this talk at the March meetup?

**Comment by jgaskins** [comment]
@apechimp Sure, that'd be good.

**Comment by apechimp** [comment]
Excellent! You're on the schedule! Be sure to keep it to 20 minutes :wink:
