### ISSUE TITLE
React/Redux At Scale

### ISSUE THREAD

**Issue by donabrams** [charmCityJs/talks#63]
Your name: Don Abrams

Your idea: At Craftsy, we decided to rewrite our entire multi-page isomorphic/SPA with React/Redux (including iOS/mobile). I'll give an overview of the challenges we hit, solutions we invented or discovered, and what unsolved problems remain (all w/ code samples).

Approx length: 15-20 min

**Comment by jasonrhodes** [comment]
Hey @donabrams can you a) keep this to 15 min max and b) give this next wed may 4th?

**Comment by donabrams** [comment]
I could do the 4th. After mapped out what I'd like to talk about, rough estimate is 29 min (so I def lied). Want to help me cut stuff out that's less interesting/more obvious?

Rough plan:

Craftsy constraints/conway (2 min)
Redux overview (3 min)
Smart vs. dumb components (2 min)
Bad Parent ideal (1 min)
Monorepo + Structuring reducers, actions (3 min)
Immutable state (1 min)
Sharing code via React Native (2 min)

CSS Encapsulation (2 min)
Display-if (1 min)
Custom ESLint rules (1 min)

Custom build - browserify based (1 min)
Moving/renaming packages (1 min)
Cartridges/composable routing (1 min)
Style library (2 min)
Test strategy (1 min)

Wishlist
Flow (1 min)
Inline tests (1 min)
Immutable destructuring (1 min)
CSPs/animations (2 min)

Total: 29 min

**Comment by esauter5** [comment]
There's been a few React talks lately, but not much specifically focused on Redux. I think it'd be great if you emphasized that. Based on the first section of topics you listed that are redux-focused, that would put you at about 14 minutes.

**Comment by donabrams** [comment]
sounds good to me

**Comment by jasonrhodes** [comment]
@esauter5++, sounds great!

**Comment by esauter5** [comment]
Thanks again for giving this @donabrams!
