### ISSUE TITLE
Debugging Ember With Empathy

### ISSUE THREAD

**Issue by vaidehijoshi** [charmCityJs/talks#64]
Your name: Vaidehi Joshi

Your idea: Denial, anger, bargaining, depression, acceptance. But I don't mean the five stages of grief — I'm talking about the five stages of debugging your first Ember app! Learning how to navigate the building blocks of Ember can be difficult, but the even trickier thing is knowing where to start debugging while you're still learning the framework. One approach that I use is to put myself into my code's shoes. In this talk, we'll connect with our objects to understand what's going on under the hood. Let's jump over some common first-time Ember hurdles together by debugging our code — with empathy.

Approx length: This talk is actually slotted to be 30 minutes (I'll be giving it at EmberConf in late March), but I can do a 20 minute abridged version for Charm City JS!

**Comment by jgaskins** [comment]
:+1: from me. Back when I used Ember, I remember getting lost in some of its magic — in both good and bad ways. :-) I'd love to see how I could've handled those debugging sessions better.

**Comment by apechimp** [comment]
@vaidehijoshi I hear you able to do this in March. Let me know if I'm incorrect.

**Comment by vaidehijoshi** [comment]
👍 Definitely down for March!
