### ISSUE TITLE
Bird's eye view of mobile advertising, part of what we do at AOL

### ISSUE THREAD

**Issue by amirmograbi** [charmCityJs/talks#65]
Name: Amir Mograbi

Idea: Since mobile advertising is pretty big in Baltimore, employing a lot of local talent. Previously with MillennialMedia and now AOL. I wanted to give a quick overview of what actually happens behind the scenes of the portion that I'm familiar with. From an Engineer's perspective and perhaps how app developers can use our services to monetize their apps. Maybe throw around some industry jargons.
The purpose is to expose the topic to developers and create interest.

Approx length: I want to keep it under 10 minutes.

**Comment by rayners** [comment]
:+1: (though I'm biased)

**Comment by jasonrhodes** [comment]
Are you able to give this on May 4th?

**Comment by amirmograbi** [comment]
@jasonrhodes yes, I'd be able to do it on May 4th, Thank!

**Comment by jasonrhodes** [comment]
Perfect!

**Comment by esauter5** [comment]
Thanks for the talk @amirmograbi!
