### ISSUE TITLE
Building a site with Serverless Framework and a static React Frontend

### ISSUE THREAD

**Issue by cphoover** [charmCityJs/talks#67]
**Your name:** 
Charlie Hoover (Software Engineer, Under Armour)

**Your talk idea, described briefly:**
Brief intro to Serverless Framework (serverless.com) / AWS Lambda / AWS API Gateway. Walk through of a relatively simple site that aggregates github statistics, with AWS Lambda/Serverless Framework, ElasticSearch, and a Static React Frontend, using ES6 syntax (babel for transpilation).

**Approx length: (must be less than 20 minutes to be considered*):**
15 minutes

**Comment by esauter5** [comment]
:+1: for this. I've been wanting to learn more about Serverless

**Comment by skratchdot** [comment]
same here. should be a good talk.

**Comment by esauter5** [comment]
@cphoover Would you be able to give this talk on June 1?

**Comment by esauter5** [comment]
I'm closing this since we haven't heard back from you, @cphoover. We'd really love to have this talk, so if you would like to give it in the future, please open a new issue.
