### ISSUE TITLE
The Magic of Meteor

### ISSUE THREAD

**Issue by merlinpatt** [charmCityJs/talks#68]
**Your name:** Merlin

**Your talk idea, described briefly:** Talk about what Meteor can do and why everyone should use it

**Approx length: (must be less than 20 minutes to be considered*):** 10 minutes

**Comment by jasonrhodes** [comment]
Hey! Are you able to give this next wed may 4th, @merlinpatt?

**Comment by merlinpatt** [comment]
Yeah I can give the talk then :-)

**Comment by jasonrhodes** [comment]
Sounds good. Thanks!

**Comment by esauter5** [comment]
Great job on this @merlinpatt!
