### ISSUE TITLE
SMPL & Sweet JS

### ISSUE THREAD

**Issue by jasuperior** [charmCityJs/talks#69]
**Jamel Cole** 

**I will be presenting a new project i'm working on called [SMPL.js](http://ThatSm.pl), which i'm calling "The Compiler for the Transpiling Age". My talk will center around the importance of transpiling and progressive enhancement, and how SMPL helps you accomplish that.**

**10 mins approx.**

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
@jasuperior Would you be available to give this talk next Wednesday (June 1)?

**Comment by jasonrhodes** [comment]
@jasuperior are you still interested in doing this talk?

**Comment by esauter5** [comment]
@jasuperior I'm closing this issue since we haven't heard back from you. If you'd like to give this in the future, please do not hesitate to open a new issue.
