### ISSUE TITLE
Web development got you down? GET MEAN!

### ISSUE THREAD

**Issue by mgd216** [charmCityJs/talks#70]
Matt Duvall, Sr. Software Engineer
Owner Co-Founder of Atlasient

The MEAN stack, JavaScript from database to client is awesome!

15 min

Talk will cover the following:
- MEAN Stack Overview
- Lessons Learned with Angular
- Cool additions to MEAN
  - Mongoose Deep Populate
  - Express Restify Mongoose
  - Angular Schema Formly

**Comment by jasonrhodes** [comment]
@mgd216 just checking in, are you still interested/available to give this? We're booked up for Oct but want to make sure so we can consider it for Nov/Dec, or close it if not. Thanks!

**Comment by mgd216** [comment]
Greetings,

Absolutely, would love to still talk about MEAN Stack if possible.  Let me
know which month you were thinking, thanks.

Matt

**Comment by clickclickonsal** [comment]
hey @mgd216, are you available December 7th to give this talk?

**Comment by mgd216** [comment]
Greetings,

Yes I am available to give the talk on 12/7/16.  If there are any
guidelines I need to follow, please let me know.  Look forward to meeting
everyone, thanks.

Matt

**Comment by clickclickonsal** [comment]
Awesome, I have you scheduled! Only guideline really is to just keep the talk under 20 mins. 😄

**Comment by mgd216** [comment]
Not a problem, again look forward to meeting the group.

**Comment by clickclickonsal** [comment]
@mgd216 I don't see you on our slack team for CCJS, if you don't mind join our slack group and I can invite you to our channel were we do any prep talk needed.
You can join via our [website](http://charmcityjs.com/), and click on the slack button and then enter your email for an invite. 😄

**Comment by esauter5** [comment]
Thanks again @mgd216. It was great having you speak!
