### ISSUE TITLE
Interactive Presentations: Created using Node, Reveal & Socket.IO

### ISSUE THREAD

**Issue by RyanSpahn** [charmCityJs/talks#71]
**Your name:** 
Ryan Spahn

**Your talk idea, described briefly:**
My fellow tech partner (lives in Philly) and I have created a Interactive Powerpoint app http://BLASTeo.com. The audience uses their devices to follow along, vote (yes or no and or multiple choice questions) and play audio in sync.  Depending on how the users uses it ... it can be used to create 4D experiences, for sing alongs with lyrics to teaching/quizzing in classrooms to whatever the users comes up with.

We have been working on it for a year and I would enjoy the opportunity to talk about the tech we used and test it out with the audience.

**Approx length: (must be less than 20 minutes to be considered*):**
5 to 10 minutes

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
@RyanSpahn Hey Ryan, we'd love to have you speak tomorrow if you're available, especially now that Nater may not be available. Let me know!
