### ISSUE TITLE
Life API: Using personal data for life gains and well being

### ISSUE THREAD

**Issue by janecakemaster** [charmCityJs/talks#72]
jane kim

Usually keeping track of personal data involves a lot of unused mobile apps and expensive trackers. What if you could just... code your own? Using Hoodie, I created an app that helps me track anything and use continuous integration to notify myself if I'm adulting properly or not.

can be any length -- i'm comfortable with 15 minutes

**Comment by jasonrhodes** [comment]
15 minutes sounds great, see you here in July! (We'll be in touch about transportation etc)

**Comment by jasonrhodes** [comment]
^5 thanks for coming downnnn
