### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by nickhudkins** [charmCityJs/talks#75]
**Your name:** 
Nick Hudkins

**Your talk idea, described briefly:**

I am going to show people GraphQL and tell them why it will change their life.

**Approx length: (must be less than 20 minutes to be considered*):**

5-10 Minutes. I do not plan on "pitting" it against REST, though I may say something like "OOF, imagine trying to fetch that data from a REST endpoint"

**Comment by jasonrhodes** [comment]
I guess this is getting pretty "hawt" right now so let's do this, good for July? And can you list all of the rest of the potential phrases you _might_ say, roughly? k thx

**Comment by nickhudkins** [comment]
July works for me!

I will work on my list of OOFs.

**Comment by jasonrhodes** [comment]
Great talk, less funny than I expected.
