### ISSUE TITLE
Topic Request: Douglas Crockford Historical Impersonator

### ISSUE THREAD

**Issue by datesss** [charmCityJs/talks#76]
**Your name:** Jake

**Your talk idea, described briefly:** There are people that dress up like Ben Franklin and go to middle schools and talk about his life in the first person. Theodore Roosevelt, Mark Twain, Abe Lincoln, and many other 'important' 'founders' of US government and culture have historical impersonators. Douglas Crockford is one of the most 'important' 'founders' of ECMAScript. He's basically the patron saint of it. So I'm proposing someone maybe gets a wig and some disheveled glasses and re-enacts a Douglas Crockford youtube video, that's all.

**Comment by esauter5** [comment]
Hey @datesss, while I love this from the standpoint that it is an original idea and different from most of the talks and talk requests we get, after talking with some of the other organizers, I'm going to close this. I'm sure this could be entertaining, but poking fun at a member of the JS community would not reflect well on charmCityJS and goes against what we preach in our Code of Conduct.

Thanks for contributing and please feel free to submit other requests or even talks of your own!

**Comment by datesss** [comment]
ahhhh sorry i did not intend for this to be taken seriously!  thanks for closing 👍
