### ISSUE TITLE
Building a Music Platform (Pony.fm)

### ISSUE THREAD

**Issue by LabLayers** [charmCityJs/talks#77]
**Your name:** Victor Lourng (organizer of Philly’s Node.js meetup & TacoJS)

**Your talk idea, described briefly:** Lessons learned from building a music platform with Angular - the story behind http://pony.fm

**Approx length: (must be less than 20 minutes to be considered*):** 6 minute lightning talk (if you want me to go into technical details I can make it longer)

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

One of the side projects I’ve recently worked on is http://pony.fm - a fully-featured community fan music site with support.

I spend ~3 minutes skimming/simplifying the major features in Angular and the tech behind them: focusing on lossless uploads/downloads, filtering by metadata, user accounts, playlists, and search.

Then I'll briefly how we built a community around our site and how it became one of the counterpoints in the pony music community.

I figured since I happen to be in Baltimore and BronyCon is coming up, it wouldn’t hurt to submit a relevant talk. I have no idea how the meetup works but if slots are full for July (I can only present next week) that is totally understandable - free free to close the issue.

**Comment by jasonrhodes** [comment]
This is fantastic. I can easily work in a lightning talk -- you're in. Thanks @LabLayers ! See you next week

**Comment by jasonrhodes** [comment]
Thanks again so much for coming down and speaking! You're welcome back any time
