### ISSUE TITLE
PRY

### ISSUE THREAD

**Issue by nickhudkins** [charmCityJs/talks#78]
Nick Hudkins

Common mistake that I see is too many people putting too many eggs in the DRY basket. 

5 mins

**Comment by nickhudkins** [comment]
In lieu of this talk happening, just read this: http://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction

**Comment by esauter5** [comment]
Do you want to give this or should I close?

**Comment by nickhudkins** [comment]
I could still give this, BUT...I can't do it this upcoming one.

**Comment by esauter5** [comment]
Cool cool. I wasn't asking for this one just wasnt sure if you still were interested because of your second comment.

Does this mean you are missing a second straight meetup? Man, we might have to revoke your membership...

**Comment by jasonrhodes** [comment]
[BOOKED for NOV]

https://charmcityjs.slack.com/archives/general/p1474679850000398

**Comment by clickclickonsal** [comment]
@nickhudkins This was a great talk! I just want to say that again. This was a great talk!
