### ISSUE TITLE
PostCSS - Awesome Tech, Confusing Name

### ISSUE THREAD

**Issue by ecarlisle** [charmCityJs/talks#79]
**Your name:** 
Eric Carlisle

**Your talk idea, described briefly:**
PostCSS, despite the name, is a new approach to do CSS preprocessing with Node. It differs from traditional preprocessors like LESS and Sass in that it's not limited to a set amount of native functionality.  With available plugins (and ones you can write), the sky is the limit for CSS customization and optimization!

**Approx length: (must be less than 20 minutes to be considered*):**
5 minutes is good for a general overview & benefits
5 - 10 minutes more and I can show some examples with live code.
*(I can be flexible)*

**Comment by jasonrhodes** [comment]
Are you available to do this for October, @ecarlisle ?

**Comment by esauter5** [comment]
thanks for giving this talk @ecarlisle!
