### ISSUE TITLE
smart search boxes: typeahead.js

### ISSUE THREAD

**Issue by ChrisGuzman** [charmCityJs/talks#8]
Your name: Chris Guzman

Your idea: How to use typeahead.js to build a smart search box. Basically I want to show how to build something like the [twitter demo](https://twitter.github.io/typeahead.js/examples/). I can also go in depth about how to use multiple datasets, what actions you can take when a user selects something, or how to style the typeahead box.

Length: 10-15 minutes

Months available: whenever!

**Comment by latazzajones** [comment]
Hey Chris - Can you do May 6th? I'd like to open with you if you can keep this at 10min. 😃

**Comment by ChrisGuzman** [comment]
Yup! Can't wait.

**Comment by latazzajones** [comment]
cool - it's up! We'll announce it once I get one of Gary's talks up there to. Thanks! I think it's a great topic and I can't wait to hear about it.
