### ISSUE TITLE
Leveraging postgresql 9.5's JSON support

### ISSUE THREAD

**Issue by max-mathieu** [charmCityJs/talks#80]
**Your name:** Max Mathieu

**Your talk idea, described briefly:** Postgres 9.5 added some cool features around JSON that makes it easier to have both relational and extensible schemas, that is all good stuff for JS devs. Tips and examples included for free (including `pg` library)

**Approx length:** 5-10 minutes

**Comment by jasonrhodes** [comment]
I'm really interested in this @max-mathieu -- maybe we can get it scheduled for sometime after the holidays if that's roughly enough time between talks for you? :D

**Comment by max-mathieu** [comment]
Sure, sounds good to me, Q4 will be pretty hectic for me anyways

**Comment by max-mathieu** [comment]
@jasonrhodes hit me up if you're still interested, just need to know about a week in advance so I can manage daycare duties 👶

**Comment by jasonrhodes** [comment]
Definitely still interested, are you available for February 1?

**Comment by max-mathieu** [comment]
@jasonrhodes I'll have to bail this time, baby went to ER twice in 2 days, so we'll need a regular week next week. Let's see how things unfold for March

**Comment by jasonrhodes** [comment]
@max-mathieu you in for March?

**Comment by max-mathieu** [comment]
@jasonrhodes Unfortunately have a conflict on that night :( Do you already know the date in April so I can pencil it in in advance?

**Comment by jasonrhodes** [comment]
It's always the first wed of the month!

**Comment by clickclickonsal** [comment]
Hey @max-mathieu, how's May 3rd sound for giving this talk?

**Comment by max-mathieu** [comment]
@clickclickonsal count me in!

**Comment by clickclickonsal** [comment]
Thanks again for giving this talk @max-mathieu!

**Comment by max-mathieu** [comment]
You're very welcome @clickclickonsal 

Not sure where I should post those, but here are my slides: https://docs.google.com/presentation/d/1Vzf9P4Z6E4ZPZDVvxpN4bEV8-KzDwbQ0xeiHDDxQrgk/edit#slide=id.p
Also, https://www.postgresql.org/docs/current/static/functions-json.html is a good reference for all json(b)-specific functions
