### ISSUE TITLE
Intro to VueJS

### ISSUE THREAD

**Issue by max-mathieu** [charmCityJs/talks#81]
**Your name:** Max Mathieu

**Your talk idea, described briefly:** I decided to go with VueJS for my latest project, so I volunteer to give an intro to VueJS, maybe build a quick sample app live, and show Vue dev tools

**Approx length:** probably 15-20, I doubt anyone wants to have a 3-talk series on this topic :)

**Comment by esauter5** [comment]
Hey Max, are you available to give this talk next Wednesday, August 3? We would love to have you speak.

**Comment by max-mathieu** [comment]
Glad you like the talk idea ;)
For next Wed, I have to drive friends to Dulles that afternoon, so let me check if timings fit. I'll let you know by tonight or tomorrow morning

**Comment by esauter5** [comment]
Ok great. No rush, just let me know when you have an idea. If it helps, we don't usually start the talks until 7:30 and the last one kicks off around 8:15 - 8:30, so we could always work around your schedule if needed.

**Comment by max-mathieu** [comment]
@esauter5 Wed won't work for me, I forgot I have to baby sit the kids that night (that's going to be a busy day :/). Sorry for not being able to make it this time, you can sign me up for September for sure!

**Comment by esauter5** [comment]
No problem, @max-mathieu! We'll tentatively set you up for September and I will check back later in August.

**Comment by esauter5** [comment]
@max-mathieu Are you still good to give this talk next Wednesday (Sept 7)?

**Comment by max-mathieu** [comment]
Yup, count me in @esauter5 :)

**Comment by max-mathieu** [comment]
Thanks for allowing me to talk last night, hope this was interesting!

Github repo with the code from the demo: https://github.com/max-mathieu/charmcity-vuejs
Slides: https://docs.google.com/presentation/d/1cw_rBIU8Nbg5cxM_MHFWP4jv_7_NrdLPsNe_TtJtuhI/edit#slide=id.p
