### ISSUE TITLE
Working with ASTs: Your first Babel plugin

### ISSUE THREAD

**Issue by cgarvis** [charmCityJs/talks#82]
**Speaker:** Christopher Garvis

**Brief:** ASTs are scary but they are actually not that bad.  In this talk, I want to pull off the mask on ASTs and build a babel plugin from scratch.

**Time:** 20 min

**Comment by jasonrhodes** [comment]
Are you available to do this for October, @cgarvis ?

**Comment by jasonrhodes** [comment]
Closing your open talks for now, you re-open them @cgarvis whenever you're ready to be reconsidered for talks again! :)
