### ISSUE TITLE
Charting Like a Boss with ReactJS

### ISSUE THREAD

**Issue by kenwheeler** [charmCityJs/talks#83]
**Your name:** 
Ken Wheeler

**Your talk idea, described briefly:**
During this talk I'll speak about how to use [Victory](victory.formidable.com) to create rich, interactive charting experiences in ReactJS.

**Approx length: (must be less than 20 minutes to be considered*):**
15

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
Looking forward to this!

**Comment by esauter5** [comment]
Thanks again for this @kenwheeler! It was great having you in town.
