### ISSUE TITLE
Elegant Beauty with p5 Interactivity 

### ISSUE THREAD

**Issue by mscottnelson** [charmCityJs/talks#84]
**Your name:** 
Michael Scott-Nelson 

**Your talk idea, described briefly:**
A brief introduction to p5.js, a library for writing beautiful interactive generative art in a Java-like syntax. 

**Approx length: (must be less than 20 minutes to be considered*):**
15

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
Thanks again for giving this talk @mscottnelson. Really enjoyed all the trippy visualizations!
