### ISSUE TITLE
Keeping your npm depencencies up to date. 

### ISSUE THREAD

**Issue by jgzamora** [charmCityJs/talks#85]
**Your name:** 
Jose Zamora
**Your talk idea, described briefly:**
A overview of why to keep dependencies updated and an intro to Greenkeeper.
**Approx length: (must be less than 20 minutes to be considered*):**
10 minutes
*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
@jgzamora would you want to give this talk next Wednesday (Sept 7)?

**Comment by esauter5** [comment]
Thanks again for giving this talk, @jgzamora!
