### ISSUE TITLE
Making games with Phaser

### ISSUE THREAD

**Issue by polyakov** [charmCityJs/talks#86]
Elijah and Vadim Polyakov

Making HTML5 games is fun and easy with Phaser.  In this talk, we'll demo a game designed and built by Elijah(12) using Phaser game engine.  We then used Apache cordova to build an android app,

Approx length: 5-10

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by jasonrhodes** [comment]
Hey there @polyakov this sounds great, are you available to do this in October?

**Comment by polyakov** [comment]
Hey @jasonrhodes  - yes we can do it on the 5th.

**Comment by jasonrhodes** [comment]
Awesome, perfect! Just show up at 7 if you want to test your computer with the monitor set up, @esauter5 will be the MC that night so look for him when you arrive. Let us know if you have any other questions!

**Comment by esauter5** [comment]
@polyakov This was awesome to see! Thanks again and we hope to see the two of you at future meetups.
