### ISSUE TITLE
JSONSchema for noobz

### ISSUE THREAD

**Issue by naterkane** [charmCityJs/talks#87]
**Your name:** 
* Nater Kane

**Your talk idea, described briefly:** 
* Introduction to JSON Schema, how to author documents, why you'd want to, and how you can use them in real life

**Approx length: (must be less than 20 minutes to be considered*):** 
* I can probably keep it around 10 min

**Comment by jasonrhodes** [comment]
Hey @naterkane can you do this in October?

**Comment by naterkane** [comment]
Sure that shouldn't be a problem

- sent from my potato

**Comment by esauter5** [comment]
Thanks for giving this @naterkane!
