### ISSUE TITLE
Make Something Dumb

### ISSUE THREAD

**Issue by jasonrhodes** [charmCityJs/talks#88]
**Your name:** Jason

**Your talk idea, described briefly:** I think the best way to learn or get better at JavaScript (most things?) is to make something—anything—so… I made something dumb. I wanna show you what I made, talk about how I got past some hang-ups, and invite you to help me make it even dumber or encourage you to make your own dumb things.

**Approx length: (must be less than 20 minutes to be considered*):** 10 min

Note: Would love to do this in October so we can use my dumb thing for November...

**Comment by esauter5** [comment]
:shipit:
