### ISSUE TITLE
JS: 1 year later: Picking a stack, growing pains

### ISSUE THREAD

**Issue by kmassada** [charmCityJs/talks#89]
**Your name:** Kenneth Massada

**Your talk idea, described briefly:**
I have been learning javascript for about 1 year now, at least seriously, I want to talk about, what I've learned, what I struggled with, I want to present also parts of my project ionic+angularjs+typescript frontend and backend nodejs. How or why Typescript is key for me, why I chose angular, and a little bit what's it's like coding an api, a frontend as a true beginner. 

**Approx length: (must be less than 20 minutes to be considered*):**
10 min

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by jasonrhodes** [comment]
Sounds fantastic, and perfect for our audience!!! Can I book you for November, @kmassada ?

**Comment by kmassada** [comment]
yes @jasonrhodes  let's do this.

**Comment by jasonrhodes** [comment]
ping @kmassada just reminding you and verifying you're on for nov 2, let me know

**Comment by kmassada** [comment]
@jasonrhodes confirming for nov2 !! we are doing this!!

**Comment by clickclickonsal** [comment]
@kmassada Great talk! I enjoyed it! 😄
