### ISSUE TITLE
Working Effectively with Legacy Code

### ISSUE THREAD

**Issue by jdstafford** [charmCityJs/talks#90]
**Your name:** 

Josh Stafford

**Your talk idea, described briefly:**

This talk will cover definitions of Legacy Code and how to make meaningful changes to legacy projects without adding to the legacy-ness.  Examples from the book, "Working Effectively with Legacy Code" by Michael Feathers, as well as experience from The School of Hard [Legacy Code] Knocks (not a real place) will be leaned upon heavily.

**Approx length: (must be less than 20 minutes to be considered*):**

~7 minutes.

**Comment by oliikit** [comment]
Hey @jdstafford! We're going through old talks - would you be up for talking in September or October?

**Comment by jdstafford** [comment]
Yes! Either September or October would be great.  Just let me know which
one.

**Comment by oliikit** [comment]
Cool! Let's do September! 💪
