### ISSUE TITLE
RethinkDB: A Fresh Look

### ISSUE THREAD

**Issue by jdstafford** [charmCityJs/talks#92]
**Your name:**
Josh Stafford

**Your talk idea, described briefly:**
I have been passively following the progression of RethinkDB, stopping to tinker with it periodically along the way.  This talk will revolve around implementing RethinkDB in a new project and exploring its pros and cons.

**Approx length: (must be less than 20 minutes to be considered*):**

10-15 minutes

**Comment by jdstafford** [comment]
WELP nevermind that: https://rethinkdb.com/blog/rethinkdb-shutdown/

**Comment by jasonrhodes** [comment]
lol wow what timing (really nice website they have, too)

**Comment by jdstafford** [comment]
So rethink doesn't appear to be going anywhere for the time being, and still has an active community despite the lack of a paid dev team.  That said, plus the fact that there is (apparently) movement toward turning rethink into a self-sustaining open source project, I might like to give this talk after all.  What are your thoughts?
