### ISSUE TITLE
Untangling Yarn

### ISSUE THREAD

**Issue by nickhudkins** [charmCityJs/talks#93]
**Nick Hudkins** 

**YA(n)PM? (Yet another package manager?) Why, Why, Why?**

**35 seconds**

People say: "Give it 2 minutes". This is me attempting to carve out 2 minutes, for people to give it 2 minutes.

**Comment by jasonrhodes** [comment]
Talks are strictly forced to stay between 1-20 minutes, sorry rejected.

**Comment by esauter5** [comment]
Why is there a `(n)`?

**Comment by nickhudkins** [comment]
Oh, cuz with the (n) it is like nPM.toLowerCase() === 'npm'

**Comment by jgaskins** [comment]
@nickhudkins Should call it a minute but get it done in 59 seconds because you're such a rebel.

**Comment by nickhudkins** [comment]
@chrisuehlinger perhaps that will be my talk. When I begin, I will just start a script that does npm install and yarn, as many times as it can. and when I end I will end with the stats.

**Comment by chrisuehlinger** [comment]
You should do a "spinning plates" style demo. Every time it finishes downloading a package, you have to think of a new package for it to download before you can proceed with your talk.

**Comment by clickclickonsal** [comment]
@nickhudkins would you like to do this as a lighting talk? I could definitely knit you in for December 7th. 😄

**Comment by jasonrhodes** [comment]
Do you really want to talk about Yarn @nickhudkins y/n

**Comment by nickhudkins** [comment]
Sure don't!

**Comment by nickhudkins** [comment]
I don't use it. Habits die hard.

**Comment by jgaskins** [comment]
I'm not sure what a Hadoop resource manager has to do with JavaScript https://hortonworks.com/apache/yarn/

**Comment by esauter5** [comment]
Talk about a hype train. This talk had so much promise, but man what a let down.

**Comment by esauter5** [comment]
(joking)

**Comment by nickhudkins** [comment]
Well it started off as a good idea, but I'm pretty tightly wound and so I
got nervous, then the whole thing unraveled. My stomach was all in knots,
so I thought the whole thing would get kind of hairy.

**Comment by jgaskins** [comment]
Sounds like you were coming apart at the seams!
