### ISSUE TITLE
R (or something else)

### ISSUE THREAD

**Issue by esauter5** [charmCityJs/talks#94]
**Your name:** 
Eric Sauter, but you can call me Jason Rhodes

**Your talk idea, described briefly:**
R is not JavaScript, but I did start learning about it last night. This talk could cover a number of things whether it be general data science / statistics stuff, some of the cool features of R, how you could integrate R and JavaScript. I may not actually even talk about R and just focus on data science in JavaScript (although talking about something other than JS could be something different and a good change of pace.

*\* Alternate talk title: Forcing yourself to learn about something you know nothing about by signing up to give a talk.

**Approx length: (must be less than 20 minutes to be considered*):**
10-15 minutes

**Comment by jgaskins** [comment]
> Eric Sauter, but you can call me Jason Rhodes

```
> SELECT name FROM people WHERE name = 'Eric Sauter';
    name
------------
Jason Rhodes
(1 row)

**Comment by chrisuehlinger** [comment]
@jgaskins I didn't know you could pull a Jason document from a SQL database.

**Comment by esauter5** [comment]
zinggggg

**Comment by jgaskins** [comment]
@chrisuehlinger You can just call the [`to_jason` function](https://www.postgresql.org/docs/9.3/static/functions-json.html#FUNCTIONS-JSON-TABLE) and it'll convert anything to @jasonrhodes.

**Comment by esauter5** [comment]
@jgaskins Yeah, but this is a JS meetup so we prefer `JASON.parse`
