### ISSUE TITLE
Intro to WebGL and Three.js

### ISSUE THREAD

**Issue by chrisuehlinger** [charmCityJs/talks#95]
**Your name:** Chris Uehlinger

**Your talk idea, described briefly:** WebGL is a pretty cool technology, but one that feels out of reach for most people. However, in this talk, I'll show how you can actually build a Three.js scene from some very basic building blocks. We'll also talk about Three.js's awesome directory of examples and dabble with some very basic VR effects.

**Approx length: (must be less than 20 minutes to be considered*):** 15-20 minutes

**Comment by esauter5** [comment]
Are you available for December, @chrisuehlinger??

**Comment by esauter5** [comment]
December 7 to be exact.

**Comment by chrisuehlinger** [comment]
Yes

**Comment by chrisuehlinger** [comment]
Works for me!

**Comment by esauter5** [comment]
Thanks @chrisuehlinger! I look forward to the first CharmCityJS meetup that takes place completely in VR
