### ISSUE TITLE
Putting code in the schools (Charlotte James)

### ISSUE THREAD

**Issue by jasonrhodes** [charmCityJs/talks#96]
**Speaker name:** Charlotte James, Communications Director at [Code in the Schools](http://www.codeintheschools.org/)

**Talk idea, described briefly:** Computer science access is an issue of educational and social justice - especially in this moment in history and especially for young people of color (ie the majority of Baltimore). Charlotte will talk about the work Code in the Schools is doing to expand access to make CS a more equitable topic of study and consequently, field of work. 

**Approx length: (must be less than 20 minutes to be considered*):** 15 min

**Comment by clickclickonsal** [comment]
http://www.codeintheschools.org/join-us/volunteer/
