### ISSUE TITLE
Docker in 7 Minutes

### ISSUE THREAD

**Issue by bolducp** [charmCityJs/talks#97]
**Your name:**  Paige Bolduc

**Your talk idea, described briefly:** A "Hello, World" talk for [Docker](https://www.docker.com/) that **assumes no familiarity at all** with Docker or container technology. I'll explain some key terminology and big picture ideas and give suggestions about resources for getting started with Docker.

**Approx length: (must be less than 20 minutes to be considered*):** 7 - 10 minutes (depending on how fast I talk)

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
Hi @bolducp! Are you available to give this talk on December 7?

**Comment by bolducp** [comment]
Hi, @esauter5! Ah, I'm sorry, but I actually have family visiting town that evening, so I can't do December 7th.

**Comment by jgaskins** [comment]
They can come, too. :-D

**Comment by bolducp** [comment]
For most of my family members, I'd definitely just invite them along to watch, but in this case it's not possible. I'm sorry! I hope you'll consider me for a different date still. :-)

**Comment by jgaskins** [comment]
lol It's all good, I'm just being silly. _Definitely_ would like to see this talk because a bite-sized Docker talk sounds great. Knowing very little about Docker, I get lost in the longer ones.

**Comment by bolducp** [comment]
@jgaskins, thanks! I had to give a lightning talk on "any technical subject" for a recent company meeting, and I chose Docker because it's a topic that I had run up against and backed away from out of confusion several times before. But once I knew I was going to be speaking in front of people, I *had* to try to figure it out. And it turns out to be really cool! So I'd love to help other tentatively interested people get started too. :-)

**Comment by esauter5** [comment]
No worries, Paige! We will check in next month and see if you are available
in January or sometime later in the new year.

**Comment by bolducp** [comment]
Sounds good! Thanks, @esauter5. Will be looking forward to it, and to meeting you and others at the November meetup too.

**Comment by esauter5** [comment]
Circling back here @bolducp. Would you like to speak at our January 4th meetup?

**Comment by bolducp** [comment]
Hi, @esauter5-- thanks for checking back in! I'm sorry to say that I've actually rather over-committed myself for January and February (I'm starting a new job on Jan. 3rd, and I've agreed to teach an Intro. to Javascript class through Girl Develop It), and so I don't think I'll have the time to prepare for a CharmCityJS talk the way that I'd want to in January or February. Should I close my talk issue on Github for now and re-open it whenever I know I'll have the time to do it well?

**Comment by esauter5** [comment]
No worries! I'll just leave it open and check back in a few months down the road.

**Comment by jasonrhodes** [comment]
@bolducp are you sick of us yet? you know you want to come talk about this at Impact Hub for our March meetup comeonnnnnn do it do it!

**Comment by bolducp** [comment]
@jasonrhodes haha, of course not sick of you guys yet! I really appreciate the encouragement. The next few weeks are pretty tight for me, but I'm definitely still interested in getting back involved in CharmCityJS and presenting (maybe in April?). I think, though, that I have a different talk I'd prefer to do, so I'm going to close this issue, but I'll open another one for your consideration soon!
