### ISSUE TITLE
JavaScript and open source hardware

### ISSUE THREAD

**Issue by johneisenhardt** [charmCityJs/talks#98]
**Your name:** 
John Eisenhardt

**Your talk idea, described briefly:**
Embedded development usually means C with a pinch of assembly and perhaps even C++ when things get fancy. 

Consider myself an embedded guy, but these days the lines have blurred between embedded, PC and web development. 

My path to JS began with creating simple web pages for embedded web-servers, then eventally fancier  Backbone front-end and NodeJS server apps. 

Recently came full circle on a prototype development, where the objective was to see how far we could get with NodeJS on an ARM7 embedded platform. 

Turns out quite far. This talk would be to provide inspiration for commercial/hobby projects that explore JS and Open Source Hardware. 

**Approx length: (must be less than 20 minutes to be considered*):**

10 minutes (no slides!). Intro, hardware example and web browser connection to a live device. 

*Secret tip: the shorter your talk is, the faster it will be accepted, usually. We get a lot of 15-20 minute talk ideas but not as many 5-10 minute ones. Tell us a quick 5 minute story!

**Comment by esauter5** [comment]
This sounds really interesting. @johneisenhardt Are you able to talk about this at our January 4th meetup?

**Comment by johneisenhardt** [comment]
Sure, I'd be happy to.

**Comment by esauter5** [comment]
Awesome. Looking forward to it

**Comment by esauter5** [comment]
Thanks for giving this talk @johneisenhardt!
